// AUTO-GENERATED by build/bundle-legacy.mjs — DO NOT EDIT THIS FILE.
// Edit the original .js / .jsx source files instead; this is just a build
// artifact that re-creates the app's single shared scope for Vite.
import React from 'react';
import * as ReactDOM from 'react-dom/client';
import confetti from 'canvas-confetti';
import '../design.css';

// The original code calls window.confetti(...) directly.
window.confetti = confetti;

// Backend base URL from Vite env. Empty -> same-origin relative calls
// (works when FastAPI serves the built SPA). Set VITE_API_BASE for a
// cross-origin dev backend (e.g. http://localhost:8000).
window.OPHTHA_API_BASE = import.meta.env.VITE_API_BASE || '';

// Google Sign-In client id (empty -> the Google button stays disabled).
window.QORA_GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID || '';

// ===== BEGIN engine/data-store.js =====
// ============================================================
// Qora — DataStore seam (rebuilt after the OphthaSim cleanup)
// ------------------------------------------------------------
// Self-contained persistence/auth seam for the Qora frontend. The
// previous engine/data-store.js depended on OphthaSim globals
// (loadProfile / CASES from the deleted data.js); this rebuild has
// NO such dependencies — it talks to the FastAPI backend directly and
// falls back to localStorage for client-only preferences.
//
// window.ApiDataStore is what qora-landing.jsx calls for login/signup.
// The Bearer token is stored under 'ophtha_api_auth' (unchanged key so
// existing sessions and qora-v2.jsx's _qv2Token() keep working).
// ============================================================

var API_AUTH_KEY = 'ophtha_api_auth';

function _apiBase() {
  return (typeof window !== 'undefined' && window.OPHTHA_API_BASE) || '';
}

function _readApiAuth() {
  try {
    var raw = localStorage.getItem(API_AUTH_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch (e) { return null; }
}

// ── Silent access-token refresh ──
// On a 401, exchange the refresh_token for a fresh access token and retry once.
// Concurrent callers share one in-flight refresh. If refresh also fails, the
// session is truly expired: clear it and bounce to the landing/login.
var _refreshInFlight = null;

function _qoraRefreshToken() {
  var auth = _readApiAuth();
  if (!auth || !auth.refresh_token) return Promise.resolve(null);
  if (_refreshInFlight) return _refreshInFlight;
  _refreshInFlight = (async function () {
    try {
      var res = await fetch(_apiBase() + '/api/auth/refresh', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ refresh_token: auth.refresh_token }),
      });
      var json = null; try { json = await res.json(); } catch (e) { json = null; }
      if (!res.ok || !json || json.success === false || !json.data || !json.data.token) {
        try { localStorage.removeItem(API_AUTH_KEY); } catch (e) {}
        if (typeof window !== 'undefined' && !window.__qoraExpiredReload) {
          window.__qoraExpiredReload = true;
          setTimeout(function () { window.location.reload(); }, 50);
        }
        return null;
      }
      try { localStorage.setItem(API_AUTH_KEY, JSON.stringify(json.data)); } catch (e) {}
      return json.data.token;
    } catch (e) {
      return null;
    } finally {
      _refreshInFlight = null;
    }
  })();
  return _refreshInFlight;
}

async function _apiFetch(path, opts, _retried) {
  opts = opts || {};
  var headers = { 'Content-Type': 'application/json' };
  var auth = _readApiAuth();
  if (auth && auth.token) headers['Authorization'] = 'Bearer ' + auth.token;
  var res = await fetch(_apiBase() + path, {
    method: opts.method || 'GET',
    headers: headers,
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  if (res.status === 401 && !_retried && path.indexOf('/api/auth/') !== 0) {
    var nt = await _qoraRefreshToken();
    if (nt) return _apiFetch(path, opts, true);
  }
  var json = null;
  try { json = await res.json(); } catch (e) { json = null; }
  if (!res.ok || (json && json.success === false)) {
    // Never swallow the error — let the UI surface / retry (contract §3).
    var msg = (json && (json.error || (json.detail && json.detail.message))) || ('HTTP ' + res.status);
    throw new Error(msg);
  }
  return json ? json.data : null;
}

// ── Client-only preferences (no backend endpoint) ──
var LocalPrefs = {
  loadSettings: function () {
    try {
      var s = localStorage.getItem('ophtha_settings');
      return Promise.resolve(s ? JSON.parse(s) : null);
    } catch (e) { return Promise.resolve(null); }
  },
  saveSettings: function (s) {
    try { localStorage.setItem('ophtha_settings', JSON.stringify(s)); } catch (e) {}
    return Promise.resolve();
  },
};

var ApiDataStore = {
  // — auth —
  login: async function (email, password) {
    var s = await _apiFetch('/api/auth/login', {
      method: 'POST', body: { email: email, password: password },
    });
    await ApiDataStore.saveAuth(s);
    return s;
  },
  signup: async function (payload) {
    var s = await _apiFetch('/api/auth/signup', { method: 'POST', body: payload });
    await ApiDataStore.saveAuth(s);
    return s;
  },
  googleLogin: async function (credential) {
    var s = await _apiFetch('/api/auth/google', { method: 'POST', body: { credential: credential } });
    await ApiDataStore.saveAuth(s);
    return s;
  },
  loadAuth: function () { return Promise.resolve(_readApiAuth()); },
  saveAuth: function (a) {
    try {
      if (a) localStorage.setItem(API_AUTH_KEY, JSON.stringify(a));
      else localStorage.removeItem(API_AUTH_KEY);
    } catch (e) {}
    return Promise.resolve();
  },

  // — profile (mapped to the UI's Profile shape) —
  loadProfile: async function () {
    var d = await _apiFetch('/api/users/me');
    return {
      name: d.full_name || '', email: d.email || '',
      school: d.school || '', year: d.year || '',
      avatarEmoji: d.avatar_emoji || '👤', avatarColor: d.avatar_color || '#5865F2',
      xp: d.xp || 0, streak: d.streak || 0,
      totalSessions: d.total_sessions || 0,
      role: d.role || 'student',
      _server: d,
    };
  },
  saveProfile: async function (p) {
    return _apiFetch('/api/users/me', {
      method: 'PATCH',
      body: {
        full_name: p.name, school: p.school, year: p.year,
        avatar_emoji: p.avatarEmoji, avatar_color: p.avatarColor,
      },
    });
  },

  loadSettings: LocalPrefs.loadSettings,
  saveSettings: LocalPrefs.saveSettings,

  listCases: function () { return _apiFetch('/api/v2/cases'); },
};

// Selector kept for API compatibility with legacy call-sites. The Qora flow
// calls window.ApiDataStore directly, so this always resolves to the API store.
function createDataStore() { return ApiDataStore; }

window.LocalPrefs = LocalPrefs;
window.ApiDataStore = ApiDataStore;
window.createDataStore = createDataStore;
window.DataStore = ApiDataStore;
window._qoraRefreshToken = _qoraRefreshToken;

// ===== END engine/data-store.js =====

// ===== BEGIN qora-catalog.js =====
// ============================================================
// Qora — clinical catalogues for the post-Assess pickers (§4.8)
// ------------------------------------------------------------
// Comprehensive, specialty-agnostic lists of investigations and
// management options for the "Data Penunjang" (investigations) and
// "Terapi" (therapy) pickers. English (product language). Expand freely.
// Exposed on window for the concatenated bundle scope.
// ============================================================

window.QORA_INVESTIGATIONS = {
  'Haematology': [
    'Full Blood Count (FBC)', 'Blood film', 'Reticulocyte count', 'ESR',
    'Haematinics (ferritin, B12, folate)', 'Iron studies', 'Coagulation screen (PT/APTT/INR)',
    'D-dimer', 'Group & Save', 'Crossmatch', 'HbA1c',
  ],
  'Biochemistry': [
    'Urea & Electrolytes (U&E)', 'Liver Function Tests (LFTs)', 'C-reactive protein (CRP)',
    'Bone profile (Ca, PO4, ALP)', 'Magnesium', 'Amylase / Lipase', 'Troponin', 'BNP',
    'Thyroid Function Tests (TFTs)', 'Fasting glucose', 'Random glucose', 'Lipid profile',
    'Serum urate', 'Creatine kinase (CK)', 'Cortisol', 'Ammonia', 'Arterial blood gas (ABG)',
    'Venous blood gas (VBG)', 'Blood ketones',
  ],
  'Endocrine & Immunology': [
    'Autoantibodies (ANA, ANCA, RF, anti-CCP)', 'Complement (C3/C4)', 'Immunoglobulins',
    'Coeliac serology (anti-tTG)', 'Beta-hCG (serum)', 'Short Synacthen test', 'Dexamethasone suppression test',
  ],
  'Microbiology & Serology': [
    'Blood cultures', 'Urine MC&S', 'Sputum MC&S', 'Stool MC&S', 'Wound swab',
    'CSF analysis (Gram stain & culture)', 'HIV / Hepatitis B / Hepatitis C serology',
    'ASO titre', 'Malaria blood film', 'COVID / Influenza swab', 'Sexual health screen (NAAT)',
    'Throat swab',
  ],
  'Urine & Bedside': [
    'Urinalysis (dipstick)', 'Urine β-hCG (pregnancy test)', 'Capillary blood glucose',
    'Capillary ketones', 'Peak expiratory flow', '12-lead ECG', 'Blood pressure',
    'Otoscopy', 'Fundoscopy',
  ],
  'Radiology & Imaging': [
    'Chest X-ray', 'Abdominal X-ray', 'Limb / joint X-ray', 'CT head', 'CT chest',
    'CT abdomen & pelvis', 'CT pulmonary angiogram (CTPA)', 'MRI brain', 'MRI spine',
    'Ultrasound abdomen', 'Ultrasound pelvis / transvaginal', 'Doppler ultrasound (leg, for DVT)',
    'Echocardiogram', 'Contrast swallow / barium study', 'Mammography', 'DEXA scan', 'V/Q scan',
  ],
  'Cardio-respiratory & Neuro': [
    '24-hour ECG (Holter)', 'Exercise tolerance test', 'Spirometry / pulmonary function tests',
    'EEG', 'Nerve conduction studies / EMG', 'Lumbar puncture',
  ],
  'Endoscopy & Procedures': [
    'Upper GI endoscopy (OGD)', 'Colonoscopy / flexible sigmoidoscopy', 'Bronchoscopy',
    'Cystoscopy', 'Nasendoscopy', 'Skin / tissue biopsy', 'Bone marrow biopsy',
    'Pleural aspiration', 'Ascitic tap',
  ],
  'Specialty-specific': [
    'Slit-lamp examination', 'Tonometry (intra-ocular pressure)', 'Visual field testing',
    'Fluorescein staining', 'Audiometry', 'Tympanometry', 'Skin scraping / Wood’s lamp',
    'Patch testing', 'Dermoscopy', 'Cervical smear', 'CTG (foetal monitoring)',
  ],
};

window.QORA_THERAPIES = {
  'Pharmacological': [
    'Simple analgesia (paracetamol)', 'NSAIDs', 'Opioid analgesia', 'Antibiotics (per local guideline)',
    'Antiemetics', 'IV fluids', 'Supplemental oxygen', 'Bronchodilators (salbutamol)',
    'Corticosteroids', 'Proton pump inhibitor (PPI)', 'Antihistamines', 'Anticoagulation',
    'Antihypertensives', 'Insulin / oral hypoglycaemics', 'Topical treatment', 'Antivirals',
    'Antifungals', 'Diuretics', 'Adrenaline (IM, anaphylaxis)',
  ],
  'Non-pharmacological': [
    'Rest / activity modification', 'Limb elevation', 'Ice / heat therapy', 'Wound care & dressing',
    'Physiotherapy', 'Occupational therapy', 'Dietary modification', 'Smoking cessation support',
    'Weight management', 'Psychological therapy (e.g. CBT)',
  ],
  'Procedures & Referral': [
    'Admit for observation', 'Urgent same-day referral', 'Surgical referral', 'Specialist referral',
    'Incision & drainage', 'Urinary catheterisation', 'Splinting / immobilisation',
    'Nebuliser therapy', 'IV access & monitoring', 'Cardioversion',
  ],
  'Education & Safety-netting': [
    'Explain the diagnosis in plain language', 'Red-flag return advice', 'Safety-netting timeframe',
    'Lifestyle advice', 'Medication counselling', 'Arrange follow-up', 'Provide written information',
    'Address ideas, concerns & expectations',
  ],
};

// ===== END qora-catalog.js =====

// ===== BEGIN qora-landing.jsx =====
// ============================================================
// Qora — English landing + auth (pivot-v4 Phase 5, Stage 2)
// ------------------------------------------------------------
// Primary entry for the multi-specialty English prototype. Self-contained:
// landing -> auth (via window.ApiDataStore.login/signup) -> reload (the App
// re-inits authed and defaults to the Qora catalogue). ADDITIVE: design.css
// tokens only (CSS hash index-Bj97HpXF.css preserved). Legacy eye app stays
// reachable via the "Classic" link. Social login = deferred plug (disabled).
// ============================================================

function QLFeature({ icon, title, body }) {
  return React.createElement('div', { className: 'as', style: {
    padding: 20, borderRadius: 'var(--r-lg)', background: 'var(--surface)',
    border: '1px solid var(--border)', boxShadow: 'var(--sh-sm)',
  } },
    React.createElement('div', { style: { fontSize: 26, marginBottom: 10 } }, icon),
    React.createElement('div', { style: { fontSize: 15, fontWeight: 700, color: 'var(--text-1)', marginBottom: 6 } }, title),
    React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', lineHeight: 1.6 } }, body));
}

function QLAuth({ mode, setMode, onLogin }) {
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState('');
  const [name, setName] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [err, setErr] = React.useState('');
  const isSignup = mode === 'signup';

  async function submit() {
    if (busy) return;
    setBusy(true); setErr('');
    try {
      if (!window.ApiDataStore) throw new Error('Backend not configured (set VITE_API_BASE).');
      const s = isSignup
        ? await window.ApiDataStore.signup({ email, password, full_name: name })
        : await window.ApiDataStore.login(email, password);
      // ApiDataStore sudah save ke 'ophtha_api_auth'
      try { localStorage.setItem('ophtha_auth', JSON.stringify(s)); } catch (e) {}
      if (onLogin) onLogin(s);
    } catch (e) {
      const m = String((e && e.message) || e);
      setErr(/40[13]|invalid|password|terdaftar|exist/i.test(m)
        ? (isSignup ? 'Could not sign up — that email may already be registered.' : 'Login failed — check your email and password.')
        : m);
      setBusy(false);
    }
  }

  const field = (label, value, set, type, ph) => React.createElement('label', { style: { display: 'block', marginBottom: 12 } },
    React.createElement('div', { style: { fontSize: 12, fontWeight: 600, color: 'var(--text-2)', marginBottom: 5 } }, label),
    React.createElement('input', {
      type: type || 'text', value, onChange: e => set(e.target.value),
      onKeyDown: e => { if (e.key === 'Enter') submit(); }, placeholder: ph, autoComplete: type === 'password' ? 'current-password' : 'on',
      style: { width: '100%', padding: '11px 13px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 14, fontFamily: 'Poppins', color: 'var(--text-1)' },
    }));

  return React.createElement('div', { className: 'as', style: { maxWidth: 400, margin: '40px auto', padding: 28, borderRadius: 'var(--r-xl)', background: 'var(--surface)', border: '1px solid var(--border)', boxShadow: 'var(--sh-lg)' } },
    React.createElement('div', { style: { fontSize: 20, fontWeight: 800, color: 'var(--text-1)', marginBottom: 4 } }, isSignup ? 'Create your account' : 'Welcome back'),
    React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', marginBottom: 20 } }, isSignup ? 'Start practising clinical interviews in minutes.' : 'Log in to continue your practice.'),
    isSignup && field('Full name', name, setName, 'text', 'Your name'),
    field('Email', email, setEmail, 'email', 'you@example.com'),
    field('Password', password, setPassword, 'password', '••••••••'),
    err && React.createElement('div', { style: { fontSize: 12.5, color: 'var(--red-d)', marginBottom: 12 } }, err),
    React.createElement('button', { onClick: submit, disabled: busy, style: { width: '100%', padding: '12px', borderRadius: 12, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 14, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer', opacity: busy ? 0.7 : 1 } }, busy ? 'Please wait…' : (isSignup ? 'Create account' : 'Log in')),
    React.createElement('button', { disabled: true, title: 'Coming soon', style: { width: '100%', marginTop: 10, padding: '11px', borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface-2)', color: 'var(--text-3)', fontSize: 13, fontWeight: 600, fontFamily: 'Poppins', cursor: 'not-allowed' } }, 'Continue with Google · coming soon'),
    React.createElement('div', { style: { textAlign: 'center', marginTop: 16, fontSize: 13, color: 'var(--text-2)' } },
      isSignup ? 'Already have an account? ' : "Don't have an account? ",
      React.createElement('button', { onClick: () => { setErr(''); setMode(isSignup ? 'login' : 'signup'); }, style: { border: 'none', background: 'none', color: 'var(--primary)', fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer', fontSize: 13 } }, isSignup ? 'Log in' : 'Sign up')));
}

function QoraLanding({ onLogin }) {
  const [view, setView] = React.useState('landing'); // landing | auth
  const [mode, setMode] = React.useState('login');
  const go = (m) => { setMode(m); setView('auth'); };

  const header = React.createElement('header', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 24px', maxWidth: 1080, margin: '0 auto' } },
    React.createElement('div', { style: { display: 'flex', alignItems: 'baseline', gap: 8 } },
      React.createElement('div', { style: { fontSize: 20, fontWeight: 800, color: 'var(--text-1)', letterSpacing: '-0.02em' } }, 'Qora'),
      React.createElement('div', { style: { fontSize: 9, color: 'var(--text-3)', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase' } }, 'Clinical interview trainer')),
    React.createElement('div', { style: { display: 'flex', gap: 8 } },
      React.createElement('button', { onClick: () => go('login'), style: { padding: '7px 14px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-2)', fontSize: 13, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Log in'),
      React.createElement('button', { onClick: () => go('signup'), style: { padding: '7px 16px', borderRadius: 10, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 13, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Get started')));

  if (view === 'auth') {
    return React.createElement('div', { style: { minHeight: '100vh' } }, header,
      React.createElement(QLAuth, { mode, setMode, onLogin }));
  }

  return React.createElement('div', { style: { minHeight: '100vh' } }, header,
    React.createElement('main', { style: { maxWidth: 900, margin: '0 auto', padding: '40px 24px 60px', textAlign: 'center' } },
      React.createElement('div', { className: 'au', style: { display: 'inline-block', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--primary)', background: 'var(--primary-l)', padding: '5px 12px', borderRadius: 999, marginBottom: 20 } }, 'Beta · for medical students & IMG exam candidates'),
      React.createElement('h1', { className: 'au', style: { fontSize: 'clamp(32px, 5vw, 52px)', fontWeight: 800, color: 'var(--text-1)', lineHeight: 1.1, letterSpacing: '-0.02em', marginBottom: 18 } },
        'Practise the patient interview, ',
        React.createElement('span', { style: { color: 'var(--primary)' } }, 'across every specialty.')),
      React.createElement('p', { className: 'au', style: { fontSize: 16, color: 'var(--text-2)', lineHeight: 1.7, maxWidth: 620, margin: '0 auto 28px' } },
        'Interview an AI patient who answers only what you ask — then get instant, transparent scoring against a hidden checklist and a full model-answer reveal. From internal medicine to emergency.'),
      React.createElement('div', { className: 'au', style: { display: 'flex', gap: 12, justifyContent: 'center', marginBottom: 48 } },
        React.createElement('button', { onClick: () => go('signup'), style: { padding: '13px 26px', borderRadius: 12, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 15, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer', boxShadow: 'var(--sh-md)' } }, 'Start practising free'),
        React.createElement('button', { onClick: () => go('login'), style: { padding: '13px 22px', borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-1)', fontSize: 15, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer' } }, 'I have an account')),
      React.createElement('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, textAlign: 'left' } },
        React.createElement(QLFeature, { icon: '🗣️', title: 'Patients that make you ask', body: "Like a real lay patient, they answer only what you ask and never volunteer the full story. You learn to elicit — not just receive." }),
        React.createElement(QLFeature, { icon: '🎯', title: 'Transparent, calibrated scoring', body: 'Per-item hit/miss against a hidden checklist, red-flag screening, and reasoning — graded conservatively, never inflated.' }),
        React.createElement(QLFeature, { icon: '🗝️', title: 'Full answer-key reveal', body: 'After every case, see exactly what a complete workup should have covered — the checklist, red flags, differentials and management.' })),
      React.createElement('div', { style: { marginTop: 40, fontSize: 12, color: 'var(--text-3)' } },
        'A study aid, not a medical device. ')));
}

window.QoraLanding = QoraLanding;

// ===== END qora-landing.jsx =====

// ===== BEGIN qora-v2.jsx =====
// ============================================================
// Qora — v2 multi-specialty experience (pivot-v4 Phase 5)
// ------------------------------------------------------------
// Self-contained screen consuming /api/v2/* (catalogue -> answer-
// restrained chat -> calibrated score + answer-key reveal).
// ADDITIVE: reuses design.css tokens only (no design.css change,
// CSS hash index-Bj97HpXF.css preserved). Requires the backend
// (window.OPHTHA_API_BASE) + a logged-in user. Same pattern as
// dev-dashboard.jsx. Copy stays English (the pivot's market).
// ============================================================

function _qv2Base() {
  return (typeof window !== 'undefined' && window.OPHTHA_API_BASE) || '';
}
function _qv2Token() {
  try {
    const raw = localStorage.getItem('ophtha_api_auth');
    const a = raw ? JSON.parse(raw) : null;
    return a && a.token ? a.token : '';
  } catch (e) { return ''; }
}
async function qv2Fetch(path, opts) {
  opts = opts || {};
  const headers = { 'Content-Type': 'application/json' };
  const tok = _qv2Token();
  if (tok) headers['Authorization'] = 'Bearer ' + tok;
  const res = await fetch(_qv2Base() + path, {
    method: opts.method || 'GET', headers,
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  let json = null;
  try { json = await res.json(); } catch (e) { json = null; }
  if (!res.ok || (json && json.success === false)) {
    throw new Error((json && (json.error || (json.detail && json.detail.message))) || ('HTTP ' + res.status));
  }
  return json ? json.data : null;
}

const QV2_SPEC_LABEL = {
  internal_medicine: 'Internal medicine', surgery: 'Surgery', paediatrics: 'Paediatrics',
  obstetrics_gynaecology: 'Obs & Gynae', psychiatry: 'Psychiatry', neurology: 'Neurology',
  ent: 'ENT', dermatology: 'Dermatology', ophthalmology: 'Ophthalmology', emergency: 'Emergency',
};

function QV2Pill({ children, tone }) {
  const t = tone || 'primary';
  return React.createElement('span', { style: {
    fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 999,
    background: `var(--${t}-l, var(--primary-l))`, color: `var(--${t}, var(--primary))`,
    textTransform: 'uppercase', letterSpacing: '0.04em',
  } }, children);
}

// ---- Catalogue ----
function QV2Catalogue({ onPick, onProgress }) {
  const [cases, setCases] = React.useState(null);
  const [specs, setSpecs] = React.useState([]);
  const [filter, setFilter] = React.useState('');
  const [err, setErr] = React.useState('');

  React.useEffect(() => {
    qv2Fetch('/api/v2/cases')
      .then(d => { setCases(d.cases || []); setSpecs(d.specialties || []); })
      .catch(e => setErr(String(e.message || e)));
  }, []);

  if (err) return React.createElement('div', { style: { padding: 40, color: 'var(--text-2)' } },
    'Could not load cases: ' + err + '. (Sign in and ensure the backend is configured.)');
  if (!cases) return React.createElement('div', { style: { padding: 40, color: 'var(--text-3)' } }, 'Loading cases…');

  const shown = filter ? cases.filter(c => c.specialty === filter) : cases;
  return React.createElement('div', { className: 'au', style: { maxWidth: 1080, margin: '0 auto', padding: '24px 20px' } },
    React.createElement('div', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 6 } },
      React.createElement('div', { style: { fontSize: 22, fontWeight: 800, color: 'var(--text-1)' } }, 'Case library'),
      onProgress && React.createElement('button', { onClick: onProgress, style: { padding: '7px 14px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-2)', fontSize: 13, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer', whiteSpace: 'nowrap' } }, '📊 My progress')),
    React.createElement('div', { style: { marginBottom: 18, fontSize: 13, color: 'var(--text-2)' } },
      shown.length + ' cases across ' + specs.length + ' specialties · the patient only answers what you ask.'),
    // specialty filter chips
    React.createElement('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 20 } },
      [['', 'All']].concat(specs.map(s => [s, QV2_SPEC_LABEL[s] || s])).map(([val, lab]) =>
        React.createElement('button', { key: val || 'all', onClick: () => setFilter(val), style: {
          padding: '6px 14px', borderRadius: 999, fontSize: 12.5, fontWeight: filter === val ? 700 : 500,
          fontFamily: 'Poppins', cursor: 'pointer',
          border: '1px solid ' + (filter === val ? 'var(--primary)' : 'var(--border)'),
          background: filter === val ? 'var(--primary-l)' : 'var(--surface)',
          color: filter === val ? 'var(--primary)' : 'var(--text-2)',
        } }, lab))),
    // cards grid
    React.createElement('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 14 } },
      shown.map((c, i) => React.createElement('button', {
        key: c.id, onClick: () => onPick(c), className: 'as', style: {
          textAlign: 'left', padding: 16, borderRadius: 'var(--r-lg)', border: '1px solid var(--border)',
          background: 'var(--surface)', boxShadow: 'var(--sh-sm)', cursor: 'pointer', fontFamily: 'Poppins',
          display: 'flex', flexDirection: 'column', gap: 8, animationDelay: (i % 8) * 0.04 + 's',
        },
      },
        React.createElement('div', { style: { display: 'flex', gap: 6, flexWrap: 'wrap' } },
          React.createElement(QV2Pill, { tone: 'primary' }, QV2_SPEC_LABEL[c.specialty] || c.specialty),
          c.mode === 'osce_full' ? React.createElement(QV2Pill, { tone: 'violet' }, 'OSCE') : React.createElement(QV2Pill, { tone: 'teal' }, 'Anamnesis')),
        React.createElement('div', { style: { fontSize: 15, fontWeight: 700, color: 'var(--text-1)', lineHeight: 1.3 } }, c.presentation),
        React.createElement('div', { style: { fontSize: 12, color: 'var(--text-3)' } }, c.chief_complaint),
        React.createElement('div', { style: { marginTop: 'auto', display: 'flex', gap: 12, fontSize: 11, color: 'var(--text-3)', fontWeight: 600 } },
          React.createElement('span', null, '◆ Difficulty ' + (c.difficulty || '–')),
          React.createElement('span', null, '⏱ ~' + (c.estimated_minutes || '–') + ' min')))))
  );
}

// ---- Assessment (DDx + management) ----
function QV2AssessField({ label, value, set, ph, area }) {
  return React.createElement('label', { style: { display: 'block', marginBottom: 12 } },
    React.createElement('div', { style: { fontSize: 12, fontWeight: 600, color: 'var(--text-2)', marginBottom: 5 } }, label),
    React.createElement(area ? 'textarea' : 'input', {
      value, onChange: (e) => set(e.target.value), placeholder: ph, rows: area ? 3 : undefined,
      style: { width: '100%', padding: '10px 12px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 13.5, fontFamily: 'Poppins', color: 'var(--text-1)', resize: area ? 'vertical' : 'none' },
    }));
}

function QV2Assess({ caseSummary, isOsce, busy, onBack, onSubmit }) {
  const [dx1, setDx1] = React.useState('');
  const [dx2, setDx2] = React.useState('');
  const [dx3, setDx3] = React.useState('');
  const [reasoning, setReasoning] = React.useState('');
  const [penunjang, setPenunjang] = React.useState('');
  const [terapi, setTerapi] = React.useState('');
  const [edukasi, setEdukasi] = React.useState('');
  const submit = () => onSubmit({ dx1, dx2, dx3, reasoning }, { penunjang, terapi, edukasi });
  return React.createElement('div', { className: 'au', style: { maxWidth: 680, margin: '0 auto', padding: 20 } },
    React.createElement('button', { onClick: onBack, style: { marginBottom: 14, padding: '6px 12px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 12, color: 'var(--text-2)', fontFamily: 'Poppins', cursor: 'pointer' } }, '← Back to interview'),
    React.createElement('div', { style: { fontSize: 20, fontWeight: 800, color: 'var(--text-1)', marginBottom: 4 } }, 'Your assessment'),
    React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', marginBottom: 18 } }, 'Commit your reasoning before the answer key is revealed.'),
    React.createElement(QV2AssessField, { label: 'Working diagnosis', value: dx1, set: setDx1, ph: 'Most likely diagnosis' }),
    React.createElement(QV2AssessField, { label: 'Differential 2', value: dx2, set: setDx2, ph: 'Alternative' }),
    React.createElement(QV2AssessField, { label: 'Differential 3', value: dx3, set: setDx3, ph: 'Alternative' }),
    React.createElement(QV2AssessField, { label: 'Clinical reasoning', value: reasoning, set: setReasoning, ph: 'Key positives, red flags, why this diagnosis…', area: true }),
    isOsce && React.createElement('div', { style: { marginTop: 8, paddingTop: 14, borderTop: '1px solid var(--border)' } },
      React.createElement('div', { style: { fontSize: 13, fontWeight: 700, color: 'var(--text-1)', marginBottom: 10 } }, '🔬 OSCE — investigations & management'),
      React.createElement(QV2AssessField, { label: 'Investigations to order', value: penunjang, set: setPenunjang, ph: 'e.g. FBC, CRP, imaging…', area: true }),
      React.createElement(QV2AssessField, { label: 'Management / treatment', value: terapi, set: setTerapi, ph: 'Immediate + definitive management…', area: true }),
      React.createElement(QV2AssessField, { label: 'Patient education & safety-netting', value: edukasi, set: setEdukasi, ph: 'What you would tell the patient…', area: true })),
    React.createElement('button', { onClick: submit, disabled: busy, style: { width: '100%', marginTop: 16, padding: 13, borderRadius: 12, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 14, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer', opacity: busy ? 0.7 : 1 } }, busy ? 'Scoring…' : 'Finish & reveal answer key'));
}

// ---- Session chat ----
// ---- Examination media viewer (specialty-agnostic) ----
// Mirrors the legacy eye-photo bar but generic over image/scan/ecg/etc. Fetches
// /api/v2/cases/{id}/media; auto-hides when a case has no media (zero visual
// change for text-only cases). Design tokens only — no design.css change.
const QV2_MEDIA_ICON = { image: '🖼', photo: '🖼', scan: '🩻', xray: '🩻', ultrasound: '🩻', ecg: '📈', fundus: '👁', slitlamp: '👁' };

function _qv2ResolveMedia(src) {
  if (!src) return '';
  if (/^https?:\/\//i.test(src)) return src;
  if (src.charAt(0) === '/') {
    const base = _qv2Base();
    return (base && src.indexOf('/api/') === 0) ? base + src : src;
  }
  if (src.indexOf('./') === 0) return src;
  return './' + src; // relative asset served by the frontend (public/exam-media/…)
}

function QV2MediaModal({ media, onClose }) {
  const [idx, setIdx] = React.useState(0);
  const [loaded, setLoaded] = React.useState(false);
  const count = media.length;
  const cur = media[idx] || media[0];
  React.useEffect(() => { setLoaded(false); }, [idx]);
  React.useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'Escape') onClose();
      else if (e.key === 'ArrowRight' && count > 1) setIdx(i => (i + 1) % count);
      else if (e.key === 'ArrowLeft' && count > 1) setIdx(i => (i - 1 + count) % count);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [count, onClose]);
  return React.createElement('div', { onClick: onClose, style: { position: 'fixed', inset: 0, zIndex: 1001, background: 'rgba(26,29,46,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, animation: 'overlayIn 0.2s ease' } },
    React.createElement('div', { onClick: (e) => e.stopPropagation(), style: { background: 'var(--surface)', borderRadius: 18, padding: 18, maxWidth: 'min(900px, 92vw)', width: '100%', maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: 'var(--sh-xl)', border: '1px solid var(--border)' } },
      React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 } },
        React.createElement('span', { style: { fontSize: 15, fontWeight: 700, color: 'var(--text-1)', flex: 1 } }, (QV2_MEDIA_ICON[cur.type] || '🔬') + ' ' + (cur.label || 'Examination media')),
        count > 1 && React.createElement('span', { style: { fontSize: 11, color: 'var(--text-3)', fontWeight: 600, fontVariantNumeric: 'tabular-nums' } }, (idx + 1) + ' / ' + count),
        React.createElement('button', { onClick: onClose, style: { padding: '6px 12px', fontSize: 12, borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-2)', fontFamily: 'Poppins', cursor: 'pointer' } }, '✕ Close')),
      React.createElement('div', { style: { position: 'relative', flex: 1, background: 'var(--surface-2)', borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', minHeight: 260 } },
        !loaded && React.createElement('div', { style: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-3)', fontSize: 12 } }, 'Loading…'),
        React.createElement('img', { src: _qv2ResolveMedia(cur.src), alt: cur.caption || cur.label || 'Examination media', onLoad: () => setLoaded(true), onError: () => setLoaded(true), style: { maxWidth: '100%', maxHeight: '70vh', objectFit: 'contain', display: 'block', opacity: loaded ? 1 : 0, transition: 'opacity 0.2s ease' } }),
        count > 1 && React.createElement('button', { onClick: () => setIdx(i => (i - 1 + count) % count), 'aria-label': 'Previous', style: { position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', width: 36, height: 36, borderRadius: '50%', background: 'rgba(0,0,0,0.55)', color: '#fff', border: 'none', fontSize: 18, cursor: 'pointer' } }, '‹'),
        count > 1 && React.createElement('button', { onClick: () => setIdx(i => (i + 1) % count), 'aria-label': 'Next', style: { position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', width: 36, height: 36, borderRadius: '50%', background: 'rgba(0,0,0,0.55)', color: '#fff', border: 'none', fontSize: 18, cursor: 'pointer' } }, '›')),
      cur.caption && React.createElement('div', { style: { marginTop: 12, fontSize: 12.5, color: 'var(--text-2)', lineHeight: 1.5 } }, cur.caption),
      count > 1 && React.createElement('div', { style: { marginTop: 8, fontSize: 10, color: 'var(--text-3)', textAlign: 'center' } }, '← → to navigate · Esc to close')));
}

function QV2MediaBar({ caseId }) {
  const [media, setMedia] = React.useState([]);
  const [open, setOpen] = React.useState(false);
  React.useEffect(() => {
    let alive = true;
    qv2Fetch('/api/v2/cases/' + encodeURIComponent(caseId) + '/media')
      .then(d => { if (alive) setMedia((d && d.media) || []); })
      .catch(() => { if (alive) setMedia([]); });
    return () => { alive = false; };
  }, [caseId]);
  if (!media.length) return null;
  return React.createElement(React.Fragment, null,
    React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 10, padding: '8px 14px', marginBottom: 10, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12 } },
      React.createElement('span', { style: { fontSize: 11, color: 'var(--text-3)', fontWeight: 700, letterSpacing: '0.04em', textTransform: 'uppercase' } }, 'Examination'),
      React.createElement('div', { style: { flex: 1 } }),
      React.createElement('button', { onClick: () => setOpen(true), style: { padding: '6px 12px', fontSize: 12, fontWeight: 600, borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface-2)', color: 'var(--text-1)', fontFamily: 'Poppins', cursor: 'pointer' } }, '🔬 View examination media' + (media.length > 1 ? ' (' + media.length + ')' : ''))),
    open && React.createElement(QV2MediaModal, { media, onClose: () => setOpen(false) }));
}

function QV2Session({ caseSummary, onScored, onExit }) {
  const [sessionId, setSessionId] = React.useState(null);
  const [messages, setMessages] = React.useState([]); // {role, text}
  const [input, setInput] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [err, setErr] = React.useState('');
  const [stage, setStage] = React.useState('chat'); // chat | assess
  const isOsce = caseSummary.mode === 'osce_full';
  const [secs, setSecs] = React.useState(15 * 60);
  const [timerOn, setTimerOn] = React.useState(false);
  const endRef = React.useRef(null);

  React.useEffect(() => {
    qv2Fetch('/api/v2/sessions', { method: 'POST', body: { case_id: caseSummary.id } })
      .then(d => { setSessionId(d.sessionId); setMessages([{ role: 'patient', text: d.openingLine || '…' }]); })
      .catch(e => setErr(String(e.message || e)));
  }, [caseSummary.id]);

  React.useEffect(() => { if (endRef.current) endRef.current.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  async function send() {
    const text = input.trim();
    if (!text || busy || !sessionId) return;
    setInput(''); setBusy(true);
    setMessages(m => m.concat([{ role: 'user', text }]));
    try {
      const d = await qv2Fetch('/api/v2/sessions/' + sessionId + '/turns', { method: 'POST', body: { text } });
      setMessages(m => m.concat([{ role: 'patient', text: d.reply }]));
    } catch (e) { setMessages(m => m.concat([{ role: 'patient', text: '(error: ' + (e.message || e) + ')' }])); }
    setBusy(false);
  }

  async function score(ddx, mgmt) {
    if (!sessionId) return;
    setBusy(true);
    try { const report = await qv2Fetch('/api/v2/sessions/' + sessionId + '/score', { method: 'POST', body: { ddx, management: mgmt } }); onScored(report); }
    catch (e) { setErr(String(e.message || e)); setBusy(false); }
  }

  React.useEffect(() => {
    if (!timerOn || stage !== 'chat') return undefined;
    const id = setInterval(() => setSecs((s) => (s > 0 ? s - 1 : 0)), 1000);
    return () => clearInterval(id);
  }, [timerOn, stage]);

  if (stage === 'assess') {
    return React.createElement(QV2Assess, { caseSummary, isOsce, busy, onBack: () => setStage('chat'), onSubmit: score });
  }

  return React.createElement('div', { style: { maxWidth: 760, margin: '0 auto', padding: '16px 16px 0', display: 'flex', flexDirection: 'column', height: 'calc(100vh - 120px)' } },
    React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 } },
      React.createElement('button', { onClick: onExit, style: { padding: '6px 12px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 12, color: 'var(--text-2)', fontFamily: 'Poppins', cursor: 'pointer' } }, '← Library'),
      React.createElement(QV2Pill, { tone: 'primary' }, QV2_SPEC_LABEL[caseSummary.specialty] || caseSummary.specialty),
      React.createElement('div', { style: { fontSize: 14, fontWeight: 700, color: 'var(--text-1)', flex: 1 } }, caseSummary.presentation),
      isOsce && React.createElement('button', { onClick: () => setTimerOn((v) => !v), title: '15-minute OSCE timer', style: { padding: '4px 10px', borderRadius: 999, border: '1px solid var(--border)', background: timerOn ? (secs < 60 ? 'var(--red-l)' : 'var(--surface-2)') : 'var(--surface)', color: timerOn ? (secs < 60 ? 'var(--red-d)' : 'var(--text-1)') : 'var(--text-3)', fontSize: 12, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, timerOn ? ('⏱ ' + String(Math.floor(secs / 60)).padStart(2, '0') + ':' + String(secs % 60).padStart(2, '0')) : '⏱ Timer')),
    React.createElement(QV2MediaBar, { caseId: caseSummary.id }),
    err && React.createElement('div', { style: { color: 'var(--red-d)', fontSize: 12, marginBottom: 8 } }, err),
    React.createElement('div', { style: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 10, padding: '8px 2px' } },
      messages.map((m, i) => React.createElement('div', { key: i, className: 'af', style: {
        alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start', maxWidth: '78%',
        padding: '10px 14px', borderRadius: 16, fontSize: 13.5, lineHeight: 1.5,
        background: m.role === 'user' ? 'var(--primary)' : 'var(--surface)',
        color: m.role === 'user' ? '#fff' : 'var(--text-1)',
        border: m.role === 'user' ? 'none' : '1px solid var(--border)', boxShadow: 'var(--sh-xs)',
      } }, m.text)),
      busy && React.createElement('div', { style: { alignSelf: 'flex-start', fontSize: 12, color: 'var(--text-3)' } }, '…'),
      React.createElement('div', { ref: endRef })),
    React.createElement('div', { style: { display: 'flex', gap: 8, padding: '12px 0 16px' } },
      React.createElement('input', {
        value: input, onChange: e => setInput(e.target.value),
        onKeyDown: e => { if (e.key === 'Enter') send(); },
        placeholder: 'Ask the patient a question…', disabled: busy,
        style: { flex: 1, padding: '11px 14px', borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 13.5, fontFamily: 'Poppins', color: 'var(--text-1)' },
      }),
      React.createElement('button', { onClick: send, disabled: busy, style: { padding: '0 18px', borderRadius: 12, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 13, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Send'),
      React.createElement('button', { onClick: () => setStage('assess'), disabled: busy, style: { padding: '0 16px', borderRadius: 12, border: '1px solid var(--primary)', background: 'var(--primary-l)', color: 'var(--primary)', fontSize: 13, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Assess →'))
  );
}

// ---- Result + answer-key reveal ----
function QV2ItemRow({ item, status }) {
  const icon = status === 'hit' ? '✅' : status === 'partial' ? '🟡' : status === 'miss' ? '⬜' : '·';
  return React.createElement('div', { style: { display: 'flex', gap: 8, alignItems: 'flex-start', fontSize: 12.5, color: 'var(--text-2)', padding: '3px 0' } },
    React.createElement('span', null, icon),
    React.createElement('span', { style: item && item.critical ? { fontWeight: 600, color: 'var(--text-1)' } : null },
      (item && item.item ? item.item : item) + (item && item.critical ? '  •critical' : '')));
}

function QV2Result({ report, caseSummary, onAgain, onLibrary }) {
  const ak = report.answer_key || {};
  const dims = report.per_dimension || {};
  // map item text -> status from per_item (loose lowercase contains match)
  const statusFor = (text) => {
    const t = String(text || '').toLowerCase();
    const hit = (report.per_item || []).find(p => t && (t.includes(String(p.item || '').toLowerCase()) || String(p.item || '').toLowerCase().includes(t)));
    return hit ? hit.status : null;
  };
  return React.createElement('div', { className: 'au', style: { maxWidth: 820, margin: '0 auto', padding: '24px 20px' } },
    React.createElement('div', { style: { fontSize: 22, fontWeight: 800, color: 'var(--text-1)' } }, 'Debrief'),
    React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', marginBottom: 18 } }, caseSummary.presentation),
    // overall + dimensions
    React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 18, padding: 18, borderRadius: 'var(--r-lg)', background: 'var(--surface)', border: '1px solid var(--border)', boxShadow: 'var(--sh-sm)', marginBottom: 16 } },
      React.createElement('div', { style: { fontSize: 38, fontWeight: 800, color: 'var(--primary)', minWidth: 56, textAlign: 'center' } }, (report.overall != null ? report.overall : 0)),
      React.createElement('div', { style: { flex: 1 } },
        Object.keys(dims).map(k => {
          const d = dims[k]; const pct = d.max ? Math.round((d.score / d.max) * 100) : 0;
          return React.createElement('div', { key: k, style: { marginBottom: 6 } },
            React.createElement('div', { style: { display: 'flex', justifyContent: 'space-between', fontSize: 11.5, color: 'var(--text-2)', fontWeight: 600, marginBottom: 2 } },
              React.createElement('span', null, k.replace(/_/g, ' ')),
              React.createElement('span', null, d.score + '/' + d.max)),
            React.createElement('div', { style: { height: 6, borderRadius: 999, background: 'var(--surface-3)' } },
              React.createElement('div', { style: { width: pct + '%', height: '100%', borderRadius: 999, background: 'var(--primary)' } })));
        }))),
    report.summary && React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', lineHeight: 1.6, padding: 14, borderRadius: 'var(--r-md)', background: 'var(--primary-ll)', marginBottom: 18 } }, report.summary),
    // answer key
    React.createElement('div', { style: { fontSize: 16, fontWeight: 800, color: 'var(--text-1)', margin: '6px 0 10px' } }, '🗝 Model answer (what a complete workup includes)'),
    (ak.anamnesis_checklist || []).map(g => React.createElement('div', { key: g.group, style: { marginBottom: 12 } },
      React.createElement('div', { style: { fontSize: 12, fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 } }, g.group.replace(/_/g, ' ')),
      (g.items || []).map((it, i) => React.createElement(QV2ItemRow, { key: i, item: it, status: statusFor(it.item) })))),
    React.createElement('div', { style: { fontSize: 12, fontWeight: 700, color: 'var(--red-d)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '8px 0 4px' } }, 'Red flags to screen'),
    (ak.red_flags || []).map((it, i) => React.createElement(QV2ItemRow, { key: i, item: it, status: statusFor(it.item) })),
    React.createElement('div', { style: { fontSize: 12, fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '12px 0 4px' } }, 'Working diagnosis & differentials'),
    React.createElement('div', { style: { fontSize: 13, color: 'var(--text-1)', fontWeight: 700 } }, (ak.expected_ddx && ak.expected_ddx.working_diagnosis) || '–'),
    React.createElement('div', { style: { fontSize: 12.5, color: 'var(--text-2)' } }, ((ak.expected_ddx && ak.expected_ddx.differentials) || []).join(' · ')),
    (ak.investigations && (ak.investigations.appropriate || []).length) ? React.createElement('div', { key: 'inv', style: { marginTop: 12 } },
      React.createElement('div', { style: { fontSize: 12, fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '4px 0' } }, 'Appropriate investigations'),
      (ak.investigations.appropriate || []).map((iv, i) => React.createElement('div', { key: i, style: { fontSize: 12.5, color: 'var(--text-2)', padding: '2px 0' } }, '• ' + iv.name + (iv.expected ? ' → ' + iv.expected : '')))) : null,
    (ak.management && ((ak.management.pharmacological || []).concat(ak.management.non_pharmacological || [], ak.management.education_safety_netting || [])).length) ? React.createElement('div', { key: 'mgmt', style: { marginTop: 12 } },
      React.createElement('div', { style: { fontSize: 12, fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '4px 0' } }, 'Management'),
      (ak.management.pharmacological || []).concat(ak.management.non_pharmacological || [], ak.management.education_safety_netting || []).map((m, i) => React.createElement('div', { key: i, style: { fontSize: 12.5, color: 'var(--text-2)', padding: '2px 0' } }, '• ' + m))) : null,
    // actions
    React.createElement('div', { style: { display: 'flex', gap: 10, marginTop: 22 } },
      React.createElement('button', { onClick: onAgain, style: { padding: '10px 18px', borderRadius: 12, border: '1px solid var(--primary)', background: 'var(--primary-l)', color: 'var(--primary)', fontSize: 13, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Try another case'),
      React.createElement('button', { onClick: onLibrary, style: { padding: '10px 18px', borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-2)', fontSize: 13, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Back to library'))
  );
}

// ---- Progress / skill view (gamification, pivot-v4 §8.6) ----
function QV2SkillBar({ label, pct }) {
  return React.createElement('div', { style: { marginBottom: 8 } },
    React.createElement('div', { style: { display: 'flex', justifyContent: 'space-between', fontSize: 12, color: 'var(--text-2)', fontWeight: 600, marginBottom: 3 } },
      React.createElement('span', null, label),
      React.createElement('span', null, pct + '%')),
    React.createElement('div', { style: { height: 7, borderRadius: 999, background: 'var(--surface-3)' } },
      React.createElement('div', { style: { width: pct + '%', height: '100%', borderRadius: 999, background: 'var(--primary)' } })));
}

function QV2Stat({ label, val }) {
  return React.createElement('div', { style: { flex: 1, padding: 16, borderRadius: 'var(--r-lg)', background: 'var(--surface)', border: '1px solid var(--border)', boxShadow: 'var(--sh-sm)', textAlign: 'center' } },
    React.createElement('div', { style: { fontSize: 26, fontWeight: 800, color: 'var(--primary)' } }, val),
    React.createElement('div', { style: { fontSize: 12, color: 'var(--text-3)', fontWeight: 600 } }, label));
}

function QV2Progress({ onBack }) {
  const [p, setP] = React.useState(null);
  const [err, setErr] = React.useState('');
  React.useEffect(() => { qv2Fetch('/api/v2/progress').then(setP).catch((e) => setErr(String(e.message || e))); }, []);
  if (err) return React.createElement('div', { style: { padding: 40, color: 'var(--text-2)' } }, 'Could not load progress: ' + err);
  if (!p) return React.createElement('div', { style: { padding: 40, color: 'var(--text-3)' } }, 'Loading progress…');
  const dimLabel = { history_coverage: 'History coverage', red_flags: 'Red-flag screening', ice_fife: 'ICE / FIFE', communication: 'Communication', diagnostic_reasoning: 'Diagnostic reasoning', investigations: 'Investigation selection', management: 'Management' };
  const dims = p.dimensionAverages || {};
  const specs = p.specialtyCounts || {};
  const dimKeys = Object.keys(dims);
  const specKeys = Object.keys(specs);
  return React.createElement('div', { className: 'au', style: { maxWidth: 820, margin: '0 auto', padding: '24px 20px' } },
    React.createElement('button', { onClick: onBack, style: { marginBottom: 14, padding: '6px 12px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 12, color: 'var(--text-2)', fontFamily: 'Poppins', cursor: 'pointer' } }, '← Library'),
    React.createElement('div', { style: { fontSize: 22, fontWeight: 800, color: 'var(--text-1)', marginBottom: 16 } }, 'Your progress'),
    React.createElement('div', { style: { display: 'flex', gap: 12, marginBottom: 22 } },
      React.createElement(QV2Stat, { label: 'XP', val: p.xp || 0 }),
      React.createElement(QV2Stat, { label: 'Sessions', val: p.totalSessions || 0 }),
      React.createElement(QV2Stat, { label: 'Cases practised', val: p.completedCases || 0 })),
    React.createElement('div', { style: { fontSize: 14, fontWeight: 700, color: 'var(--text-1)', marginBottom: 10 } }, 'Skill by dimension'),
    dimKeys.length
      ? dimKeys.map((k) => React.createElement(QV2SkillBar, { key: k, label: dimLabel[k] || k, pct: dims[k] }))
      : React.createElement('div', { style: { fontSize: 13, color: 'var(--text-3)' } }, 'Complete a case to see your skill breakdown.'),
    React.createElement('div', { style: { fontSize: 14, fontWeight: 700, color: 'var(--text-1)', margin: '20px 0 10px' } }, 'Specialty coverage'),
    React.createElement('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 8 } },
      specKeys.length
        ? specKeys.map((s) => React.createElement('span', { key: s, style: { fontSize: 12, fontWeight: 600, padding: '5px 12px', borderRadius: 999, background: 'var(--primary-l)', color: 'var(--primary)' } }, (QV2_SPEC_LABEL[s] || s) + ' · ' + specs[s]))
        : React.createElement('span', { style: { fontSize: 13, color: 'var(--text-3)' } }, 'No specialties practised yet.')));
}

// One-time answer-restraint explainer (the product's core idea).
function QV2Onboarding({ onDone }) {
  const [step, setStep] = React.useState(0);
  const slides = [
    { icon: '🗣️', title: 'The patient only answers what you ask', body: "Like a real lay patient, they won't volunteer the full story. Greet them and they greet back — they won't list symptoms until you ask." },
    { icon: '🔍', title: "Elicit, don't receive", body: 'Work the history systematically — onset, character, red flags, ideas/concerns/expectations. Every question you ask is what gets scored.' },
    { icon: '🗝️', title: 'Then see the full answer key', body: 'After you finish you get per-item hit/miss against the hidden checklist, plus the complete model answer — checklist, red flags, differentials and management.' },
  ];
  const s = slides[step], last = step === slides.length - 1;
  return React.createElement('div', { style: { position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(26,29,46,0.55)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20, animation: 'overlayIn 0.2s ease' } },
    React.createElement('div', { className: 'as', style: { maxWidth: 420, width: '100%', padding: 28, borderRadius: 'var(--r-2xl)', background: 'var(--surface)', boxShadow: 'var(--sh-xl)', textAlign: 'center' } },
      React.createElement('div', { style: { fontSize: 40, marginBottom: 14 } }, s.icon),
      React.createElement('div', { style: { fontSize: 18, fontWeight: 800, color: 'var(--text-1)', marginBottom: 10 } }, s.title),
      React.createElement('div', { style: { fontSize: 14, color: 'var(--text-2)', lineHeight: 1.65, marginBottom: 22 } }, s.body),
      React.createElement('div', { style: { display: 'flex', justifyContent: 'center', gap: 6, marginBottom: 18 } },
        slides.map((_, i) => React.createElement('div', { key: i, style: { width: i === step ? 20 : 7, height: 7, borderRadius: 999, background: i === step ? 'var(--primary)' : 'var(--border-2)', transition: 'all .2s' } }))),
      React.createElement('div', { style: { display: 'flex', gap: 10 } },
        React.createElement('button', { onClick: onDone, style: { padding: '11px 16px', borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-3)', fontSize: 13, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Skip'),
        React.createElement('button', { onClick: () => last ? onDone() : setStep(step + 1), style: { flex: 1, padding: '11px', borderRadius: 12, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 14, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, last ? 'Start practising' : 'Next'))));
}

// ---- Dashboard (Qora style, inspired by OphthaSim) ----
function QoraDashboard({ onNav, onStartCase }) {
  const [p, setP] = React.useState(null);
  const [err, setErr] = React.useState('');
  const [recent, setRecent] = React.useState([]);
  React.useEffect(() => {
    qv2Fetch('/api/v2/progress').then(setP).catch(e => setErr(String(e.message || e)));
    qv2Fetch('/api/v2/sessions?limit=5').then(d => setRecent((d && d.sessions) || [])).catch(() => {});
  }, []);
  if (err) return React.createElement('div', { style: { padding: 40, color: 'var(--text-2)', textAlign: 'center' } },
    'Could not load dashboard: ' + err);
  if (!p) return React.createElement('div', { style: { padding: 40, color: 'var(--text-3)', textAlign: 'center' } }, 'Loading dashboard…');

  const level = p.level || Math.floor((p.xp || 0) / 200) + 1;
  const levelProgress = ((p.xp || 0) % 200) / 200 * 100;
  const levelNames = ['Student','Intern','Resident','Senior Resident','Consultant','Specialist','Senior Specialist','Professor'];
  const levelName = levelNames[Math.min(level - 1, levelNames.length - 1)] || 'Student';
  const totalSessions = p.totalSessions || 0;
  const completedCases = p.completedCases || 0;
  const dims = p.dimensionAverages || {};
  const hasDims = Object.keys(dims).length > 0;
  const specs = p.specialtyCounts || {};
  const specKeys = Object.keys(specs);
  const avgScore = hasDims ? Math.round(Object.values(dims).reduce((a, b) => a + b, 0) / Object.keys(dims).length) : 0;

  // Recent sessions helper
  const specLabel = { internal_medicine: 'Internal medicine', surgery: 'Surgery', paediatrics: 'Paediatrics', obstetrics_gynaecology: 'Obs & Gynae', psychiatry: 'Psychiatry', neurology: 'Neurology', ent: 'ENT', dermatology: 'Dermatology', ophthalmology: 'Ophthalmology', emergency: 'Emergency' };

  return React.createElement('div', { style: { maxWidth: 1100, margin: '0 auto', padding: '32px 24px 60px' } },
    // Hero
    React.createElement('div', { className: 'au', style: {
      background: 'linear-gradient(135deg, var(--primary) 0%, #7C3AED 100%)',
      borderRadius: 28, padding: '36px 40px', marginBottom: 28,
      position: 'relative', overflow: 'hidden', color: '#fff',
    }},
      React.createElement('div', { style: { position: 'absolute', right: -60, top: -60, width: 320, height: 320, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.08)' } }),
      React.createElement('div', { style: { position: 'absolute', right: -20, top: -20, width: 220, height: 220, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.12)' } }),
      React.createElement('div', { style: { position: 'absolute', right: 40, top: 20, width: 140, height: 140, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.15)' } }),
      React.createElement('div', { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', position: 'relative' } },
        React.createElement('div', { style: { maxWidth: 520 } },
          React.createElement('div', { style: { display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(255,255,255,0.15)', borderRadius: 10, padding: '5px 12px', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16, backdropFilter: 'blur(8px)' } },
            React.createElement('span', { style: { fontSize: 13 } }, '👨‍⚕️'), ' Clinical Interview Trainer'),
          React.createElement('h1', { style: { fontSize: 30, fontWeight: 800, lineHeight: 1.2, marginBottom: 10 } },
            'Welcome back! 👋'),
          React.createElement('p', { style: { fontSize: 14, opacity: 0.82, marginBottom: 28, lineHeight: 1.6 } },
            'Practise taking a structured history across every specialty. Each virtual patient brings a new clinical challenge.'),
          React.createElement('div', { style: { display: 'flex', gap: 12, flexWrap: 'wrap' } },
            React.createElement('button', { onClick: () => onNav('cases'), style: { padding: '11px 22px', borderRadius: 12, border: 'none', background: '#fff', color: 'var(--primary)', fontSize: 14, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer', boxShadow: '0 4px 20px rgba(0,0,0,0.15)' } }, '▶ Start new case'),
            completedCases > 0 && React.createElement('button', { onClick: () => onNav('cases'), style: { padding: '11px 22px', borderRadius: 12, border: '1.5px solid rgba(255,255,255,0.3)', background: 'rgba(255,255,255,0.1)', color: 'rgba(255,255,255,0.9)', fontSize: 14, fontWeight: 600, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Continue practising'))),
        // XP card
        React.createElement('div', { style: { background: 'rgba(255,255,255,0.12)', backdropFilter: 'blur(12px)', borderRadius: 20, padding: '18px 22px', minWidth: 200, border: '1px solid rgba(255,255,255,0.2)' } },
          React.createElement('div', { style: { fontSize: 11, opacity: 0.7, fontWeight: 600, marginBottom: 10, textTransform: 'uppercase', letterSpacing: '0.07em' } }, 'Your Progress'),
          React.createElement('div', { style: { fontSize: 28, fontWeight: 800, lineHeight: 1 } }, 'Lv ' + level),
          React.createElement('div', { style: { fontSize: 12, opacity: 0.75, marginBottom: 14 } }, levelName),
          React.createElement('div', { style: { background: 'rgba(255,255,255,0.2)', borderRadius: 999, height: 6, marginBottom: 6 } },
            React.createElement('div', { style: { height: '100%', borderRadius: 999, background: '#fff', width: levelProgress + '%', transition: 'width 1s var(--ease-panel)' } })),
          React.createElement('div', { style: { fontSize: 11, opacity: 0.65, textAlign: 'right' } }, (p.xp || 0) + ' XP')))),

    // Stats Row
    React.createElement('div', { className: 'au', style: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 28 } },
      React.createElement(QDStat, { label: 'Cases completed', value: completedCases, icon: '📋', color: 'var(--primary)', sub: 'across ' + specKeys.length + ' specialties' }),
      React.createElement(QDStat, { label: 'Total sessions', value: totalSessions, icon: '🔥', color: 'var(--amber)', sub: 'practice encounters' }),
      React.createElement(QDStat, { label: 'Avg score', value: avgScore + '%', icon: '📈', color: 'var(--teal)', sub: hasDims ? 'across all dimensions' : 'complete a case to see' }),
      React.createElement(QDStat, { label: 'Streak', value: p.streak ? p.streak + 'd' : '0d', icon: '🏅', color: 'var(--gold)', sub: p.streak ? 'days in a row' : 'start your streak' })),

    // Two-column: Recent + Specialties
    React.createElement('div', { style: { display: 'grid', gridTemplateColumns: '1fr 340px', gap: 24 } },
      // Recent Activity
      React.createElement('div', null,
        React.createElement('div', { style: { fontSize: 14, fontWeight: 700, color: 'var(--text-1)', marginBottom: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' } },
          React.createElement('span', null, '📋 Recent sessions'),
          recent.length > 0 && React.createElement('button', { onClick: () => onNav('cases'), style: { padding: '4px 12px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 11, color: 'var(--primary)', fontFamily: 'Poppins', cursor: 'pointer', fontWeight: 600 } }, 'View all')),
        recent.length === 0 && React.createElement('div', { style: { padding: '28px 20px', textAlign: 'center', fontSize: 13, color: 'var(--text-3)', background: 'var(--surface)', borderRadius: 16, border: '1px dashed var(--border)' } },
          'Complete your first case to see activity here.'),
        React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 8 } },
          recent.slice(0, 5).map((s, i) => React.createElement('div', { key: s.sessionId || i, className: 'as', style: { display: 'flex', alignItems: 'center', gap: 14, padding: 14, borderRadius: 14, background: 'var(--surface)', border: '1px solid var(--border)', boxShadow: 'var(--sh-xs)' } },
            React.createElement('div', { style: { width: 42, height: 42, borderRadius: 12, background: 'var(--primary-l)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, flexShrink: 0 } },
              s.specialty === 'emergency' ? '🚑' : s.specialty === 'surgery' ? '🔪' : s.specialty === 'paediatrics' ? '👶' : s.specialty === 'psychiatry' ? '🧠' : s.specialty === 'ophthalmology' ? '👁' : '🩺'),
            React.createElement('div', { style: { flex: 1, minWidth: 0 } },
              React.createElement('div', { style: { fontSize: 13, fontWeight: 700, color: 'var(--text-1)', marginBottom: 2 } }, s.presentation || 'Case'),
              React.createElement('div', { style: { fontSize: 11, color: 'var(--text-3)' } }, (specLabel[s.specialty] || s.specialty) + (s.score != null ? ' · Score: ' + s.score : ' · In progress'))))))),

      // Right column: specialties + dimensions
      React.createElement('div', null,
        // Specialty coverage
        React.createElement('div', { className: 'as', style: { padding: 18, borderRadius: 'var(--r-lg)', background: 'var(--surface)', border: '1px solid var(--border)', marginBottom: 16 } },
          React.createElement('div', { style: { fontSize: 13, fontWeight: 700, color: 'var(--text-1)', marginBottom: 12 } }, '🎯 Specialty coverage'),
          specKeys.length === 0 && React.createElement('div', { style: { fontSize: 12, color: 'var(--text-3)' } }, 'No specialties practised yet.'),
          React.createElement('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 6 } },
            specKeys.map(s => React.createElement('span', { key: s, style: { fontSize: 11, fontWeight: 600, padding: '4px 10px', borderRadius: 999, background: 'var(--primary-l)', color: 'var(--primary)' } },
              (specLabel[s] || s) + ' · ' + specs[s])))),
        // Skill dimensions
        hasDims && React.createElement('div', { className: 'as', style: { padding: 18, borderRadius: 'var(--r-lg)', background: 'var(--surface)', border: '1px solid var(--border)' } },
          React.createElement('div', { style: { fontSize: 13, fontWeight: 700, color: 'var(--text-1)', marginBottom: 12 } }, '📊 Skill breakdown'),
          Object.keys(dims).map(k => {
            const dimLabel = { history_coverage: 'History', red_flags: 'Red flags', ice_fife: 'ICE/FIFE', communication: 'Communication', diagnostic_reasoning: 'Reasoning', investigations: 'Investigations', management: 'Management' };
            const pct = dims[k];
            return React.createElement('div', { key: k, style: { marginBottom: 8 } },
              React.createElement('div', { style: { display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-2)', fontWeight: 600, marginBottom: 2 } },
                React.createElement('span', null, dimLabel[k] || k),
                React.createElement('span', null, Math.round(pct) + '%')),
              React.createElement('div', { style: { height: 5, borderRadius: 999, background: 'var(--surface-3)' } },
                React.createElement('div', { style: { width: pct + '%', height: '100%', borderRadius: 999, background: 'var(--primary)', transition: 'width 0.6s ease' } })));
          })))));
}

function QDStat({ label, value, icon, color, sub }) {
  return React.createElement('div', { className: 'as', style: { padding: 18, borderRadius: 'var(--r-lg)', background: 'var(--surface)', border: '1px solid var(--border)', boxShadow: 'var(--sh-sm)' } },
    React.createElement('div', { style: { fontSize: 22, marginBottom: 6 } }, icon),
    React.createElement('div', { style: { fontSize: 24, fontWeight: 800, color } }, value),
    React.createElement('div', { style: { fontSize: 12, fontWeight: 600, color: 'var(--text-1)', marginTop: 1 } }, label),
    React.createElement('div', { style: { fontSize: 10, color: 'var(--text-3)', marginTop: 2 } }, sub));
}

function QoraV2Screen() {
  const [view, setView] = React.useState('catalogue'); // catalogue | session | result
  const [picked, setPicked] = React.useState(null);
  const [report, setReport] = React.useState(null);
  const [onboard, setOnboard] = React.useState(() => { try { return !localStorage.getItem('qora_onboarded'); } catch (e) { return true; } });
  const dismiss = () => { try { localStorage.setItem('qora_onboarded', '1'); } catch (e) {} setOnboard(false); };

  let body;
  if (view === 'session' && picked) {
    body = React.createElement(QV2Session, { caseSummary: picked, onScored: (r) => { setReport(r); setView('result'); }, onExit: () => setView('catalogue') });
  } else if (view === 'result' && report && picked) {
    body = React.createElement(QV2Result, { report, caseSummary: picked, onAgain: () => setView('catalogue'), onLibrary: () => setView('catalogue') });
  } else if (view === 'progress') {
    body = React.createElement(QV2Progress, { onBack: () => setView('catalogue') });
  } else {
    body = React.createElement(QV2Catalogue, { onPick: (c) => { setPicked(c); setReport(null); setView('session'); }, onProgress: () => setView('progress') });
  }
  return React.createElement(React.Fragment, null, onboard ? React.createElement(QV2Onboarding, { onDone: dismiss }) : null, body);
}

window.QoraV2Screen = QoraV2Screen;
window.QoraDashboard = QoraDashboard;

// ===== END qora-v2.jsx =====

// ===== BEGIN inline App (from Virtual Patient Simulator.html) =====
    // ============================================================
    // Qora — Standalone App with Dashboard + Cases
    // ============================================================

    function loadAuth() {
      try {
        const raw = localStorage.getItem('ophtha_api_auth');
        return raw ? JSON.parse(raw) : null;
      } catch(e) { return null; }
    }
    function saveAuth(auth) {
      try {
        if (auth) localStorage.setItem('ophtha_api_auth', JSON.stringify(auth));
        else localStorage.removeItem('ophtha_api_auth');
      } catch(e) {}
    }

    function App() {
      const [auth, setAuth] = React.useState(loadAuth);
      const [screen, setScreen] = React.useState(() => loadAuth() ? 'dashboard' : 'qora-landing');
      const [screenKey, setScreenKey] = React.useState(0);
      const [showSettings, setShowSettings] = React.useState(false);

      const navigate = React.useCallback((s) => {
        setScreen(s);
        setScreenKey(k => k + 1);
        window.scrollTo(0, 0);
      }, []);

      const handleLogin = React.useCallback((credentials) => {
        setAuth(credentials);
        navigate('dashboard');
      }, [navigate]);

      const handleLogout = React.useCallback(() => {
        setAuth(null);
        saveAuth(null);
        try { localStorage.removeItem('ophtha_auth'); } catch(e) {}
        try { localStorage.removeItem('ophtha_api_auth'); } catch(e) {}
        navigate('qora-landing');
      }, [navigate]);

      React.useEffect(() => {
        const t = setTimeout(() => {
          document.querySelectorAll('.au,.af,.as,.ab,.ar,.al').forEach(el => {
            el.style.opacity = '1';
            el.style.transform = 'none';
          });
        }, 900);
        return () => clearTimeout(t);
      }, [screenKey]);

      const closeSettings = () => setShowSettings(false);
      const isLoggedIn = screen !== 'qora-landing';

      return React.createElement(React.Fragment, null,
        // Qora header (logged in screens)
        isLoggedIn && React.createElement('header', { style: {
          position: 'sticky', top: 0, zIndex: 100,
          background: 'rgba(245,247,255,0.88)',
          backdropFilter: 'blur(20px)',
          borderBottom: '1px solid var(--border)',
          padding: '0 24px', height: 60,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }},
          React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }, onClick: () => navigate('dashboard') },
            React.createElement('div', null,
              React.createElement('div', { style: { fontSize: 14, fontWeight: 800, color: 'var(--text-1)', lineHeight: 1 } }, 'Qora'),
              React.createElement('div', { style: { fontSize: 9, color: 'var(--text-3)', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase' } }, 'Clinical Interview Trainer'))),
          // Nav
          React.createElement('nav', { style: { display: 'flex', gap: 4 } },
            [['dashboard','Dashboard'],['cases','Cases']].map(function(pair) {
              var s = pair[0], l = pair[1];
              return React.createElement('button', { key: s, onClick: function() { navigate(s); }, style: {
                padding: '6px 14px', borderRadius: 10, border: 'none',
                background: screen === s ? 'var(--primary-l)' : 'transparent',
                color: screen === s ? 'var(--primary)' : 'var(--text-2)',
                fontSize: 13, fontWeight: screen === s ? 700 : 500,
                cursor: 'pointer', transition: 'all 0.18s ease',
                fontFamily: 'Poppins',
              } }, l);
            })),
          // Right side
          React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 10 } },
            React.createElement('button', { onClick: function() { setShowSettings(true); }, style: {
              width: 32, height: 32, borderRadius: 8, border: '1px solid var(--border)',
              background: 'var(--surface)', cursor: 'pointer', fontSize: 14,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }, title: 'Settings' }, '⚙️'),
            React.createElement('button', { onClick: handleLogout, style: {
              width: 32, height: 32, borderRadius: '50%',
              background: 'var(--primary)', color: '#fff',
              border: 'none', fontSize: 14, fontWeight: 700, cursor: 'pointer',
              fontFamily: 'Poppins',
            }, title: 'Log out' },
              auth && auth.email ? auth.email[0].toUpperCase() : '?'))),

        // Main content
        React.createElement('main', { key: screenKey, style: { flex: 1 } },
          screen === 'qora-landing' && React.createElement(QoraLanding, { onLogin: handleLogin }),
          screen === 'dashboard' && React.createElement(QoraDashboard, { onNav: navigate }),
          screen === 'cases' && React.createElement(QoraV2Screen, null)),

        // Settings drawer
        showSettings && React.createElement('div', { style: { position: 'fixed', inset: 0, zIndex: 1000, animation: 'overlayIn 0.2s ease' } },
          React.createElement('div', { onClick: closeSettings, style: { position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.3)' } }),
          React.createElement('div', { style: { position: 'absolute', right: 0, top: 0, bottom: 0, width: 320, background: 'var(--surface)', boxShadow: 'var(--sh-xl)', padding: 24, display: 'flex', flexDirection: 'column' } },
            React.createElement('div', { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 } },
              React.createElement('div', { style: { fontSize: 16, fontWeight: 800, color: 'var(--text-1)' } }, 'Settings'),
              React.createElement('button', { onClick: closeSettings, style: { padding: '6px 12px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer', fontSize: 12, fontFamily: 'Poppins' } }, '✕ Close')),
            React.createElement('div', { style: { fontSize: 13, color: 'var(--text-2)', lineHeight: 1.6 } },
              React.createElement('p', null, 'Logged in as: ', React.createElement('strong', null, (auth && auth.email) || '–')),
              React.createElement('p', null, 'Role: ', (auth && auth.role) || '–'),
              React.createElement('p', { style: { marginTop: 20, fontSize: 11, color: 'var(--text-3)' } }, 'Qora \u2014 Clinical Interview Trainer v0.16.0')),
            React.createElement('div', { style: { marginTop: 'auto' } },
              React.createElement('button', { onClick: handleLogout, style: { width: '100%', padding: 11, borderRadius: 12, border: '1px solid var(--red)', background: 'var(--red-l)', color: 'var(--red-d)', fontSize: 13, fontWeight: 700, fontFamily: 'Poppins', cursor: 'pointer' } }, 'Log out')))));
    }

    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(React.createElement(App));


// ===== END inline App =====
