"""Phase 4 continuation — specs part 2 (Peds, OBGYN, Neuro, Psych, Surgery, MSK, Derm, ENT, Ophthal)."""
from __future__ import annotations

FAMILIES2: list[dict] = [
# ── PAEDIATRICS (10) ────────────────────────────────────────────────
dict(id="fam_child_diarrhea", spec="paediatrics", tid="Diare Akut Anak", ten="Acute Childhood Diarrhea",
     complaints=["Child with frequent watery stools", "Child vomiting with diarrhea"],
     pop=["child", "toddler"], stages=["preclinical", "koas"],
     skd=["sistem_gastroenteritis-termasuk-kolera-giardiasis"],
     obj=["Grade dehydration in children", "Give ORS/zinc counseling", "Spot red flags needing admission"],
     diffs=["Disentri", "Intususepsi", "Infeksi saluran kemih"],
     variants=[
        dict(sfx="no_dehyd", title="Child diarrhea without dehydration", angle="child",
             anchor="sistem_gastroenteritis-termasuk-kolera-giardiasis", age=3, sex="male", setting="primary care"),
        dict(sfx="some_dehyd", title="Child diarrhea with some dehydration", angle="child",
             anchor="sistem_gastroenteritis-termasuk-kolera-giardiasis", age=2, sex="female", setting="emergency department"),
        dict(sfx="severe_dehyd", title="Child diarrhea with severe dehydration", angle="severe",
             anchor="sistem_gastroenteritis-termasuk-kolera-giardiasis", age=1, sex="male", setting="emergency department"),
     ]),
dict(id="fam_child_pneumonia", spec="paediatrics", tid="Pneumonia Anak", ten="Childhood Pneumonia",
     complaints=["Child with fast breathing and fever", "Child coughing with chest indrawing"],
     pop=["child", "infant"], stages=["koas"],
     skd=["sistem_bronkopneumonia", "sistem_bronkiolitis"],
     obj=["Count RR + danger signs", "Start amoxicillin pathway + referral triage", "Counsel immunization/nutrition"],
     diffs=["Bronkiolitis", "Asma", "TB anak"],
     variants=[
        dict(sfx="nonsevere", title="Non-severe pneumonia in a child", angle="child",
             anchor="sistem_bronkopneumonia", age=4, sex="female", setting="primary care"),
        dict(sfx="severe", title="Severe pneumonia with danger signs", angle="severe",
             anchor="sistem_bronkopneumonia", age=2, sex="male", setting="emergency department"),
        dict(sfx="bronchiolitis", title="Wheezy infant (bronchiolitis pattern)", angle="child",
             anchor="sistem_bronkiolitis", age=1, sex="female", setting="emergency department"),
     ]),
dict(id="fam_febrile_seizure", spec="paediatrics", tid="Kejang Demam", ten="Febrile Seizure",
     complaints=["Child had a fit during fever", "Shaking fit that stopped by itself"],
     pop=["child", "toddler"], stages=["preclinical", "koas"],
     skd=["sistem_kejang-demam-sederhana", "sistem_kejang-demam-komplikata"],
     obj=["Distinguish simple vs complex features", "Reassure + antipyretic counseling", "Refer complex/prolonged fits"],
     diffs=["Meningitis", "Epilepsi", "Kejang metabolik"],
     variants=[
        dict(sfx="simple", title="Simple febrile seizure, back to baseline", angle="child",
             anchor="sistem_kejang-demam-sederhana", age=2, sex="male", setting="emergency department"),
        dict(sfx="complex", title="Prolonged/focal febrile seizure", angle="severe",
             anchor="sistem_kejang-demam-komplikata", age=3, sex="female", setting="emergency department"),
     ]),
dict(id="fam_malnutrition", spec="paediatrics", tid="Malnutrisi Anak", ten="Child Malnutrition",
     complaints=["Child very thin with poor appetite", "Child not gaining weight"],
     pop=["child", "toddler"], stages=["koas"],
     skd=["sistem_malnutrisi-energi-protein-40", "sistem_stunting-perawakan-pendek"],
     obj=["Plot growth + edema check", "Classify moderate vs severe", "Start nutrition rehabilitation + infection screen"],
     diffs=["TB anak", "Cacingan", "Penyakit kronik"],
     variants=[
        dict(sfx="moderate", title="Moderate wasting without edema", angle="child",
             anchor="sistem_malnutrisi-energi-protein-40", age=3, sex="female", setting="primary care"),
        dict(sfx="severe_edema", title="Severe malnutrition with edema", angle="severe",
             anchor="sistem_malnutrisi-energi-protein-40", age=2, sex="male", setting="emergency department"),
     ]),
dict(id="fam_croup", spec="paediatrics", tid="Croup", ten="Croup Syndrome",
     complaints=["Child with barking cough at night", "Noisy breathing with hoarse voice"],
     pop=["child"], stages=["koas"],
     skd=["sistem_sindroma-croup"],
     obj=["Grade stridor + distress", "Give nebulized/steroid pathway", "Decide admission vs home observation"],
     diffs=["Benda asing jalan napas", "Epiglotitis", "Asma"],
     variants=[
        dict(sfx="mild", title="Mild croup without stridor at rest", angle="child",
             anchor="sistem_sindroma-croup", age=3, sex="male", setting="primary care"),
        dict(sfx="moderate", title="Croup with stridor at rest", angle="severe",
             anchor="sistem_sindroma-croup", age=2, sex="female", setting="emergency department"),
     ]),
dict(id="fam_measles", spec="paediatrics", tid="Campak", ten="Measles",
     complaints=["Fever with red rash spreading down", "Cough-red eyes-rash triad"],
     pop=["child", "unvaccinated"], stages=["preclinical", "koas"],
     skd=["sistem_morbili-campak-tanpa-komplikasi", "sistem_morbili-campak"],
     obj=["Elicit vaccine + contact history", "Give vitamin A + supportive care", "Detect pneumonia/eye complications"],
     diffs=["Rubela", "Varisela", "Drug eruption"],
     variants=[
        dict(sfx="uncomplicated", title="Uncomplicated measles", angle="child",
             anchor="sistem_morbili-campak-tanpa-komplikasi", age=5, sex="female", setting="primary care"),
        dict(sfx="complicated", title="Measles with pneumonia complication", angle="severe",
             anchor="sistem_morbili-campak", age=4, sex="male", setting="emergency department"),
     ]),
dict(id="fam_chickenpox", spec="paediatrics", tid="Varisela", ten="Chickenpox",
     complaints=["Itchy blister rash all over", "Fever with crops of blisters"],
     pop=["child", "school-age"], stages=["preclinical", "koas"],
     skd=["sistem_varisela"],
     obj=["Stage the lesions", "Give symptomatic care + isolation advice", "Spot bacterial superinfection"],
     diffs=["Impetigo", "Skabies", "Gigitan serangga"],
     variants=[
        dict(sfx="typical", title="Typical childhood chickenpox", angle="child",
             anchor="sistem_varisela", age=6, sex="male", setting="primary care"),
        dict(sfx="superinfected", title="Chickenpox with superinfected lesions", angle="complicated",
             anchor="sistem_varisela", age=5, sex="female", setting="primary care"),
     ]),
dict(id="fam_neonatal", spec="paediatrics", tid="Bayi dengan Tanda Bahaya", ten="Neonate with Danger Signs",
     complaints=["Newborn refusing to feed", "Baby unusually sleepy with fever"],
     pop=["neonate"], stages=["koas"],
     skd=["sistem_kejang-pada-neonatus"],
     obj=["Check neonatal danger signs fast", "Keep warm + glucose + urgent referral", "Counsel mother on warning signs"],
     diffs=["Sepsis neonatorum", "Ikterus", "Asfiksia"],
     variants=[
        dict(sfx="sepsis_like", title="Neonate with poor feeding and lethargy", angle="severe",
             anchor="sistem_kejang-pada-neonatus", age=0, sex="female", setting="emergency department"),
        dict(sfx="seizure_like", title="Neonatal jitteriness/seizure-like movements", angle="severe",
             anchor="sistem_kejang-pada-neonatus", age=0, sex="male", setting="emergency department"),
     ]),
dict(id="fam_pertussis", spec="paediatrics", tid="Pertusis", ten="Pertussis",
     complaints=["Child with fits of coughing and vomiting", "Whooping cough spells"],
     pop=["child", "infant"], stages=["koas"],
     skd=["sistem_pertusis"],
     obj=["Elicit paroxysm/whoop/vomiting pattern", "Arrange macrolide + prophylaxis counseling", "Watch apnea in infants"],
     diffs=["Bronkitis akut", "Asma", "Benda asing"],
     variants=[
        dict(sfx="typical", title="Classic pertussis in a child", angle="child",
             anchor="sistem_pertusis", age=5, sex="female", setting="primary care"),
        dict(sfx="infant_apnea", title="Pertussis in a young infant with apnea risk", angle="severe",
             anchor="sistem_pertusis", age=0, sex="male", setting="emergency department"),
     ]),
dict(id="fam_worms", spec="paediatrics", tid="Cacingan", ten="Intestinal Worms",
     complaints=["Child with itchy bottom at night", "Worms seen in stool"],
     pop=["child"], stages=["preclinical", "koas"], cross=["internal_medicine"],
     skd=["sistem_oxyuriasis", "sistem_askariasis", "sistem_penyakit-cacingan"],
     obj=["Elicit hygiene + household pattern", "Give single-dose deworming + family counseling", "Screen for anemia/malnutrition"],
     diffs=["Dermatitis perianal", "Gastroenteritis", "Alergi"],
     variants=[
        dict(sfx="pinworm", title="Pinworm with nocturnal itching", angle="child",
             anchor="sistem_oxyuriasis", age=7, sex="female", setting="primary care"),
        dict(sfx="ascariasis", title="Ascariasis with abdominal complaints", angle="child",
             anchor="sistem_askariasis", age=8, sex="male", setting="primary care"),
     ]),
# ── OBSTETRICS & GYNAECOLOGY (12) ───────────────────────────────────
dict(id="fam_anc", spec="obstetrics_gynaecology", tid="Asuhan Antenatal", ten="Antenatal Care",
     complaints=["Routine pregnancy check-up", "Pregnant with mild complaints"],
     pop=["pregnant woman"], stages=["preclinical", "koas"],
     skd=["sistem_antenatal-care-terpadu-berdasarkan-buku-kia", "sistem_kehamilan-normal", "sistem_anemia-defisiensi-besi-pada-kehamilan"],
     obj=["Take focused ANC history", "Track fundal height/BP/urine protein", "Give iron/folate + birth planning"],
     diffs=["Anemia kehamilan", "Hipertensi gestasional", "Infeksi saluran kemih"],
     variants=[
        dict(sfx="routine", title="Routine ANC visit, low risk", angle="pregnancy",
             anchor="sistem_antenatal-care-terpadu-berdasarkan-buku-kia", age=26, sex="female", setting="primary care"),
        dict(sfx="anemia_preg", title="Pregnancy with iron-deficiency anemia", angle="pregnancy",
             anchor="sistem_anemia-defisiensi-besi-pada-kehamilan", age=29, sex="female", setting="primary care"),
        dict(sfx="normal_counsel", title="Normal pregnancy with birth-plan counseling", angle="pregnancy",
             anchor="sistem_kehamilan-normal", age=24, sex="female", setting="primary care"),
     ]),
dict(id="fam_hyperemesis", spec="obstetrics_gynaecology", tid="Mual Muntah Kehamilan", ten="Nausea and Vomiting in Pregnancy",
     complaints=["Severe vomiting in early pregnancy", "Cannot keep any food down"],
     pop=["pregnant woman", "first trimester"], stages=["koas"],
     skd=["sistem_emesis-gravidarum", "sistem_hiperemesis-gravidarum"],
     obj=["Grade severity + ketone/dehydration check", "Start fluids/antiemetics pathway", "Exclude molar/ectopic mimics"],
     diffs=["Gastroenteritis", "Kehamilan ektopik", "Mola hidatidosa"],
     variants=[
        dict(sfx="mild", title="Mild emesis with maintained intake", angle="pregnancy",
             anchor="sistem_emesis-gravidarum", age=25, sex="female", setting="primary care"),
        dict(sfx="severe", title="Hyperemesis with dehydration and ketonuria", angle="severe",
             anchor="sistem_hiperemesis-gravidarum", age=27, sex="female", setting="emergency department"),
     ]),
dict(id="fam_hdp", spec="obstetrics_gynaecology", tid="Hipertensi pada Kehamilan", ten="Hypertension in Pregnancy",
     complaints=["High blood pressure found in pregnancy", "Headache and swelling late in pregnancy"],
     pop=["pregnant woman", "third trimester"], stages=["koas"],
     skd=["sistem_antenatal-care-terpadu-berdasarkan-buku-kia", "sistem_eklampsia", "sistem_sindrom-hellp"],
     obj=["Measure BP + proteinuria correctly", "Recognize severe-feature thresholds", "Stabilize and refer urgently"],
     diffs=["Hipertensi kronik", "Eklampsia", "Sindrom HELLP"],
     variants=[
        dict(sfx="gest_htn", title="Raised BP in pregnancy needing workup", angle="pregnancy",
             anchor="sistem_antenatal-care-terpadu-berdasarkan-buku-kia", age=30, sex="female", setting="primary care"),
        dict(sfx="severe_features", title="Severe features with headache/visual change", angle="severe",
             anchor="sistem_eklampsia", age=32, sex="female", setting="emergency department"),
        dict(sfx="hellp", title="HELLP-pattern labs with upper abdominal pain", angle="severe",
             anchor="sistem_sindrom-hellp", age=34, sex="female", setting="emergency department"),
     ]),
dict(id="fam_ectopic", spec="obstetrics_gynaecology", tid="Kehamilan Ektopik", ten="Ectopic Pregnancy",
     complaints=["Lower abdominal pain with missed period", "Vaginal spotting with faintness"],
     pop=["woman of reproductive age"], stages=["koas"],
     skd=["sistem_kehamilan-ektopik-terganggu"],
     obj=["Link amenorrhea + pain + bleeding", "Order pregnancy test + ultrasound pathway", "Resuscitate ruptured cases + urgent referral"],
     diffs=["Abortus", "Apendisitis", "Ruptur kista ovarium"],
     variants=[
        dict(sfx="stable_workup", title="Suspected ectopic, currently stable", angle="complicated",
             anchor="sistem_kehamilan-ektopik-terganggu", age=28, sex="female", setting="emergency department"),
        dict(sfx="ruptured", title="Ruptured ectopic with shock signs", angle="severe",
             anchor="sistem_kehamilan-ektopik-terganggu", age=31, sex="female", setting="emergency department"),
     ]),
dict(id="fam_pph", spec="obstetrics_gynaecology", tid="Perdarahan Pascasalin", ten="Postpartum Hemorrhage",
     complaints=["Heavy bleeding after delivery", "Bleeding that will not stop after birth"],
     pop=["postpartum woman"], stages=["koas"],
     skd=["sistem_atonia-uteri", "sistem_retensio-sisa-plasenta"],
     obj=["Quantify loss + uterine tone check", "Massage + uterotonics + fluids pathway", "Escalate to referral/balloon/surgical pathway"],
     diffs=["Retensio plasenta", "Laserasi jalan lahir", "Koagulopati"],
     variants=[
        dict(sfx="atony", title="Atonic bleeding after vaginal birth", angle="severe",
             anchor="sistem_atonia-uteri", age=29, sex="female", setting="primary care"),
        dict(sfx="retained", title="Bleeding with retained placental tissue", angle="severe",
             anchor="sistem_retensio-sisa-plasenta", age=33, sex="female", setting="emergency department"),
     ]),
dict(id="fam_prom", spec="obstetrics_gynaecology", tid="Ketuban Pecah Dini dan Prematuritas", ten="PROM and Preterm Labour",
     complaints=["Watery fluid leaking from vagina", "Regular tightening before due date"],
     pop=["pregnant woman"], stages=["koas"],
     skd=["sistem_ketuban-pecah-dini", "sistem_partus-prematurus-iminen"],
     obj=["Confirm pooling/ferning pathway", "Start antibiotics/steroid pathway per gestation", "Arrange timely referral"],
     diffs=["Inkontinensia urin", "Keputihan", "Persalinan cukup bulan"],
     variants=[
        dict(sfx="term_prom", title="Term PROM without infection signs", angle="pregnancy",
             anchor="sistem_ketuban-pecah-dini", age=27, sex="female", setting="primary care"),
        dict(sfx="preterm_threat", title="Threatened preterm labour", angle="severe",
             anchor="sistem_partus-prematurus-iminen", age=30, sex="female", setting="emergency department"),
     ]),
dict(id="fam_abortion", spec="obstetrics_gynaecology", tid="Abortus", ten="Miscarriage Spectrum",
     complaints=["Bleeding in early pregnancy", "Cramping with tissue passage"],
     pop=["pregnant woman", "first trimester"], stages=["koas"],
     skd=["sistem_abortus-insipien-kurang-dari-13-minggu", "sistem_abortus-inkomplit-kurang-dari-13-minggu", "sistem_abortus-iminen"],
     obj=["Stage threatened/inevitable/incomplete", "Decide expectant vs evacuation pathway", "Give rhesus/infection counseling"],
     diffs=["Kehamilan ektopik", "Mola hidatidosa", "Perdarahan implantasi"],
     variants=[
        dict(sfx="threatened", title="Threatened miscarriage, os closed", angle="pregnancy",
             anchor="sistem_abortus-insipien-kurang-dari-13-minggu", age=26, sex="female", setting="primary care"),
        dict(sfx="incomplete", title="Incomplete miscarriage with heavy flow", angle="complicated",
             anchor="sistem_abortus-inkomplit-kurang-dari-13-minggu", age=29, sex="female", setting="emergency department"),
        dict(sfx="imminent", title="Imminent loss needing urgent referral", angle="severe",
             anchor="sistem_abortus-iminen", age=31, sex="female", setting="emergency department"),
     ]),
dict(id="fam_discharge", spec="obstetrics_gynaecology", tid="Keputihan", ten="Vaginal Discharge",
     complaints=["Itchy white discharge", "Foul-smelling discharge"],
     pop=["woman of reproductive age"], stages=["preclinical", "koas"],
     skd=["sistem_vulvovaginitis-candida", "sistem_vaginosis-bakterialis", "sistem_sindrom-duh-discharge-genital-gonore-dan-non-gonore"],
     obj=["Characterize discharge + risk history", "Apply syndromic management pathway", "Give partner + prevention counseling"],
     diffs=["Kandidosis", "Vaginosis bakterialis", "Servisitis gonore"],
     variants=[
        dict(sfx="candida", title="Curdy itchy discharge (candida pattern)", angle="typical",
             anchor="sistem_vulvovaginitis-candida", age=24, sex="female", setting="primary care"),
        dict(sfx="bv", title="Fishy discharge (bacterial vaginosis pattern)", angle="typical",
             anchor="sistem_vaginosis-bakterialis", age=28, sex="female", setting="primary care"),
        dict(sfx="cervicitis", title="Purulent discharge with STI risk", angle="complicated",
             anchor="sistem_sindrom-duh-discharge-genital-gonore-dan-non-gonore", age=22, sex="female", setting="primary care"),
     ]),
dict(id="fam_aub", spec="obstetrics_gynaecology", tid="Perdarahan Uterus Abnormal", ten="Abnormal Uterine Bleeding",
     complaints=["Very heavy periods with clots", "Bleeding between periods"],
     pop=["woman of reproductive age", "perimenopausal"], stages=["koas"],
     skd=["sistem_perdarahan-uterus-abnormal-berat"],
     obj=["Quantify loss + anemia signs", "Order pregnancy test + ultrasound pathway", "Stabilize heavy bleeders + refer"],
     diffs=["Abortus", "Mioma", "Kehamilan ektopik"],
     variants=[
        dict(sfx="heavy_stable", title="Heavy menstrual bleeding, stable", angle="typical",
             anchor="sistem_perdarahan-uterus-abnormal-berat", age=38, sex="female", setting="primary care"),
        dict(sfx="severe_anemic", title="Heavy bleeding with symptomatic anemia", angle="severe",
             anchor="sistem_perdarahan-uterus-abnormal-berat", age=44, sex="female", setting="emergency department"),
     ]),
dict(id="fam_kb", spec="obstetrics_gynaecology", tid="Keluarga Berencana", ten="Family Planning",
     complaints=["Want to discuss contraception", "Choosing birth control after delivery"],
     pop=["woman of reproductive age"], stages=["preclinical", "koas"],
     skd=["sistem_keluarga-berencana-masa-nifas"],
     obj=["Elicit preferences + contraindications", "Compare method effectiveness", "Counsel side effects + follow-up"],
     diffs=["Amenorea laktasi", "Infertilitas", "Efek samping metode"],
     variants=[
        dict(sfx="postpartum_choice", title="Postpartum method choice", angle="typical",
             anchor="sistem_keluarga-berencana-masa-nifas", age=28, sex="female", setting="primary care"),
        dict(sfx="side_effects", title="Contraceptive side-effect review", angle="chronic",
             anchor="sistem_keluarga-berencana-masa-nifas", age=32, sex="female", setting="primary care"),
     ]),
dict(id="fam_mastitis", spec="obstetrics_gynaecology", tid="Mastitis Laktasi", ten="Lactational Mastitis",
     complaints=["Painful red breast while breastfeeding", "Breast lump with fever after delivery"],
     pop=["postpartum woman", "breastfeeding"], stages=["preclinical", "koas"],
     skd=["sistem_mastitis"],
     obj=["Distinguish engorgement vs mastitis vs abscess", "Support continued feeding + antibiotics pathway", "Spot abscess needing drainage"],
     diffs=["Bendungan ASI", "Abses payudara", "Selulitis"],
     variants=[
        dict(sfx="early", title="Early mastitis without abscess", angle="typical",
             anchor="sistem_mastitis", age=27, sex="female", setting="primary care"),
        dict(sfx="abscess_watch", title="Mastitis with fluctuant collection", angle="complicated",
             anchor="sistem_mastitis", age=30, sex="female", setting="primary care"),
     ]),
dict(id="fam_labor", spec="obstetrics_gynaecology", tid="Persalinan Lama", ten="Prolonged Labour",
     complaints=["Contractions for many hours without progress", "Labour not advancing"],
     pop=["woman in labour"], stages=["koas"],
     skd=["sistem_partus-lama", "sistem_partus-tak-maju"],
     obj=["Plot partograph thinking", "Detect CPD/malpresentation/obstruction", "Refer before rupture/sepsis"],
     diffs=["Persalinan normal", "Disproporsi kepala panggul", "Gawat janin"],
     variants=[
        dict(sfx="prolonged", title="Prolonged labour needing referral", angle="severe",
             anchor="sistem_partus-lama", age=26, sex="female", setting="primary care"),
        dict(sfx="arrest", title="Arrest of progress with maternal exhaustion", angle="severe",
             anchor="sistem_partus-tak-maju", age=29, sex="female", setting="emergency department"),
     ]),
]
