"""Phase 4 continuation — curated disease-family specs anchored to EXACT SKD 2026 catalog IDs.

Rules honored:
- Every `skd` id MUST exist in content/v3/catalog/skd2026_master_catalog.json
  (generator asserts; missing = hard fail, never silent).
- Each variant anchors to ONE exact catalog entry; its competency.category is
  READ from that entry (never guessed from the disease name).
- Forensik/medikolegal rows are excluded by rule (not bedside-trainer content).
- Duplicate catalog rows (`__2` suffixed) are canonicalized to one family.
- No SKDI 3A/3B/4A inference (legacy crosswalk only if verified — it isn't).
"""
from __future__ import annotations

# angle: typical | complicated | severe | pregnancy | child | elderly | chronic | early
FAMILIES: list[dict] = [
# ── INTERNAL MEDICINE (17) ──────────────────────────────────────────────
dict(id="fam_dm2", spec="internal_medicine", tid="Diabetes Mellitus Tipe 2", ten="Type 2 Diabetes Mellitus",
     complaints=["Increased thirst and frequent urination", "Routine diabetes control"],
     pop=["adult", "middle-aged"], stages=["preclinical", "koas"],
     skd=["sistem_diabetes-mellitus-tipe-2", "sistem_hipoglikemia-ringan"],
     obj=["Recognize classic hyperglycemia symptoms", "Order and interpret fasting glucose/HbA1c",
          "Start metformin-based management with lifestyle counseling", "Detect hypoglycemia and adjust therapy"],
     diffs=["Diabetes mellitus tipe 1", "Hiperglikemia hiperosmolar", "Hipoglikemia"],
     variants=[
        dict(sfx="new_uncomplicated", title="Newly detected uncomplicated type 2 diabetes", angle="typical",
             anchor="sistem_diabetes-mellitus-tipe-2", age=52, sex="male", setting="primary care"),
        dict(sfx="uncontrolled_comorb", title="Uncontrolled diabetes with hypertension comorbidity", angle="complicated",
             anchor="sistem_diabetes-mellitus-tipe-2", age=60, sex="female", setting="primary care"),
        dict(sfx="hypo_on_therapy", title="Mild hypoglycemia on glucose-lowering therapy", angle="early",
             anchor="sistem_hipoglikemia-ringan", age=58, sex="male", setting="primary care"),
     ]),
dict(id="fam_gastritis", spec="internal_medicine", tid="Gastritis", ten="Gastritis",
     complaints=["Upper abdominal pain", "Heartburn-like epigastric pain"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_gastritis", "sistem_perdarahan-gastrointestinal"],
     obj=["Elicit dyspepsia red flags", "Link NSAID use to mucosal injury", "Start acid suppression and safety-net"],
     diffs=["Refluks gastroesofagus", "Ulkus peptikum", "Kolesistitis"],
     variants=[
        dict(sfx="acute_nsaid", title="Acute NSAID-related gastritis", angle="typical",
             anchor="sistem_gastritis", age=45, sex="female", setting="primary care"),
        dict(sfx="recurrent", title="Recurrent dyspepsia with lifestyle triggers", angle="chronic",
             anchor="sistem_gastritis", age=38, sex="male", setting="primary care"),
        dict(sfx="alarm_refer", title="Gastritis-like pain with GI-bleed alarm features", angle="complicated",
             anchor="sistem_perdarahan-gastrointestinal", age=62, sex="male", setting="emergency department"),
     ]),
dict(id="fam_gerd", spec="internal_medicine", tid="Refluks Gastroesofagus", ten="Gastroesophageal Reflux",
     complaints=["Burning chest sensation after meals", "Sour taste rising to throat"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_refluks-gastroesofagus", "sistem_sindrom-koroner-akut"],
     obj=["Distinguish reflux from cardiac chest pain", "Apply lifestyle + PPI step-up", "Know when to refer for endoscopy"],
     diffs=["Sindrom koroner akut", "Gastritis", "Angina"],
     variants=[
        dict(sfx="typical", title="Typical reflux with postprandial heartburn", angle="typical",
             anchor="sistem_refluks-gastroesofagus", age=42, sex="female", setting="primary care"),
        dict(sfx="chronic_relapse", title="Chronic relapsing reflux, partial PPI response", angle="chronic",
             anchor="sistem_refluks-gastroesofagus", age=55, sex="male", setting="primary care"),
        dict(sfx="chestpain_ruleout", title="Epigastric burning with cardiac-risk features", angle="complicated",
             anchor="sistem_sindrom-koroner-akut", age=58, sex="male", setting="emergency department"),
     ]),
dict(id="fam_typhoid", spec="internal_medicine", tid="Demam Tifoid", ten="Typhoid Fever",
     complaints=["Prolonged stepwise fever", "Fever with abdominal discomfort"],
     pop=["adult", "adolescent", "endemic-area resident"], stages=["preclinical", "koas"],
     skd=["sistem_demam-tifoid", "sistem_demam-tifoid-dengan-komplikasi"],
     obj=["Recognize prolonged fever pattern", "Order blood culture/Widal interpretation cautiously",
          "Start appropriate antibiotics and detect complications"],
     diffs=["Dengue", "Malaria", "Gastroenteritis"],
     variants=[
        dict(sfx="uncomplicated", title="Uncomplicated typhoid fever", angle="typical",
             anchor="sistem_demam-tifoid", age=24, sex="male", setting="primary care"),
        dict(sfx="prolonged", title="Prolonged fever with relative bradycardia", angle="complicated",
             anchor="sistem_demam-tifoid", age=30, sex="female", setting="primary care"),
        dict(sfx="complicated", title="Typhoid with intestinal-bleed warning signs", angle="severe",
             anchor="sistem_demam-tifoid-dengan-komplikasi", age=28, sex="male", setting="emergency department"),
     ]),
dict(id="fam_gastroenteritis", spec="internal_medicine", tid="Gastroenteritis Akut", ten="Acute Gastroenteritis",
     complaints=["Watery diarrhea and vomiting", "Diarrhea since yesterday"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_gastroenteritis-termasuk-kolera-giardiasis", "sistem_disentri-basiler-amuba", "sistem_keracunan-makanan"],
     obj=["Assess dehydration grade", "Choose ORS vs IV fluids", "Recognize dysentery needing antibiotics"],
     diffs=["Disentri basiler", "Keracunan makanan", "Demam tifoid"],
     variants=[
        dict(sfx="watery_mild", title="Acute watery diarrhea without dehydration", angle="typical",
             anchor="sistem_gastroenteritis-termasuk-kolera-giardiasis", age=29, sex="female", setting="primary care"),
        dict(sfx="moderate_dehyd", title="Gastroenteritis with moderate dehydration", angle="complicated",
             anchor="sistem_gastroenteritis-termasuk-kolera-giardiasis", age=35, sex="male", setting="emergency department"),
        dict(sfx="dysentery", title="Bloody diarrhea (dysentery pattern)", angle="complicated",
             anchor="sistem_disentri-basiler-amuba", age=26, sex="male", setting="primary care"),
     ]),
dict(id="fam_anemia", spec="internal_medicine", tid="Anemia Defisiensi", ten="Deficiency Anemia",
     complaints=["Easily tired and pale", "Fatigue with dizziness on standing"],
     pop=["adult", "woman of reproductive age"], stages=["preclinical", "koas"],
     skd=["sistem_anemia-defisiensi-vitamin-mineral-besi-b12"],
     obj=["Elicit bleeding/nutrition/menstrual history", "Interpret Hb/MCV/ferritin pattern", "Start iron replacement and find the cause"],
     diffs=["Anemia of chronic disease", "Thalassemia trait", "Acute blood loss"],
     variants=[
        dict(sfx="ida_woman", title="Iron deficiency anemia in a young woman", angle="typical",
             anchor="sistem_anemia-defisiensi-vitamin-mineral-besi-b12", age=27, sex="female", setting="primary care"),
        dict(sfx="b12_elderly", title="B12-deficiency pattern with paresthesia", angle="elderly",
             anchor="sistem_anemia-defisiensi-vitamin-mineral-besi-b12", age=66, sex="male", setting="primary care"),
        dict(sfx="severe_sympt", title="Symptomatic anemia needing transfusion triage", angle="severe",
             anchor="sistem_anemia-defisiensi-vitamin-mineral-besi-b12", age=48, sex="female", setting="emergency department"),
     ]),
dict(id="fam_cap", spec="internal_medicine", tid="Pneumonia Komunitas", ten="Community-Acquired Pneumonia",
     complaints=["Cough with fever and breathlessness", "Chest pain when coughing"],
     pop=["adult", "older adult"], stages=["koas"],
     skd=["sistem_community-acquired-pneumonia-cap", "sistem_bronkitis-akut"],
     obj=["Apply severity assessment (RR, SpO2, confusion)", "Choose outpatient vs admit", "Start empiric antibiotics per guidance"],
     diffs=["Bronkitis akut", "TB paru", "Gagal jantung"],
     variants=[
        dict(sfx="moderate_admit", title="CAP with hypoxemia needing admission workup", angle="complicated",
             anchor="sistem_community-acquired-pneumonia-cap", age=64, sex="male", setting="emergency department"),
        dict(sfx="severe", title="Severe CAP with respiratory distress", angle="severe",
             anchor="sistem_community-acquired-pneumonia-cap", age=70, sex="female", setting="emergency department"),
        dict(sfx="vs_bronchitis", title="Acute cough-fever mimicking bronchitis", angle="early",
             anchor="sistem_bronkitis-akut", age=40, sex="female", setting="primary care"),
     ]),
dict(id="fam_tb", spec="internal_medicine", tid="Tuberkulosis Paru", ten="Pulmonary Tuberculosis",
     complaints=["Chronic cough over 2 weeks", "Cough with night sweats and weight loss"],
     pop=["adult", "household contact"], stages=["preclinical", "koas"],
     skd=["sistem_tb-paru-tanpa-komplikasi", "sistem_tb-laten-latent-tuberculosis-infection"],
     obj=["Elicit chronicity + contact history", "Order sputum molecular test and chest X-ray", "Start standard regimen counseling + contact tracing"],
     diffs=["Pneumonia komunitas", "Bronkitis kronik", "Keganasan paru"],
     variants=[
        dict(sfx="new_typical", title="New sputum-positive pulmonary TB", angle="typical",
             anchor="sistem_tb-paru-tanpa-komplikasi", age=34, sex="male", setting="primary care"),
        dict(sfx="dm_comorb", title="TB with diabetes comorbidity", angle="complicated",
             anchor="sistem_tb-paru-tanpa-komplikasi", age=52, sex="female", setting="primary care"),
        dict(sfx="latent_contact", title="Household contact with latent infection", angle="early",
             anchor="sistem_tb-laten-latent-tuberculosis-infection", age=28, sex="female", setting="primary care"),
     ]),
dict(id="fam_asthma", spec="internal_medicine", tid="Asma Bronkial", ten="Bronchial Asthma",
     complaints=["Recurrent wheezing and shortness of breath", "Night-time cough and chest tightness"],
     pop=["adult", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_asma-bronkial"],
     obj=["Elicit trigger + variability history", "Classify control level", "Teach inhaler technique + action plan"],
     diffs=["PPOK", "Gagal jantung", "Alergi saluran napas"],
     variants=[
        dict(sfx="intermittent", title="Intermittent asthma with clear triggers", angle="typical",
             anchor="sistem_asma-bronkial", age=22, sex="female", setting="primary care"),
        dict(sfx="persistent", title="Persistent asthma needing controller step-up", angle="chronic",
             anchor="sistem_asma-bronkial", age=35, sex="male", setting="primary care"),
        dict(sfx="exacerbation", title="Moderate asthma exacerbation", angle="complicated",
             anchor="sistem_asma-bronkial", age=27, sex="female", setting="emergency department"),
     ]),
dict(id="fam_copd", spec="internal_medicine", tid="PPOK", ten="COPD",
     complaints=["Chronic breathlessness on exertion", "Worsening breathlessness with more sputum"],
     pop=["older adult", "smoker"], stages=["koas"],
     skd=["sistem_ppok-stabil", "sistem_ppok-eksaserbasi"],
     obj=["Quantify smoking + exacerbation history", "Distinguish stable vs exacerbation", "Optimize inhalers + refer for rehab assessment"],
     diffs=["Asma bronkial", "Gagal jantung", "Bronkiektasis"],
     variants=[
        dict(sfx="stable", title="Stable COPD on routine control", angle="typical",
             anchor="sistem_ppok-stabil", age=63, sex="male", setting="primary care"),
        dict(sfx="exacerbation", title="COPD exacerbation with purulent sputum", angle="complicated",
             anchor="sistem_ppok-eksaserbasi", age=67, sex="male", setting="emergency department"),
        dict(sfx="severe_hypox", title="Severe exacerbation with hypoxemia", angle="severe",
             anchor="sistem_ppok-eksaserbasi", age=71, sex="female", setting="emergency department"),
     ]),
dict(id="fam_gout", spec="internal_medicine", tid="Artritis Gout", ten="Gout Arthritis",
     complaints=["Sudden very painful swollen big toe", "Recurrent painful joint attacks"],
     pop=["adult", "middle-aged"], stages=["preclinical", "koas"],
     skd=["sistem_artritis-gout", "sistem_hiperurisemia"],
     obj=["Recognize podagra pattern", "Manage acute attack vs long-term urate lowering", "Counsel diet + comorbidity risks"],
     diffs=["Artritis septik", "Osteoarthritis", "Pseudogout"],
     variants=[
        dict(sfx="acute_podagra", title="First acute podagra attack", angle="typical",
             anchor="sistem_artritis-gout", age=47, sex="male", setting="primary care"),
        dict(sfx="recurrent_hyperu", title="Recurrent gout with hyperuricemia", angle="chronic",
             anchor="sistem_hiperurisemia", age=55, sex="male", setting="primary care"),
        dict(sfx="ckd_comorb", title="Gout flare with kidney-function concern", angle="complicated",
             anchor="sistem_artritis-gout", age=64, sex="male", setting="primary care"),
     ]),
dict(id="fam_hf", spec="internal_medicine", tid="Gagal Jantung", ten="Heart Failure",
     complaints=["Breathless when lying flat", "Leg swelling with easy fatigue"],
     pop=["older adult"], stages=["koas"],
     skd=["sistem_gagal-jantung", "sistem_gagal-jantung-akut"],
     obj=["Elicit orthopnea/PND/edema triad", "Order ECG, chest X-ray, BNP/echo pathway", "Start decongestion + referral planning"],
     diffs=["PPOK eksaserbasi", "Pneumonia", "Anemia berat"],
     variants=[
        dict(sfx="chronic_recog", title="Chronic heart-failure pattern for recognition", angle="typical",
             anchor="sistem_gagal-jantung", age=68, sex="female", setting="primary care"),
        dict(sfx="acute_decomp", title="Acute decompensated heart failure", angle="severe",
             anchor="sistem_gagal-jantung-akut", age=72, sex="male", setting="emergency department"),
        dict(sfx="edema_workup", title="New bilateral edema workup", angle="early",
             anchor="sistem_gagal-jantung", age=60, sex="male", setting="primary care"),
     ]),
dict(id="fam_aki", spec="internal_medicine", tid="Gangguan Ginjal Akut", ten="Acute Kidney Injury",
     complaints=["Markedly reduced urination", "Swelling with very little urine after diarrhea"],
     pop=["adult", "older adult"], stages=["koas"],
     skd=["sistem_acute-kidney-injury"],
     obj=["Link volume loss/nephrotoxins to oliguria", "Order creatinine/electrolyte trend", "Resuscitate, stop nephrotoxins, refer timely"],
     diffs=["Dehidrasi tanpa AKI", "Obstruksi urin", "Gagal jantung"],
     variants=[
        dict(sfx="prerenal_dehyd", title="Prerenal AKI after volume loss", angle="typical",
             anchor="sistem_acute-kidney-injury", age=58, sex="male", setting="emergency department"),
        dict(sfx="hyperkalemia", title="AKI with hyperkalemia warning signs", angle="severe",
             anchor="sistem_acute-kidney-injury", age=66, sex="female", setting="emergency department"),
     ]),
dict(id="fam_hepatitis", spec="internal_medicine", tid="Hepatitis A", ten="Hepatitis A",
     complaints=["Yellow eyes with nausea", "Dark urine and upper abdominal ache"],
     pop=["adult", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_hepatitis-a-37"],
     obj=["Elicit exposure + prodrome history", "Interpret ALT/bilirubin pattern", "Give supportive care + hygiene counseling"],
     diffs=["Kolesistitis", "Leptospirosis", "Demam tifoid"],
     variants=[
        dict(sfx="typical", title="Typical acute hepatitis A", angle="typical",
             anchor="sistem_hepatitis-a-37", age=21, sex="male", setting="primary care"),
        dict(sfx="cholestatic", title="Prolonged cholestatic course", angle="complicated",
             anchor="sistem_hepatitis-a-37", age=33, sex="female", setting="primary care"),
     ]),
dict(id="fam_thyroid", spec="internal_medicine", tid="Gangguan Tiroid Rujuk Balik", ten="Thyroid Disorders (Shared Care)",
     complaints=["Trembling with weight loss and palpitations", "Neck swelling routine control"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_rujuk-balik-hipertiroid", "sistem_rujuk-balik-goiter", "sistem_tirotoksikosis"],
     obj=["Elicit thyrotoxic symptoms", "Interpret TSH/FT4 pattern", "Manage shared-care refills + detect storm warning"],
     diffs=["Gangguan ansietas", "Anemia", "Fibrilasi atrial"],
     variants=[
        dict(sfx="hyper_shared", title="Hyperthyroidism on shared-care refill", angle="chronic",
             anchor="sistem_rujuk-balik-hipertiroid", age=39, sex="female", setting="primary care"),
        dict(sfx="goiter_euthy", title="Euthyroid goiter routine review", angle="typical",
             anchor="sistem_rujuk-balik-goiter", age=45, sex="female", setting="primary care"),
        dict(sfx="storm_warning", title="Uncontrolled thyrotoxicosis with storm warning", angle="severe",
             anchor="sistem_tirotoksikosis", age=36, sex="female", setting="emergency department"),
     ]),
dict(id="fam_malaria", spec="internal_medicine", tid="Malaria", ten="Malaria",
     complaints=["Intermittent high fever with chills", "Fever with heavy sweating cycles"],
     pop=["adult", "endemic-area resident", "traveler"], stages=["preclinical", "koas"],
     skd=["sistem_malaria-tanpa-komplikasi"],
     obj=["Elicit travel/endemic exposure", "Order thick/thin smear or RDT", "Start antimalarials + counsel prevention"],
     diffs=["Demam dengue", "Demam tifoid", "Leptospirosis"],
     variants=[
        dict(sfx="uncomplicated", title="Uncomplicated malaria with classic paroxysm", angle="typical",
             anchor="sistem_malaria-tanpa-komplikasi", age=29, sex="male", setting="primary care"),
        dict(sfx="traveler", title="Imported malaria in a returning traveler", angle="early",
             anchor="sistem_malaria-tanpa-komplikasi", age=33, sex="female", setting="primary care"),
     ]),
dict(id="fam_anaphylaxis", spec="internal_medicine", tid="Reaksi Anafilaktik", ten="Anaphylaxis",
     complaints=["Sudden whole-body itching with lip swelling", "Sudden breathlessness after a drug/insect sting"],
     pop=["adult"], stages=["koas"], cross=["emergency"],
     skd=["sistem_reaksi-anafilaktik", "sistem_angioedema"],
     obj=["Recognize airway/breathing/circulation compromise", "Give IM adrenaline without delay", "Plan observation + action plan"],
     diffs=["Urtikaria akut", "Angioedema", "Asma eksaserbasi"],
     variants=[
        dict(sfx="typical_food", title="Anaphylaxis after food exposure", angle="severe",
             anchor="sistem_reaksi-anafilaktik", age=26, sex="female", setting="emergency department"),
        dict(sfx="drug_biphasic", title="Drug-triggered reaction needing observation", angle="complicated",
             anchor="sistem_reaksi-anafilaktik", age=44, sex="male", setting="emergency department"),
        dict(sfx="angioedema", title="Angioedema with airway-watch features", angle="complicated",
             anchor="sistem_angioedema", age=38, sex="female", setting="emergency department"),
     ]),
# ── EMERGENCY (13) ────────────────────────────────────────────────────
dict(id="fam_acs", spec="emergency", tid="Sindrom Koroner Akut", ten="Acute Coronary Syndrome",
     complaints=["Heavy central chest pain", "Chest pressure spreading to the arm"],
     pop=["middle-aged", "older adult"], stages=["koas"],
     skd=["sistem_sindrom-koroner-akut"],
     obj=["Elicit onset/character/radiation + risk factors", "Order ECG + troponin pathway", "Give loading antiplatelets + urgent referral"],
     diffs=["GERD", "Pneumotoraks", "Gagal jantung akut"],
     variants=[
        dict(sfx="typical_stemi", title="Typical acute chest pain (STEMI pattern)", angle="severe",
             anchor="sistem_sindrom-koroner-akut", age=57, sex="male", setting="emergency department"),
        dict(sfx="atypical_elderly", title="Atypical equivalents in an older diabetic", angle="complicated",
             anchor="sistem_sindrom-koroner-akut", age=71, sex="female", setting="emergency department"),
        dict(sfx="unstable", title="Rest angina with hemodynamic concern", angle="severe",
             anchor="sistem_sindrom-koroner-akut", age=63, sex="male", setting="emergency department"),
     ]),
dict(id="fam_stroke", spec="emergency", tid="Stroke Iskemik Akut", ten="Acute Ischemic Stroke",
     complaints=["Sudden one-sided weakness", "Sudden slurred speech with face droop"],
     pop=["older adult"], stages=["koas"], cross=["neurology"],
     skd=["sistem_infark-serebral", "sistem_tia"],
     obj=["Establish last-known-well time", "Apply FAST + glucose check", "Activate stroke referral pathway fast"],
     diffs=["TIA", "Hipoglikemia", "Kejang Todd paresis"],
     variants=[
        dict(sfx="acute_window", title="Focal deficit within reperfusion window", angle="severe",
             anchor="sistem_infark-serebral", age=66, sex="male", setting="emergency department"),
        dict(sfx="delayed", title="Delayed presentation beyond the window", angle="complicated",
             anchor="sistem_infark-serebral", age=74, sex="female", setting="emergency department"),
        dict(sfx="tia_warning", title="Transient deficit (TIA warning event)", angle="complicated",
             anchor="sistem_tia", age=61, sex="male", setting="emergency department"),
     ]),
dict(id="fam_shock", spec="emergency", tid="Syok", ten="Shock",
     complaints=["Sudden cold sweats with weakness", "Faint with fast heartbeat"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_syok-septik-kardiogenik-neurogenik"],
     obj=["Recognize poor perfusion triad", "Give fluids + vasopressor-access thinking", "Find the source and refer to higher care"],
     diffs=["Dehidrasi berat", "Anemia akut", "Sinkop vasovagal"],
     variants=[
        dict(sfx="septic", title="Septic shock from infection source", angle="severe",
             anchor="sistem_syok-septik-kardiogenik-neurogenik", age=59, sex="male", setting="emergency department"),
        dict(sfx="hypovolemic", title="Hypovolemic shock after fluid loss", angle="severe",
             anchor="sistem_syok-septik-kardiogenik-neurogenik", age=34, sex="female", setting="emergency department"),
        dict(sfx="cardiogenic", title="Cardiogenic pattern with lung crackles", angle="severe",
             anchor="sistem_syok-septik-kardiogenik-neurogenik", age=68, sex="male", setting="emergency department"),
     ]),
dict(id="fam_dka", spec="emergency", tid="Ketoasidosis Diabetikum", ten="Diabetic Ketoacidosis",
     complaints=["Rapid breathing with fruity-smelling breath", "Vomiting with deep fast breathing in diabetes"],
     pop=["adult", "young adult"], stages=["koas"],
     skd=["sistem_ketoasidosis-diabetikum", "sistem_hiperglikemia-hiperosmolar-non-ketotik"],
     obj=["Link polyuria + Kussmaul + ketones", "Order glucose/ketone/ABG/electrolytes", "Start fluids + insulin protocol + find precipitant"],
     diffs=["Hiperglikemia hiperosmolar", "Asidosis laktat", "Gastroenteritis"],
     variants=[
        dict(sfx="typical", title="Moderate DKA with infectious precipitant", angle="severe",
             anchor="sistem_ketoasidosis-diabetikum", age=31, sex="female", setting="emergency department"),
        dict(sfx="severe", title="Severe DKA with altered consciousness", angle="severe",
             anchor="sistem_ketoasidosis-diabetikum", age=24, sex="male", setting="emergency department"),
        dict(sfx="hhs_elderly", title="Hyperosmolar pattern in an older diabetic", angle="complicated",
             anchor="sistem_hiperglikemia-hiperosmolar-non-ketotik", age=69, sex="male", setting="emergency department"),
     ]),
dict(id="fam_hypoglycemia", spec="emergency", tid="Hipoglikemia Berat", ten="Severe Hypoglycemia",
     complaints=["Sudden cold sweat with confusion", "Found drowsy and sweaty"],
     pop=["adult", "diabetic on therapy"], stages=["koas"],
     skd=["sistem_hipoglikemia-berat"],
     obj=["Check glucose immediately", "Give fast glucose + glucagon pathway", "Review drug/dose/meal cause"],
     diffs=["Stroke", "Kejang", "Sinkop"],
     variants=[
        dict(sfx="typical", title="Severe hypoglycemia on insulin", angle="severe",
             anchor="sistem_hipoglikemia-berat", age=55, sex="male", setting="emergency department"),
        dict(sfx="sulfonylurea", title="Prolonged hypoglycemia on sulfonylurea", angle="complicated",
             anchor="sistem_hipoglikemia-berat", age=62, sex="female", setting="emergency department"),
     ]),
dict(id="fam_seizure_emg", spec="emergency", tid="Kejang dan Status Epileptikus", ten="Seizure and Status Epilepticus",
     complaints=["Witnessed shaking fit", "Repeated fits without waking up"],
     pop=["adult"], stages=["koas"], cross=["neurology"],
     skd=["sistem_status-epilepticus", "sistem_epilepsi"],
     obj=["Secure airway + time the fit", "Give first-line benzodiazepine pathway", "Arrange neuro referral + safety counseling"],
     diffs=["Sinkop", "Hipoglikemia", "Gangguan psikogenik"],
     variants=[
        dict(sfx="first_fit", title="First unprovoked seizure presentation", angle="complicated",
             anchor="sistem_epilepsi", age=26, sex="male", setting="emergency department"),
        dict(sfx="status", title="Prolonged seizure activity (status pattern)", angle="severe",
             anchor="sistem_status-epilepticus", age=33, sex="female", setting="emergency department"),
     ]),
dict(id="fam_poisoning", spec="emergency", tid="Keracunan", ten="Poisoning",
     complaints=["Vomiting after pesticide exposure", "Collapse after unknown ingestion"],
     pop=["adult", "farmer"], stages=["koas"],
     skd=["sistem_keracunan-insektisida", "sistem_keracunan-racun-alam"],
     obj=["Identify agent + time + amount", "Protect airway + decontamination timing", "Give antidote-pathway + refer to higher care"],
     diffs=["Gastroenteritis", "Keracunan makanan", "Stroke"],
     variants=[
        dict(sfx="organophos", title="Insecticide exposure with cholinergic signs", angle="severe",
             anchor="sistem_keracunan-insektisida", age=41, sex="male", setting="emergency department"),
        dict(sfx="natural_toxin", title="Natural-toxin ingestion with GI + neuro signs", angle="complicated",
             anchor="sistem_keracunan-racun-alam", age=29, sex="female", setting="emergency department"),
     ]),
dict(id="fam_gi_bleed", spec="emergency", tid="Perdarahan Gastrointestinal", ten="Gastrointestinal Bleeding",
     complaints=["Vomiting blood", "Black tarry stools with dizziness"],
     pop=["adult", "older adult"], stages=["koas"],
     skd=["sistem_perdarahan-gastrointestinal"],
     obj=["Quantify loss + vitals + NSAID/liver history", "Resuscitate + urgent endoscopy pathway", "Refer to higher care early"],
     diffs=["Epistaksis tertelan", "Hemoroid", "Gastritis tanpa perdarahan"],
     variants=[
        dict(sfx="upper_stable", title="Upper GI bleed, currently stable", angle="complicated",
             anchor="sistem_perdarahan-gastrointestinal", age=54, sex="male", setting="emergency department"),
        dict(sfx="unstable", title="Massive bleed with shock signs", angle="severe",
             anchor="sistem_perdarahan-gastrointestinal", age=66, sex="male", setting="emergency department"),
     ]),
dict(id="fam_status_asthma", spec="emergency", tid="Status Asmatikus", ten="Status Asthmaticus",
     complaints=["Severe breathlessness not relieved by inhaler", "Can only speak a few words"],
     pop=["adult", "adolescent"], stages=["koas"],
     skd=["sistem_status-asmatikus"],
     obj=["Grade severity (speech, SpO2, silent chest)", "Give oxygen + nebulized/systemic therapy", "Escalate to ICU pathway when failing"],
     diffs=["Anafilaksis", "PPOK eksaserbasi", "Gagal jantung akut"],
     variants=[
        dict(sfx="severe", title="Severe attack refractory to reliever", angle="severe",
             anchor="sistem_status-asmatikus", age=24, sex="female", setting="emergency department"),
        dict(sfx="nearfatal", title="Near-fatal pattern with drowsiness", angle="severe",
             anchor="sistem_status-asmatikus", age=38, sex="male", setting="emergency department"),
     ]),
dict(id="fam_trauma", spec="emergency", tid="Trauma Ekstremitas dan Luka", ten="Limb Trauma and Wounds",
     complaints=["Swollen deformed arm after a fall", "Deep cut with heavy bleeding"],
     pop=["adult", "young adult"], stages=["koas"], cross=["surgery"],
     skd=["sistem_fraktur-terbuka-tertutup", "sistem_vulnus-laceratum-punctum"],
     obj=["Check neurovascular status distal to injury", "Control bleeding + tetanus + analgesia", "Splint and refer for definitive fixation"],
     diffs=["Sprain", "Dislokasi", "Kontusio tanpa fraktur"],
     variants=[
        dict(sfx="closed_fx", title="Closed forearm fracture after fall", angle="complicated",
             anchor="sistem_fraktur-terbuka-tertutup", age=27, sex="male", setting="emergency department"),
        dict(sfx="open_wound", title="Open laceration with bleeding control need", angle="complicated",
             anchor="sistem_vulnus-laceratum-punctum", age=32, sex="male", setting="emergency department"),
        dict(sfx="neurovasc", title="Fracture with neurovascular concern", angle="severe",
             anchor="sistem_fraktur-terbuka-tertutup", age=45, sex="female", setting="emergency department"),
     ]),
dict(id="fam_burns", spec="emergency", tid="Luka Bakar", ten="Burns",
     complaints=["Hot-water scald on the arm", "Widespread burn after stove accident"],
     pop=["adult", "child"], stages=["koas"], cross=["surgery"],
     skd=["sistem_luka-bakar-derajat-1", "sistem_luka-bakar-derajat-2-10", "sistem_luka-bakar-derajat-3"],
     obj=["Estimate depth + extent", "Cool, cover, fluids for major burns", "Refer major/deep burns early"],
     diffs=["Selulitis", "Dermatitis kontak", "Eritema non-luka bakar"],
     variants=[
        dict(sfx="first_degree", title="Minor first-degree scald", angle="typical",
             anchor="sistem_luka-bakar-derajat-1", age=30, sex="female", setting="primary care"),
        dict(sfx="partial_major", title="Partial-thickness burn over 10 percent", angle="severe",
             anchor="sistem_luka-bakar-derajat-2-10", age=25, sex="male", setting="emergency department"),
        dict(sfx="full_thickness", title="Deep full-thickness burn patch", angle="severe",
             anchor="sistem_luka-bakar-derajat-3", age=40, sex="male", setting="emergency department"),
     ]),
dict(id="fam_coma", spec="emergency", tid="Penurunan Kesadaran", ten="Decreased Consciousness",
     complaints=["Found unconscious by family", "Increasingly drowsy since morning"],
     pop=["adult", "older adult"], stages=["koas"], cross=["neurology"],
     skd=["sistem_koma", "sistem_ensefalopati"],
     obj=["Run ABCDE + glucose first", "Elicit toxin/metabolic/infection clues", "Protect airway + urgent referral"],
     diffs=["Hipoglikemia", "Stroke", "Intoksikasi"],
     variants=[
        dict(sfx="metabolic", title="Drowsiness with metabolic cause", angle="severe",
             anchor="sistem_ensefalopati", age=62, sex="male", setting="emergency department"),
        dict(sfx="deep_coma", title="Deep coma with airway priority", angle="severe",
             anchor="sistem_koma", age=55, sex="female", setting="emergency department"),
     ]),
dict(id="fam_htn_crisis", spec="emergency", tid="Krisis Hipertensi", ten="Hypertensive Crisis",
     complaints=["Very high blood pressure with headache", "High pressure with chest discomfort"],
     pop=["middle-aged", "older adult"], stages=["koas"], cross=["internal_medicine"],
     skd=["sistem_krisis-hipertensi", "sistem_ensefalopati-hipertensi"],
     obj=["Distinguish urgency vs emergency (organ damage)", "Lower pressure in a controlled pathway", "Refer emergencies immediately"],
     diffs=["Hipertensi derajat 2 stabil", "Stroke", "Sindrom koroner akut"],
     variants=[
        dict(sfx="urgency", title="Severe elevation without organ damage", angle="complicated",
             anchor="sistem_krisis-hipertensi", age=59, sex="female", setting="emergency department"),
        dict(sfx="emergency_neuro", title="Severe elevation with neuro deficits", angle="severe",
             anchor="sistem_ensefalopati-hipertensi", age=64, sex="male", setting="emergency department"),
     ]),
]
