"""Phase 4 continuation — specs part 3 (Neuro, Psych, Surgery, MSK, Derm, ENT, Ophthal)."""
from __future__ import annotations

FAMILIES3: list[dict] = [
# ── NEUROLOGY (8) ───────────────────────────────────────────────────
dict(id="fam_tension_headache", spec="neurology", tid="Sakit Kepala Tegang", ten="Tension Headache",
     complaints=["Pressing headache on both sides", "Tight band-like headache"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_tension-headache", "sistem_migren-tanpa-aura"],
     obj=["Elicit headache red flags (SNOOP)", "Distinguish tension vs migraine", "Start analgesia + trigger management"],
     diffs=["Migren", "Cluster headache", "Hipertensi"],
     variants=[
        dict(sfx="episodic", title="Episodic tension headache", angle="typical",
             anchor="sistem_tension-headache", age=34, sex="female", setting="primary care"),
        dict(sfx="chronic_stress", title="Frequent headache with stress trigger", angle="chronic",
             anchor="sistem_tension-headache", age=41, sex="male", setting="primary care"),
        dict(sfx="vs_migraine", title="Unilateral throbbing headache with nausea", angle="typical",
             anchor="sistem_migren-tanpa-aura", age=28, sex="female", setting="primary care"),
     ]),
dict(id="fam_migraine", spec="neurology", tid="Migren", ten="Migraine",
     complaints=["One-sided pounding headache with nausea", "Headache worsened by light and movement"],
     pop=["adult", "young woman"], stages=["preclinical", "koas"],
     skd=["sistem_migren-tanpa-aura"],
     obj=["Apply migraine criteria", "Start acute + consider preventive therapy", "Exclude secondary causes"],
     diffs=["Tension headache", "Cluster headache", "Sinusitis"],
     variants=[
        dict(sfx="without_aura", title="Migraine without aura", angle="typical",
             anchor="sistem_migren-tanpa-aura", age=27, sex="female", setting="primary care"),
        dict(sfx="frequent", title="High-frequency migraine needing prevention", angle="chronic",
             anchor="sistem_migren-tanpa-aura", age=33, sex="female", setting="primary care"),
     ]),
dict(id="fam_bells", spec="neurology", tid="Bell Palsy", ten="Bell's Palsy",
     complaints=["One side of the face suddenly droopy", "Cannot close one eye, mouth pulled aside"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_bell-s-palsy", "sistem_infark-serebral"],
     obj=["Distinguish peripheral vs central facial weakness", "Start steroids + eye protection early", "Refer stroke mimics fast"],
     diffs=["Stroke", "Otitis media complications", "Tumor"],
     variants=[
        dict(sfx="typical", title="Typical peripheral facial palsy", angle="typical",
             anchor="sistem_bell-s-palsy", age=38, sex="male", setting="primary care"),
        dict(sfx="stroke_mimic", title="Facial droop with limb weakness (stroke rule-out)", angle="severe",
             anchor="sistem_infark-serebral", age=65, sex="female", setting="emergency department"),
     ]),
dict(id="fam_meningitis", spec="neurology", tid="Meningitis", ten="Meningitis",
     complaints=["High fever with severe headache and stiff neck", "Fever with rash that does not fade"],
     pop=["adult", "adolescent"], stages=["koas"],
     skd=["sistem_meningitis"],
     obj=["Elicit Kernig/Brudzinski/photophobia", "Start empiric antibiotics + lumbar puncture pathway", "Isolate + refer urgently"],
     diffs=["Ensefalitis", "Migren", "Demam tifoid"],
     variants=[
        dict(sfx="bacterial", title="Bacterial-pattern meningitis", angle="severe",
             anchor="sistem_meningitis", age=22, sex="male", setting="emergency department"),
        dict(sfx="early_subtle", title="Early meningitis with subtle neck stiffness", angle="complicated",
             anchor="sistem_meningitis", age=29, sex="female", setting="emergency department"),
     ]),
dict(id="fam_vertigo", spec="neurology", tid="Vertigo Posinal", ten="Positional Vertigo",
     complaints=["Spinning dizziness when turning in bed", "Brief spinning when looking up"],
     pop=["adult", "older adult"], stages=["preclinical", "koas"], cross=["ent"],
     skd=["sistem_vertigo-benign-paroxysmal-positional-vertigo", "sistem_neuritis-vestibularis"],
     obj=["Apply Dix-Hallpike thinking", "Distinguish BPPV vs vestibular neuritis vs stroke", "Teach repositioning + safety"],
     diffs=["Neuritis vestibularis", "Stroke posterior", "Meniere"],
     variants=[
        dict(sfx="bppv", title="Posterior-canal BPPV", angle="typical",
             anchor="sistem_vertigo-benign-paroxysmal-positional-vertigo", age=52, sex="female", setting="primary care"),
        dict(sfx="neuritis", title="Persistent vertigo with nausea (neuritis pattern)", angle="complicated",
             anchor="sistem_neuritis-vestibularis", age=45, sex="male", setting="primary care"),
     ]),
dict(id="fam_carpal", spec="neurology", tid="Sindrom Terowongan Karpal", ten="Carpal Tunnel Syndrome",
     complaints=["Numb tingling thumb and fingers at night", "Hand weakness dropping objects"],
     pop=["adult", "woman"], stages=["preclinical", "koas"],
     skd=["sistem_carpal-tunnel-syndrome"],
     obj=["Elicit nocturnal median-nerve pattern", "Apply Phalen/Tinel + NCS pathway", "Splint/activity + refer for injection/surgery assessment"],
     diffs=["Neuropati servikal", "Neuropati diabetes", "Artritis"],
     variants=[
        dict(sfx="mild", title="Mild nocturnal median symptoms", angle="typical",
             anchor="sistem_carpal-tunnel-syndrome", age=42, sex="female", setting="primary care"),
        dict(sfx="severe_motor", title="CTS with thenar wasting", angle="complicated",
             anchor="sistem_carpal-tunnel-syndrome", age=55, sex="female", setting="primary care"),
     ]),
dict(id="fam_diab_neuro", spec="neurology", tid="Neuropati Diabetes", ten="Diabetic Neuropathy",
     complaints=["Burning numb feet like socks", "Feet feel dead with prickling"],
     pop=["adult", "diabetic"], stages=["koas"], cross=["internal_medicine"],
     skd=["sistem_neuropati-diabetes-ringan", "sistem_ulkus-gangrenosa"],
     obj=["Map stocking distribution + foot exam", "Optimize glycemia + pain pathway", "Prevent foot ulceration"],
     diffs=["Neuropati jeratan", "Defisiensi B12", "Gangguan vaskular"],
     variants=[
        dict(sfx="sensory", title="Distal symmetric sensory neuropathy", angle="typical",
             anchor="sistem_neuropati-diabetes-ringan", age=58, sex="male", setting="primary care"),
        dict(sfx="foot_risk", title="Neuropathy with high-risk foot findings", angle="complicated",
             anchor="sistem_ulkus-gangrenosa", age=63, sex="female", setting="primary care"),
     ]),
dict(id="fam_headache_redflag", spec="neurology", tid="Sakit Kepala Tanda Bahaya", ten="Headache Red Flags",
     complaints=["Worst headache of my life", "Thunderclap headache with vomiting"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_perdarahan-subarachnoid", "sistem_cluster-headache"],
     obj=["Recognize thunderclap pattern", "Order CT/LP pathway + urgent referral", "Never miss subarachnoid bleed"],
     diffs=["Migren", "Tension headache", "Meningitis"],
     variants=[
        dict(sfx="sah", title="Thunderclap headache (SAH rule-out)", angle="severe",
             anchor="sistem_perdarahan-subarachnoid", age=48, sex="female", setting="emergency department"),
        dict(sfx="cluster", title="Severe unilateral headache with tearing eye", angle="complicated",
             anchor="sistem_cluster-headache", age=35, sex="male", setting="primary care"),
     ]),
# ── PSYCHIATRY (9) ──────────────────────────────────────────────────
dict(id="fam_depression", spec="psychiatry", tid="Depresi Ringan-Sedang", ten="Mild-Moderate Depression",
     complaints=["Feeling empty for weeks", "Lost interest in everything"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_gangguan-depresi-ringan-sedang" if False else "psikiatri_gangguan-depresi-ringan-sedang",
          "psikiatri_gangguan-depresi-berat"],
     obj=["Elicit mood/anhedonia/sleep/appetite pattern", "Screen suicide risk every time", "Start counseling + SSRI pathway + follow-up"],
     diffs=["Gangguan penyesuaian", "Hipotiroid", "Anemia"],
     variants=[
        dict(sfx="mild", title="Mild depression with preserved function", angle="typical",
             anchor="psikiatri_gangguan-depresi-ringan-sedang", age=29, sex="female", setting="primary care"),
        dict(sfx="moderate_somatic", title="Moderate depression with somatic complaints", angle="complicated",
             anchor="psikiatri_gangguan-depresi-ringan-sedang", age=41, sex="male", setting="primary care"),
        dict(sfx="severe_refer", title="Severe depression needing urgent referral", angle="severe",
             anchor="psikiatri_gangguan-depresi-berat", age=35, sex="female", setting="emergency department"),
     ]),
dict(id="fam_anxiety", spec="psychiatry", tid="Kecemasan Ringan", ten="Mild Anxiety",
     complaints=["Constant worrying I cannot control", "Heart racing with worry"],
     pop=["adult", "young adult"], stages=["preclinical", "koas"],
     skd=["psikiatri_gangguan-kecemasan-ringan", "psikiatri_gangguan-panik"],
     obj=["Distinguish anxiety from cardiac/thyroid mimics", "Teach breathing + thought-record basics", "Know SSRI/referral thresholds"],
     diffs=["Hipertiroid", "Gangguan panik", "Depresi"],
     variants=[
        dict(sfx="gad_mild", title="Mild generalized worry pattern", angle="typical",
             anchor="psikiatri_gangguan-kecemasan-ringan", age=26, sex="female", setting="primary care"),
        dict(sfx="panic_attacks", title="Recurrent panic attacks with ER visits", angle="complicated",
             anchor="psikiatri_gangguan-panik", age=31, sex="male", setting="emergency department"),
     ]),
dict(id="fam_insomnia", spec="psychiatry", tid="Insomnia", ten="Insomnia",
     complaints=["Cannot fall asleep for months", "Wake up many times at night"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["psikiatri_insomnia", "psikiatri_sleep-disorder-ringan"],
     obj=["Map sleep hygiene + screen apnea/mood/substances", "Deliver CBT-I basics before pills", "Limit hypnotics safely"],
     diffs=["Apnea tidur", "Depresi", "Hipertiroid"],
     variants=[
        dict(sfx="primary", title="Primary insomnia with poor habits", angle="typical",
             anchor="psikiatri_insomnia", age=38, sex="female", setting="primary care"),
        dict(sfx="comorbid_mood", title="Insomnia with low-mood features", angle="complicated",
             anchor="psikiatri_sleep-disorder-ringan", age=46, sex="male", setting="primary care"),
     ]),
dict(id="fam_psychosis", spec="psychiatry", tid="Psikosis", ten="Psychosis",
     complaints=["Family says patient talks to unseen voices", "Hearing voices commenting on actions"],
     pop=["young adult"], stages=["koas"],
     skd=["psikiatri_gangguan-psikotik", "psikiatri_skizofrenia"],
     obj=["Elicit positive/negative/disorganization features", "Exclude substances/medical causes", "Arrange safe urgent psychiatric referral"],
     diffs=["Skizofrenia", "Gangguan bipolar", "Intoksikasi zat"],
     variants=[
        dict(sfx="first_episode", title="First-episode psychosis presentation", angle="severe",
             anchor="psikiatri_gangguan-psikotik", age=23, sex="male", setting="emergency department"),
        dict(sfx="schizophrenia", title="Chronic schizophrenia with relapse", angle="complicated",
             anchor="psikiatri_skizofrenia", age=31, sex="female", setting="primary care"),
     ]),
dict(id="fam_suicide", spec="psychiatry", tid="Risiko Bunuh Diri", ten="Suicide Risk",
     complaints=["Wishing to disappear", "Family worried about self-harm talk"],
     pop=["adolescent", "adult"], stages=["koas"],
     skd=["psikiatri_ide-percobaan-bunuh-diri", "psikiatri_self-harm-behavior"],
     obj=["Ask directly about intent/plan/means", "Remove means + safety plan", "Escalate to emergency psychiatric care"],
     diffs=["Depresi berat", "Gangguan penyesuaian", "Kepribadian ambang"],
     variants=[
        dict(sfx="ideation", title="Suicidal ideation without a plan", angle="severe",
             anchor="psikiatri_ide-percobaan-bunuh-diri", age=21, sex="female", setting="emergency department"),
        dict(sfx="selfharm", title="Recent self-harm behavior", angle="severe",
             anchor="psikiatri_self-harm-behavior", age=19, sex="female", setting="emergency department"),
     ]),
dict(id="fam_alcohol", spec="psychiatry", tid="Alkohol dan Zat", ten="Alcohol and Substances",
     complaints=["Shaking when not drinking", "Family wants help to stop drinking"],
     pop=["adult"], stages=["koas"],
     skd=["psikiatri_alcohol-withdrawal-syndrome", "psikiatri_intoksikasi-zat-psikoaktif", "psikiatri_ketergantungan-nikotin"],
     obj=["Quantify use + withdrawal signs", "Manage withdrawal safely + refer", "Deliver brief cessation counseling"],
     diffs=["Ansietas", "Delirium", "Kejang"],
     variants=[
        dict(sfx="withdrawal", title="Alcohol withdrawal with tremor", angle="severe",
             anchor="psikiatri_alcohol-withdrawal-syndrome", age=44, sex="male", setting="emergency department"),
        dict(sfx="intoxication", title="Acute substance intoxication", angle="complicated",
             anchor="psikiatri_intoksikasi-zat-psikoaktif", age=27, sex="male", setting="emergency department"),
        dict(sfx="nicotine", title="Nicotine dependence seeking to quit", angle="typical",
             anchor="psikiatri_ketergantungan-nikotin", age=36, sex="male", setting="primary care"),
     ]),
dict(id="fam_ptsd", spec="psychiatry", tid="Trauma dan Stres", ten="Trauma and Stress",
     complaints=["Nightmares after an accident", "Cannot stop reliving a frightening event"],
     pop=["adult"], stages=["koas"],
     skd=["psikiatri_post-traumatic-stress-disorder-ptsd", "psikiatri_acute-stress-disorder", "psikiatri_gangguan-penyesuaian"],
     obj=["Elicit re-experiencing/avoidance/arousal", "Give grounding + trauma-focused referral", "Screen function + suicide risk"],
     diffs=["Gangguan penyesuaian", "Depresi", "Gangguan panik"],
     variants=[
        dict(sfx="ptsd", title="PTSD after a road accident", angle="complicated",
             anchor="psikiatri_post-traumatic-stress-disorder-ptsd", age=30, sex="female", setting="primary care"),
        dict(sfx="acute_stress", title="Acute stress reaction days after event", angle="typical",
             anchor="psikiatri_acute-stress-disorder", age=26, sex="male", setting="primary care"),
        dict(sfx="adjustment", title="Adjustment difficulty after life change", angle="typical",
             anchor="psikiatri_gangguan-penyesuaian", age=34, sex="female", setting="primary care"),
     ]),
dict(id="fam_ocd", spec="psychiatry", tid="OCD Ringan", ten="Mild OCD",
     complaints=["Must wash hands many times", "Intrusive thoughts with rituals"],
     pop=["young adult"], stages=["koas"],
     skd=["psikiatri_obsessive-compulsive-disorder-ocd-ringan", "psikiatri_obsessive-compulsive-disorder-ocd-berat"],
     obj=["Map obsessions vs compulsions + time cost", "Start ERP basics + SSRI pathway", "Refer severe/psychotic-feature cases"],
     diffs=["Gangguan ansietas", "Depresi", "Psikosis"],
     variants=[
        dict(sfx="mild_washing", title="Mild contamination-washing pattern", angle="typical",
             anchor="psikiatri_obsessive-compulsive-disorder-ocd-ringan", age=24, sex="female", setting="primary care"),
        dict(sfx="severe_time", title="Severe time-consuming rituals", angle="severe",
             anchor="psikiatri_obsessive-compulsive-disorder-ocd-berat", age=28, sex="male", setting="primary care"),
     ]),
dict(id="fam_somatic", spec="psychiatry", tid="Keluhan Somatik", ten="Somatic Complaints",
     complaints=["Many body pains with normal tests", "Worried about serious disease despite reassurance"],
     pop=["adult"], stages=["koas"],
     skd=["psikiatri_gangguan-somatisasi", "psikiatri_phobia-spesifik"],
     obj=["Validate while avoiding over-testing", "Set regular review + function goals", "Coordinate single-GP care"],
     diffs=["Depresi", "Gangguan ansietas", "Penyakit organik"],
     variants=[
        dict(sfx="somatization", title="Multiple somatic complaints pattern", angle="typical",
             anchor="psikiatri_gangguan-somatisasi", age=45, sex="female", setting="primary care"),
        dict(sfx="health_worry", title="Focused health worry after normal workup", angle="typical",
             anchor="psikiatri_phobia-spesifik", age=33, sex="male", setting="primary care"),
     ]),
# ── SURGERY (10) ────────────────────────────────────────────────────
dict(id="fam_appendicitis", spec="surgery", tid="Apendisitis Akut", ten="Acute Appendicitis",
     complaints=["Pain moved to lower right belly", "Right lower abdominal pain with fever"],
     pop=["young adult", "adolescent"], stages=["koas"],
     skd=["sistem_apendisitis-akut", "sistem_abses-apendiks"],
     obj=["Elicit migration + McBurney + Rovsing", "Order Alvarado/USG pathway", "Keep NPO + refer for surgery"],
     diffs=["Kehamilan ektopik", "Gastroenteritis", "Infeksi saluran kemih"],
     variants=[
        dict(sfx="typical", title="Classic migratory appendicitis", angle="complicated",
             anchor="sistem_apendisitis-akut", age=21, sex="male", setting="emergency department"),
        dict(sfx="atypical_woman", title="Atypical pain in a young woman (ectopic rule-out)", angle="complicated",
             anchor="sistem_apendisitis-akut", age=24, sex="female", setting="emergency department"),
        dict(sfx="mass_abscess", title="Delayed mass (appendiceal phlegmon pattern)", angle="severe",
             anchor="sistem_abses-apendiks", age=30, sex="male", setting="emergency department"),
     ]),
dict(id="fam_hernia", spec="surgery", tid="Hernia", ten="Hernia",
     complaints=["Lump in the groin when straining", "Painful groin lump that will not go back"],
     pop=["adult", "older adult"], stages=["preclinical", "koas"],
     skd=["sistem_hernia-strangulata-inkarserata"],
     obj=["Test reducibility + cough impulse", "Distinguish simple vs strangulated", "Refer strangulation immediately"],
     diffs=["Limfadenitis", "Hidrokel", "Abses"],
     variants=[
        dict(sfx="reducible", title="Reducible inguinal hernia", angle="typical",
             anchor="sistem_hernia-strangulata-inkarserata", age=52, sex="male", setting="primary care"),
        dict(sfx="strangulated", title="Painful irreducible hernia (strangulation)", angle="severe",
             anchor="sistem_hernia-strangulata-inkarserata", age=61, sex="male", setting="emergency department"),
     ]),
dict(id="fam_abscess", spec="surgery", tid="Abses Kulit", ten="Skin Abscess",
     complaints=["Painful red lump with pus", "Boil that keeps growing"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_furunkel-karbunkel", "sistem_abses-peri-anal"],
     obj=["Assess fluctuation + systemic signs", "Decide incision vs antibiotics", "Screen diabetes"],
     diffs=["Selulitis", "Lipoma", "Kista terinfeksi"],
     variants=[
        dict(sfx="furuncle", title="Simple furuncle", angle="typical",
             anchor="sistem_furunkel-karbunkel", age=29, sex="male", setting="primary care"),
        dict(sfx="carbuncle_dm", title="Carbuncle with diabetes", angle="complicated",
             anchor="sistem_furunkel-karbunkel", age=54, sex="female", setting="primary care"),
        dict(sfx="perianal", title="Painful perianal collection", angle="complicated",
             anchor="sistem_abses-peri-anal", age=36, sex="male", setting="emergency department"),
     ]),
dict(id="fam_cellulitis", spec="surgery", tid="Selulitis", ten="Cellulitis",
     complaints=["Hot red spreading leg", "Red painful leg after a scratch"],
     pop=["adult", "older adult"], stages=["koas"],
     skd=["sistem_selulitis", "sistem_erisipelas"],
     obj=["Mark border + check systemic toxicity", "Start antibiotics + elevation pathway", "Spot necrotizing red flags"],
     diffs=["Trombosis vena dalam", "Gout", "Dermatitis kontak"],
     variants=[
        dict(sfx="limb_typical", title="Typical limb cellulitis", angle="complicated",
             anchor="sistem_selulitis", age=57, sex="male", setting="primary care"),
        dict(sfx="erysipelas", title="Well-demarcated erysipelas of the face/leg", angle="typical",
             anchor="sistem_erisipelas", age=48, sex="female", setting="primary care"),
        dict(sfx="toxic", title="Cellulitis with systemic toxicity", angle="severe",
             anchor="sistem_selulitis", age=66, sex="female", setting="emergency department"),
     ]),
dict(id="fam_hemorrhoid", spec="surgery", tid="Hemoroid", ten="Hemorrhoids",
     complaints=["Bleeding when passing stool", "Itchy lump at the anus"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_hemoroid-grade-1-2", "sistem_hemoroid-grade-3-4"],
     obj=["Grade + exclude red-flag bleeding", "Start fiber/topical pathway", "Refer high-grade/prolapsing piles"],
     diffs=["Fisura ani", "Keganasan rektum", "Prolaps rektum"],
     variants=[
        dict(sfx="low_grade", title="Grade 1-2 bleeding piles", angle="typical",
             anchor="sistem_hemoroid-grade-1-2", age=40, sex="male", setting="primary care"),
        dict(sfx="high_grade", title="Prolapsing grade 3-4 piles", angle="complicated",
             anchor="sistem_hemoroid-grade-3-4", age=55, sex="female", setting="primary care"),
     ]),
dict(id="fam_cholecystitis", spec="surgery", tid="Kolesistitis", ten="Cholecystitis",
     complaints=["Right upper belly pain after fatty food", "Colicky upper pain with fever"],
     pop=["adult", "woman"], stages=["koas"],
     skd=["sistem_kolesistitis"],
     obj=["Elicit Murphy + fever pattern", "Order USG + LFT pathway", "Keep NPO + refer for cholecystectomy assessment"],
     diffs=["Gastritis", "Hepatitis", "Pankreatitis"],
     variants=[
        dict(sfx="acute", title="Acute cholecystitis pattern", angle="complicated",
             anchor="sistem_kolesistitis", age=46, sex="female", setting="emergency department"),
        dict(sfx="biliary_colic", title="Biliary-colic-like prodrome case", angle="early",
             anchor="sistem_kolesistitis", age=39, sex="female", setting="primary care"),
     ]),
dict(id="fam_peritonitis", spec="surgery", tid="Nyeri Abdomen Akut Bedah", ten="Surgical Acute Abdomen",
     complaints=["Whole belly hard and very painful", "Sudden severe abdominal pain with guarding"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_peritonitis", "sistem_perforasi-usus"],
     obj=["Detect guarding/rigidity + vitals", "Order erect X-ray/USG pathway", "Resuscitate + urgent surgical referral"],
     diffs=["Apendisitis", "Kehamilan ektopik", "Pankreatitis"],
     variants=[
        dict(sfx="generalized", title="Generalized peritonitis examination", angle="severe",
             anchor="sistem_peritonitis", age=43, sex="male", setting="emergency department"),
        dict(sfx="perforation", title="Perforated-viscus pattern with free air", angle="severe",
             anchor="sistem_perforasi-usus", age=58, sex="male", setting="emergency department"),
     ]),
dict(id="fam_obstruction", spec="surgery", tid="Ileus Obstruksi", ten="Bowel Obstruction",
     complaints=["Crampy belly pain with vomiting, no wind", "Bloated belly, cannot pass stool or gas"],
     pop=["adult", "older adult", "postoperative"], stages=["koas"],
     skd=["sistem_ileus-obstruksi", "sistem_ileus-paralitik"],
     obj=["Elicit colic + obstipation + distension", "Order X-ray + NGT/fluids pathway", "Refer strangulation/complete cases urgently"],
     diffs=["Ileus paralitik", "Konstipasi", "Peritonitis"],
     variants=[
        dict(sfx="mechanical", title="Mechanical small-bowel pattern", angle="severe",
             anchor="sistem_ileus-obstruksi", age=60, sex="male", setting="emergency department"),
        dict(sfx="adhesive", title="Adhesive pattern in a postoperative patient", angle="complicated",
             anchor="sistem_ileus-obstruksi", age=48, sex="female", setting="emergency department"),
     ]),
dict(id="fam_wound", spec="surgery", tid="Luka dan Infeksi Luka", ten="Wounds and Wound Infection",
     complaints=["Cut that looks infected", "Wound with spreading redness"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_vulnus-laceratum-punctum", "sistem_luka-akut"],
     obj=["Assess depth/contamination/tetanus status", "Clean + close vs refer pathway", "Detect infection early"],
     diffs=["Selulitis", "Abses", "Gigitan hewan"],
     variants=[
        dict(sfx="clean_lac", title="Clean laceration needing closure decision", angle="typical",
             anchor="sistem_vulnus-laceratum-punctum", age=28, sex="male", setting="emergency department"),
        dict(sfx="infected", title="Infected wound after delay", angle="complicated",
             anchor="sistem_luka-akut", age=45, sex="female", setting="primary care"),
     ]),
dict(id="fam_intussusception", spec="surgery", tid="Intususepsi Anak", ten="Childhood Intussusception",
     complaints=["Baby screaming in bouts with vomiting", "Colicky episodes with red jelly stool"],
     pop=["infant"], stages=["koas"],
     skd=["sistem_intususepsi"],
     obj=["Elicit paroxysm + stool change", "Arrange ultrasound + air-enema pathway", "Refer before perforation"],
     diffs=["Gastroenteritis", "Apendisitis", "Meckel"],
     variants=[
        dict(sfx="typical", title="Classic infant intussusception", angle="severe",
             anchor="sistem_intususepsi", age=0, sex="male", setting="emergency department"),
        dict(sfx="early", title="Early intermittent pattern", angle="complicated",
             anchor="sistem_intususepsi", age=1, sex="female", setting="emergency department"),
     ]),
# ── MUSCULOSKELETAL (5, under surgery) ──────────────────────────────
dict(id="fam_backpain", spec="surgery", tid="Nyeri Punggung Bawah", ten="Low Back Pain",
     complaints=["Lower back pain shooting down the leg", "Back pain with leg numbness"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_hernia-nucleus-pulposus-hnp", "sistem_radicular-syndrome"],
     obj=["Map dermatomal pattern + red flags", "Trial conservative pathway first", "Refer deficit/cauda equina urgently"],
     diffs=["Strain otot", "Infeksi saluran kemih", "Batu ginjal"],
     variants=[
        dict(sfx="radicular", title="Radicular leg pain (HNP pattern)", angle="typical",
             anchor="sistem_hernia-nucleus-pulposus-hnp", age=44, sex="male", setting="primary care"),
        dict(sfx="redflag", title="Back pain with saddle numbness (red flag)", angle="severe",
             anchor="sistem_radicular-syndrome", age=52, sex="female", setting="emergency department"),
     ]),
dict(id="fam_sprain", spec="surgery", tid="Keseleo", ten="Sprain",
     complaints=["Twisted ankle, now swollen", "Knee gave way after twisting"],
     pop=["young adult", "athlete"], stages=["preclinical", "koas"],
     skd=["sistem_sprain-ankle-and-muscle", "sistem_ruptur-ligamen-lutut"],
     obj=["Apply Ottawa + grade the sprain", "RICE + rehab pathway", "Refer instability/fracture pattern"],
     diffs=["Fraktur", "Ruptur tendon Achilles", "Dislokasi"],
     variants=[
        dict(sfx="ankle_mild", title="Mild lateral ankle sprain", angle="typical",
             anchor="sistem_sprain-ankle-and-muscle", age=23, sex="male", setting="primary care"),
        dict(sfx="knee_lig", title="Knee twist with instability (ligament pattern)", angle="complicated",
             anchor="sistem_ruptur-ligamen-lutut", age=27, sex="female", setting="emergency department"),
     ]),
dict(id="fam_oa", spec="surgery", tid="Osteoarthritis Lutut", ten="Knee Osteoarthritis",
     complaints=["Knee pain worse with stairs", "Stiff knees in the morning briefly"],
     pop=["older adult"], stages=["preclinical", "koas"],
     skd=["sistem_osteoarthritis-grade-1-dan-2", "sistem_osteoarthritis-grade-3-dan-4"],
     obj=["Elicit mechanical pattern + crepitus", "Start weight/exercise/analgesia plan", "Refer advanced cases for arthroplasty assessment"],
     diffs=["Gout", "Artritis reumatoid", "Bursitis"],
     variants=[
        dict(sfx="early", title="Early knee OA, function preserved", angle="typical",
             anchor="sistem_osteoarthritis-grade-1-dan-2", age=58, sex="female", setting="primary care"),
        dict(sfx="advanced", title="Advanced OA with deformity", angle="complicated",
             anchor="sistem_osteoarthritis-grade-3-dan-4", age=69, sex="male", setting="primary care"),
     ]),
dict(id="fam_septic_joint", spec="surgery", tid="Artritis Septik", ten="Septic Arthritis",
     complaints=["Single hot very painful knee with fever", "Joint too painful to move"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_artritis-septik"],
     obj=["Treat as emergency until proven otherwise", "Arrange urgent arthrocentesis pathway", "Refer for washout + IV antibiotics"],
     diffs=["Gout", "Osteoarthritis", "Selulitis"],
     variants=[
        dict(sfx="knee", title="Acute hot knee (septic rule-out)", angle="severe",
             anchor="sistem_artritis-septik", age=49, sex="male", setting="emergency department"),
        dict(sfx="febrile_child", title="Fever with refusal to bear weight", angle="severe",
             anchor="sistem_artritis-septik", age=7, sex="female", setting="emergency department"),
     ]),
dict(id="fam_osteomyelitis", spec="surgery", tid="Osteomielitis", ten="Osteomyelitis",
     complaints=["Deep bone pain with fever", "Non-healing sore over bone"],
     pop=["adult", "diabetic"], stages=["koas"],
     skd=["sistem_osteomielitis"],
     obj=["Link ulcer/trauma to bone pain", "Order X-ray/MRI + culture pathway", "Start antibiotics + surgical referral"],
     diffs=["Selulitis", "Gout", "Tumor tulang"],
     variants=[
        dict(sfx="hematogenous", title="Bone pain with bacteremia pattern", angle="severe",
             anchor="sistem_osteomielitis", age=35, sex="male", setting="emergency department"),
        dict(sfx="diabetic_foot", title="Diabetic foot with bone exposure concern", angle="severe",
             anchor="sistem_osteomielitis", age=61, sex="male", setting="emergency department"),
     ]),
# ── DERMATOLOGY (10) ────────────────────────────────────────────────
dict(id="fam_atopic", spec="dermatology", tid="Dermatitis Atopik", ten="Atopic Dermatitis",
     complaints=["Itchy rash in elbow and knee folds", "Dry itchy patches since childhood"],
     pop=["child", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_dermatitis-atopik-kecuali-recalcitrant", "sistem_dermatitis-seboroik"],
     obj=["Map flexural + chronicity pattern", "Start emollient + topical steroid pathway", "Counsel trigger avoidance"],
     diffs=["Skabies", "Dermatitis kontak", "Psoriasis"],
     variants=[
        dict(sfx="child_flexural", title="Childhood flexural eczema", angle="child",
             anchor="sistem_dermatitis-atopik-kecuali-recalcitrant", age=8, sex="female", setting="primary care"),
        dict(sfx="adult_chronic", title="Chronic adult hand/face pattern", angle="chronic",
             anchor="sistem_dermatitis-atopik-kecuali-recalcitrant", age=29, sex="male", setting="primary care"),
     ]),
dict(id="fam_contact_derm", spec="dermatology", tid="Dermatitis Kontak", ten="Contact Dermatitis",
     complaints=["Itchy rash where watch touches", "Rash after new soap/detergent"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_dermatitis-kontak-iritan", "sistem_dermatitis-kontak-alergika"],
     obj=["Link exposure timing to rash", "Remove trigger + topical pathway", "Patch-test referral for allergic pattern"],
     diffs=["Dermatitis atopik", "Tinea", "Skabies"],
     variants=[
        dict(sfx="irritant", title="Irritant pattern from detergents", angle="typical",
             anchor="sistem_dermatitis-kontak-iritan", age=36, sex="female", setting="primary care"),
        dict(sfx="allergic", title="Allergic pattern needing workup", angle="complicated",
             anchor="sistem_dermatitis-kontak-alergika", age=28, sex="male", setting="primary care"),
     ]),
dict(id="fam_tinea", spec="dermatology", tid="Tinea", ten="Dermatophytosis",
     complaints=["Ring-shaped itchy patch", "Itchy groin rash with clear edge"],
     pop=["adult", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_tinea-corporis", "sistem_tinea-cruris", "sistem_tinea-kapitis"],
     obj=["Recognize annular scaly border", "Use KOH pathway + topical antifungals", "Treat household spread"],
     diffs=["Pitiriasis versikolor", "Dermatitis numularis", "Psoriasis"],
     variants=[
        dict(sfx="corporis", title="Tinea corporis ring lesion", angle="typical",
             anchor="sistem_tinea-corporis", age=25, sex="male", setting="primary care"),
        dict(sfx="cruris", title="Tinea cruris in the groin", angle="typical",
             anchor="sistem_tinea-cruris", age=32, sex="male", setting="primary care"),
        dict(sfx="capitis", title="Scaly scalp patch with hair loss (child)", angle="child",
             anchor="sistem_tinea-kapitis", age=9, sex="female", setting="primary care"),
     ]),
dict(id="fam_scabies", spec="dermatology", tid="Skabies", ten="Scabies",
     complaints=["Itching worse at night, family itches too", "Burrow-like lines between fingers"],
     pop=["child", "household"], stages=["preclinical", "koas"],
     skd=["sistem_skabies"],
     obj=["Elicit nocturnal + household pattern", "Treat whole household + bedding hygiene", "Follow up treatment failure"],
     diffs=["Dermatitis atopik", "Gigitan serangga", "Impetigo"],
     variants=[
        dict(sfx="household", title="Household scabies cluster", angle="typical",
             anchor="sistem_skabies", age=12, sex="male", setting="primary care"),
        dict(sfx="superinfected", title="Scabies with superinfected sores", angle="complicated",
             anchor="sistem_skabies", age=9, sex="female", setting="primary care"),
     ]),
dict(id="fam_impetigo", spec="dermatology", tid="Impetigo", ten="Impetigo",
     complaints=["Honey-colored crusts around mouth", "Sores that spread by scratching"],
     pop=["child"], stages=["preclinical", "koas"],
     skd=["sistem_impetigo", "sistem_ektima"],
     obj=["Recognize golden crusts", "Start topical/systemic pathway by extent", "Hygiene + school exclusion counseling"],
     diffs=["Herpes simpleks", "Varisela", "Dermatitis kontak"],
     variants=[
        dict(sfx="localized", title="Localized honey-crust lesions", angle="child",
             anchor="sistem_impetigo", age=6, sex="female", setting="primary care"),
        dict(sfx="widespread", title="Widespread lesions needing systemic therapy", angle="complicated",
             anchor="sistem_ektima", age=7, sex="male", setting="primary care"),
     ]),
dict(id="fam_urticaria", spec="dermatology", tid="Urtikaria", ten="Urticaria",
     complaints=["Itchy bumps that come and go", "Hives moving around the body"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_urtikaria-akut", "sistem_urtikaria"],
     obj=["Distinguish acute vs chronic course", "Start antihistamine pathway", "Watch airway/anaphylaxis overlap"],
     diffs=["Anafilaksis", "Skabies", "Drug eruption"],
     variants=[
        dict(sfx="acute", title="Acute hives after trigger", angle="typical",
             anchor="sistem_urtikaria-akut", age=27, sex="female", setting="primary care"),
        dict(sfx="chronic", title="Recurrent hives over weeks", angle="chronic",
             anchor="sistem_urtikaria", age=39, sex="male", setting="primary care"),
     ]),
dict(id="fam_acne", spec="dermatology", tid="Akne Vulgaris", ten="Acne Vulgaris",
     complaints=["Pimples on face and back", "Blackheads and painful bumps"],
     pop=["adolescent", "young adult"], stages=["preclinical", "koas"],
     skd=["sistem_akne-vulgaris"],
     obj=["Grade comedonal vs inflammatory", "Start topical retinoid/BP pathway", "Escalate severe/nodular cases"],
     diffs=["Rosacea", "Folikulitis", "Dermatitis perioral"],
     variants=[
        dict(sfx="mild_comedonal", title="Mild comedonal acne", angle="typical",
             anchor="sistem_akne-vulgaris", age=16, sex="female", setting="primary care"),
        dict(sfx="inflammatory", title="Moderate inflammatory acne", angle="complicated",
             anchor="sistem_akne-vulgaris", age=19, sex="male", setting="primary care"),
     ]),
dict(id="fam_psoriasis", spec="dermatology", tid="Psoriasis Ringan", ten="Mild Psoriasis",
     complaints=["Thick silvery scaly plaques on elbows/knees", "Scalp scaling with plaques"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_psoriasis-vulgaris-ringan", "sistem_psoriasis-vulgaris-sedang-dan-berat"],
     obj=["Recognize silvery plaque + Auspitz thinking", "Start emollient + topical pathway", "Refer extensive/arthritic disease"],
     diffs=["Dermatitis seboroik", "Tinea", "Pitiriasis rosea"],
     variants=[
        dict(sfx="mild_plaque", title="Mild plaque psoriasis", angle="typical",
             anchor="sistem_psoriasis-vulgaris-ringan", age=37, sex="male", setting="primary care"),
        dict(sfx="extensive_refer", title="Extensive disease needing referral", angle="complicated",
             anchor="sistem_psoriasis-vulgaris-sedang-dan-berat", age=45, sex="female", setting="primary care"),
     ]),
dict(id="fam_zoster", spec="dermatology", tid="Herpes Zoster", ten="Herpes Zoster",
     complaints=["Painful blister band on one side", "Burning rash in a stripe"],
     pop=["adult", "older adult"], stages=["koas"],
     skd=["sistem_herpes-zoster-tanpa-komplikasi", "sistem_herpes-zoster"],
     obj=["Recognize dermatomal pattern", "Start antivirals within window", "Watch eye involvement + neuralgia"],
     diffs=["Herpes simpleks", "Selulitis", "Kontak dermatitis"],
     variants=[
        dict(sfx="uncomplicated", title="Uncomplicated dermatomal zoster", angle="typical",
             anchor="sistem_herpes-zoster-tanpa-komplikasi", age=55, sex="female", setting="primary care"),
        dict(sfx="ophthalmic_watch", title="Zoster near the eye (referral watch)", angle="complicated",
             anchor="sistem_herpes-zoster", age=63, sex="male", setting="primary care"),
     ]),
dict(id="fam_drug_eruption", spec="dermatology", tid="Erupsi Obat", ten="Drug Eruption",
     complaints=["Rash days after starting a new drug", "Widespread red rash with fever after medication"],
     pop=["adult"], stages=["koas"],
     skd=["sistem_exanthematous-drug-eruption-fixed-drug-eruption", "sistem_sindrom-stevens-johnson-ssj"],
     obj=["Build a drug timeline", "Stop suspect drug + supportive pathway", "Detect SJS/TEN warning and refer emergently"],
     diffs=["Morbili", "Urtikaria", "Vaskulitis"],
     variants=[
        dict(sfx="morbilliform", title="Morbilliform drug rash", angle="complicated",
             anchor="sistem_exanthematous-drug-eruption-fixed-drug-eruption", age=42, sex="female", setting="primary care"),
        dict(sfx="sjs_warning", title="Blistering mucosal pattern (SJS rule-out)", angle="severe",
             anchor="sistem_sindrom-stevens-johnson-ssj", age=35, sex="male", setting="emergency department"),
     ]),
# ── ENT (8) ─────────────────────────────────────────────────────────
dict(id="fam_otitis_ext", spec="ent", tid="Otitis Eksterna", ten="Otitis Externa",
     complaints=["Itchy painful ear after swimming", "Ear pain when touching the ear"],
     pop=["adult", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_otitis-eksterna"],
     obj=["Elicit water/trauma history + tragal tenderness", "Start topical pathway + dry-ear counseling", "Refer malignant-pattern cases"],
     diffs=["Otitis media", "Benda asing telinga", "Furunkel"],
     variants=[
        dict(sfx="swimmer", title="Swimmer-pattern otitis externa", angle="typical",
             anchor="sistem_otitis-eksterna", age=21, sex="male", setting="primary care"),
        dict(sfx="diabetic_watch", title="Severe ear pain in diabetes (watch pattern)", angle="complicated",
             anchor="sistem_otitis-eksterna", age=58, sex="female", setting="primary care"),
     ]),
dict(id="fam_otitis_media", spec="ent", tid="Otitis Media", ten="Otitis Media",
     complaints=["Ear pain with fever after flu", "Muffled hearing with ear fullness"],
     pop=["child", "adult"], stages=["preclinical", "koas"],
     skd=["sistem_otitis-media-serosa", "sistem_otitis-media-akut"],
     obj=["Distinguish effusion vs acute infection", "Apply watchful vs antibiotic pathway", "Safety-net for mastoiditis"],
     diffs=["Otitis eksterna", "Benda asing", "Barotrauma"],
     variants=[
        dict(sfx="serosa", title="Effusion with muffled hearing (child)", angle="child",
             anchor="sistem_otitis-media-serosa", age=6, sex="male", setting="primary care"),
        dict(sfx="acute", title="Acute painful otitis media", angle="typical",
             anchor="sistem_otitis-media-akut", age=5, sex="female", setting="primary care"),
        dict(sfx="recurrent", title="Recurrent episodes needing referral", angle="complicated",
             anchor="sistem_otitis-media-akut", age=8, sex="male", setting="primary care"),
     ]),
dict(id="fam_sinusitis", spec="ent", tid="Sinusitis Akut", ten="Acute Sinusitis",
     complaints=["Thick nasal discharge with facial pressure", "Cold lasting over 10 days with face pain"],
     pop=["adult"], stages=["preclinical", "koas"],
     skd=["sistem_sinusitis-akut", "sistem_rhinitis-akut"],
     obj=["Apply duration/severity/double-worsening rule", "Start saline + decongestant pathway", "Reserve antibiotics for bacterial pattern"],
     diffs=["Rhinitis akut", "Migren", "Sakit gigi"],
     variants=[
        dict(sfx="viral_like", title="Prolonged cold-like congestion", angle="typical",
             anchor="sistem_rhinitis-akut", age=30, sex="female", setting="primary care"),
        dict(sfx="bacterial", title="Bacterial-pattern facial pain with purulence", angle="complicated",
             anchor="sistem_sinusitis-akut", age=38, sex="male", setting="primary care"),
     ]),
dict(id="fam_rhinitis", spec="ent", tid="Rhinitis Alergi", ten="Allergic Rhinitis",
     complaints=["Sneezing fits with itchy nose and eyes", "Runny nose every dusty morning"],
     pop=["adolescent", "adult"], stages=["preclinical", "koas"],
     skd=["sistem_rhinitis-alergika", "sistem_rhinitis-vasomotor"],
     obj=["Elicit trigger + seasonality pattern", "Start intranasal steroid + antihistamine pathway", "Counsel avoidance + asthma overlap"],
     diffs=["Rhinitis akut", "Sinusitis", "Benda asing hidung"],
     variants=[
        dict(sfx="seasonal", title="Seasonal allergic pattern", angle="typical",
             anchor="sistem_rhinitis-alergika", age=19, sex="female", setting="primary care"),
        dict(sfx="persistent", title="Persistent year-round pattern", angle="chronic",
             anchor="sistem_rhinitis-vasomotor", age=34, sex="male", setting="primary care"),
     ]),
dict(id="fam_epistaxis", spec="ent", tid="Mimisan", ten="Epistaxis",
     complaints=["Nosebleed that will not stop", "Recurrent nosebleeds when picking nose"],
     pop=["child", "adult", "older adult"], stages=["preclinical", "koas"],
     skd=["sistem_epistaxis-anterior", "sistem_epistaksis-sedang-berat"],
     obj=["Apply pressure + posture first aid", "Find anticoagulant/hypertension contributors", "Pack/refer posterior or recurrent cases"],
     diffs=["Trauma hidung", "Tumor hidung", "Koagulopati"],
     variants=[
        dict(sfx="anterior_mild", title="Mild anterior bleed, controlled", angle="typical",
             anchor="sistem_epistaxis-anterior", age=10, sex="male", setting="primary care"),
        dict(sfx="recurrent_adult", title="Recurrent bleed on anticoagulant", angle="complicated",
             anchor="sistem_epistaksis-sedang-berat", age=67, sex="female", setting="emergency department"),
     ]),
dict(id="fam_pharyngitis", spec="ent", tid="Faringitis dan Tonsilitis", ten="Pharyngitis and Tonsillitis",
     complaints=["Very sore throat with fever", "Pain swallowing with swollen neck glands"],
     pop=["child", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_faringitis", "sistem_tonsilitis-36"],
     obj=["Apply fever/centor-style reasoning", "Distinguish viral vs strep pattern", "Reserve antibiotics + watch abscess"],
     diffs=["Mononukleosis", "Difteria", "GERD"],
     variants=[
        dict(sfx="viral", title="Viral-pattern sore throat", angle="typical",
             anchor="sistem_faringitis", age=14, sex="female", setting="primary care"),
        dict(sfx="strep_like", title="Exudative tonsillitis pattern", angle="complicated",
             anchor="sistem_tonsilitis-36", age=12, sex="male", setting="primary care"),
     ]),
dict(id="fam_fb_ent", spec="ent", tid="Benda Asing THT", ten="ENT Foreign Bodies",
     complaints=["Something stuck in the nose", "Sudden blocked ear after playing"],
     pop=["child"], stages=["preclinical", "koas"],
     skd=["sistem_benda-asing-hidung", "sistem_benda-asing-telinga"],
     obj=["Keep the child calm + avoid pushing deeper", "Remove simple anterior objects safely", "Refer airway-risk cases immediately"],
     diffs=["Rhinitis", "Otitis eksterna", "Serumen"],
     variants=[
        dict(sfx="nasal", title="Nasal foreign body in a child", angle="child",
             anchor="sistem_benda-asing-hidung", age=4, sex="male", setting="emergency department"),
        dict(sfx="aural", title="Aural foreign body with blocked hearing", angle="child",
             anchor="sistem_benda-asing-telinga", age=6, sex="female", setting="primary care"),
     ]),
dict(id="fam_hearing", spec="ent", tid="Gangguan Dengar", ten="Hearing Loss",
     complaints=["Gradually cannot hear well", "Blocked ear with wax"],
     pop=["older adult", "adult"], stages=["koas"],
     skd=["sistem_presbiakusis", "sistem_serumen-prop"],
     obj=["Distinguish conductive vs sensorineural pattern", "Clear wax safely + audiometry pathway", "Refer for hearing-aid assessment"],
     diffs=["Otitis media serosa", "Otosklerosis", "Benda asing"],
     variants=[
        dict(sfx="wax", title="Wax impaction with reversible loss", angle="typical",
             anchor="sistem_serumen-prop", age=48, sex="male", setting="primary care"),
        dict(sfx="presbycusis", title="Gradual bilateral age-related loss", angle="chronic",
             anchor="sistem_presbiakusis", age=70, sex="female", setting="primary care"),
     ]),
# ── OPHTHALMOLOGY (6) ───────────────────────────────────────────────
dict(id="fam_conjunctivitis", spec="ophthalmology", tid="Konjungtivitis", ten="Conjunctivitis",
     complaints=["Red itchy eyes with discharge", "Red eyes since yesterday"],
     pop=["adult", "child"], stages=["preclinical", "koas"],
     skd=["sistem_konjungtivitis-bakteri-virus-alergi"],
     obj=["Distinguish bacterial/viral/allergic discharge", "Start hygiene + topical pathway", "Detect keratitis/glaucoma mimics"],
     diffs=["Keratitis", "Glaukoma akut", "Benda asing kornea"],
     variants=[
        dict(sfx="bacterial", title="Purulent bacterial pattern", angle="typical",
             anchor="sistem_konjungtivitis-bakteri-virus-alergi", age=9, sex="male", setting="primary care"),
        dict(sfx="viral", title="Watery viral pattern with contact history", angle="typical",
             anchor="sistem_konjungtivitis-bakteri-virus-alergi", age=26, sex="female", setting="primary care"),
        dict(sfx="allergic", title="Itchy allergic pattern in pollen season", angle="typical",
             anchor="sistem_konjungtivitis-bakteri-virus-alergi", age=19, sex="female", setting="primary care"),
     ]),
dict(id="fam_hordeolum", spec="ophthalmology", tid="Hordeolum dan Blefaritis", ten="Hordeolum and Blepharitis",
     complaints=["Painful bump on eyelid", "Crusty eyelids in the morning"],
     pop=["adult", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_hordeolum", "sistem_blefaritis"],
     obj=["Distinguish stye vs chalazion vs preseptal spread", "Start warm compress + hygiene pathway", "Refer vision-change/orbital cases"],
     diffs=["Kalazion", "Selulitis preseptal", "Dakrioadenitis"],
     variants=[
        dict(sfx="stye", title="Acute painful stye", angle="typical",
             anchor="sistem_hordeolum", age=22, sex="female", setting="primary care"),
        dict(sfx="blepharitis", title="Chronic crusty blepharitis", angle="chronic",
             anchor="sistem_blefaritis", age=47, sex="male", setting="primary care"),
     ]),
dict(id="fam_refractive", spec="ophthalmology", tid="Gangguan Refraksi Ringan", ten="Mild Refractive Error",
     complaints=["Cannot see the board clearly", "Blurry distance vision"],
     pop=["school-age", "adolescent"], stages=["preclinical", "koas"],
     skd=["sistem_miopia-ringan", "sistem_mata-kering"],
     obj=["Elicit distance vs near blur pattern", "Arrange refraction pathway", "Counsel screen habits + follow-up"],
     diffs=["Astigmatisme", "Keratitis", "Katarak dini"],
     variants=[
        dict(sfx="myopia", title="School-age myopia screening case", angle="typical",
             anchor="sistem_miopia-ringan", age=12, sex="female", setting="primary care"),
        dict(sfx="dryeye", title="Dry-eye pattern in screen-heavy adult", angle="chronic",
             anchor="sistem_mata-kering", age=33, sex="male", setting="primary care"),
     ]),
dict(id="fam_glaucoma", spec="ophthalmology", tid="Glaukoma Akut", ten="Acute Glaucoma",
     complaints=["Sudden very painful red eye with blurred vision", "Eye pain with halos and nausea"],
     pop=["older adult"], stages=["koas"],
     skd=["sistem_glaukoma-akut"],
     obj=["Recognize painful red eye + halos + nausea triad", "Check pressure-equivalent urgency + refer same-day", "Never give dilating drops"],
     diffs=["Konjungtivitis", "Keratitis", "Migren"],
     variants=[
        dict(sfx="acute_attack", title="Acute angle-closure attack", angle="severe",
             anchor="sistem_glaukoma-akut", age=62, sex="female", setting="emergency department"),
        dict(sfx="subacute", title="Intermittent halo episodes (subacute pattern)", angle="complicated",
             anchor="sistem_glaukoma-akut", age=58, sex="male", setting="primary care"),
     ]),
dict(id="fam_corneal", spec="ophthalmology", tid="Trauma Kornea", ten="Corneal Trauma",
     complaints=["Something hit the eye, now painful and watery", "Eye pain after grinding work without goggles"],
     pop=["adult", "worker"], stages=["koas"],
     skd=["sistem_trauma-kornea", "sistem_benda-asing-di-kornea"],
     obj=["Elicit velocity/chemical context + vision check", "Stain/protect + urgent ophthalmology referral", "Update tetanus where relevant"],
     diffs=["Konjungtivitis", "Laserasi kelopak", "Luka bakar kimia"],
     variants=[
        dict(sfx="abrasion", title="Corneal abrasion after minor trauma", angle="complicated",
             anchor="sistem_trauma-kornea", age=29, sex="male", setting="emergency department"),
        dict(sfx="fb", title="Corneal foreign body in a metal worker", angle="complicated",
             anchor="sistem_benda-asing-di-kornea", age=36, sex="male", setting="emergency department"),
     ]),
dict(id="fam_keratitis", spec="ophthalmology", tid="Keratitis", ten="Keratitis",
     complaints=["Painful red eye sensitive to light", "Contact-lens wearer with painful red eye"],
     pop=["adult", "contact-lens wearer"], stages=["koas"],
     skd=["sistem_keratitis", "sistem_masalah-kornea-terkait-lensa-kontak"],
     obj=["Spot photophobia + vision drop as corneal flags", "Stop lens wear + urgent referral", "Never steroid a dendritic pattern blindly"],
     diffs=["Konjungtivitis", "Glaukoma akut", "Uveitis"],
     variants=[
        dict(sfx="lens_related", title="Contact-lens-related keratitis", angle="complicated",
             anchor="sistem_masalah-kornea-terkait-lensa-kontak", age=24, sex="female", setting="emergency department"),
        dict(sfx="ulcer_watch", title="Central opacity with vision drop (referral watch)", angle="severe",
             anchor="sistem_keratitis", age=41, sex="male", setting="emergency department"),
     ]),
]
