"""Phase 4 continuation — clinical renderer (system profiles + angle modifiers).

Produces SUBSTANTIVE, internally-consistent ClinicalVariant truth from standard
clinical knowledge. Honesty rules:
- working_diagnosis wording follows the official SKD 2026 entry name.
- competency.category is READ from the anchor catalog entry (never guessed).
- Sources: SKD 2026 competency (verified artifact) + clinical-basis source with
  url="" and review_status="pending_human" (exact PNPK/society edition must be
  attached by a human reviewer — we never invent URLs, titles, or edition nos).
- status is always research_complete (never reviewed/published).
"""
from __future__ import annotations

# ── System clinical profiles ─────────────────────────────────────────────
# Each: exam systems, investigation panel, medication classes, red-flag pool,
# history prompt pools. These are standard bedside knowledge, not citations.
SYSTEMS: dict[str, dict] = {
"sistem_respirasi": dict(
    exam=["lungs: breath sounds, added sounds, respiratory effort",
          "nose_throat: nasal discharge, pharyngeal erythema, tonsils",
          "general: use of accessory muscles, cyanosis"],
    inv=[("Chest X-ray", "essential"), ("Pulse oximetry", "essential"),
         ("Sputum molecular test / AFB smear", "appropriate"),
         ("Complete blood count", "appropriate"), ("CRP", "optional")],
    meds=[("amoxicillin", "beta-lactam antibiotic", "amoxicillin", ["amoxicillin-clavulanate"]),
          ("salbutamol", "short-acting bronchodilator", "salbutamol inhaler", ["budesonide-formoterol"]),
          ("paracetamol", "antipyretic-analgesic", "paracetamol", ["ibuprofen"])],
    reds=["Respiratory rate >= 30/min with hypoxemia", "Stridor or silent chest",
          "Hemoptysis with weight loss", "Chest pain with breathlessness"],
    hx=["cough onset and character", "sputum colour and amount", "fever pattern",
        "breathlessness triggers", "smoking and exposure history", "immunization history"]),
"sistem_kardiovaskuler": dict(
    exam=["heart: rate, rhythm, murmurs, JVP",
          "lungs: basal crackles, effusion signs",
          "extremities: edema, pulses, capillary refill"],
    inv=[("ECG 12-lead", "essential"), ("Chest X-ray", "appropriate"),
         ("High-sensitivity troponin", "appropriate"), ("Echocardiography", "appropriate"),
         ("Serum electrolytes + creatinine", "appropriate")],
    meds=[("amlodipine", "calcium-channel blocker", "amlodipine", ["candesartan"]),
          ("bisoprolol", "beta blocker", "bisoprolol", ["metoprolol"]),
          ("aspirin", "antiplatelet", "aspirin", ["clopidogrel"])],
    reds=["Chest pain with diaphoresis and radiation", "SBP < 90 with cold extremities",
          "New severe breathlessness lying flat", "Syncope with exertion"],
    hx=["chest pain character and radiation", "exertional threshold", "orthopnea and PND",
        "palpitations and syncope", "smoking, hypertension, diabetes history", "family cardiac history"]),
"sistem_endokrin_metabolik_nutrisi": dict(
    exam=["general: hydration, nutrition status, BMI",
          "neck: thyroid size and nodules",
          "feet: pulses, sensation, deformity (diabetes)"],
    inv=[("Fasting blood glucose", "essential"), ("HbA1c", "essential"),
         ("Lipid profile", "appropriate"), ("TSH + FT4", "appropriate"),
         ("Serum electrolytes", "appropriate")],
    meds=[("metformin", "biguanide glucose-lowering", "metformin", ["glimepiride"]),
          ("insulin glargine", "basal insulin", "insulin glargine", ["insulin NPH"]),
          ("atorvastatin", "statin", "atorvastatin", ["simvastatin"])],
    reds=["Fruity breath with rapid deep breathing", "Cold sweat with confusion on therapy",
          "Thyroid storm features (fever, agitation, tachycardia)", "Severe dehydration with polyuria"],
    hx=["polyuria, polydipsia, polyphagia", "weight change", "medication adherence and diet",
        "hypoglycemia episodes", "family diabetes history", "thyroid symptoms review"]),
"sistem_gi_hepatobilier_pankreas": dict(
    exam=["abdomen: tenderness location, guarding, rebound, Murphy sign",
          "general: jaundice, dehydration, pallor",
          "rectal: stool colour, blood (as indicated)"],
    inv=[("Complete blood count", "essential"), ("ALT/AST + bilirubin", "appropriate"),
         ("Abdominal ultrasound", "appropriate"), ("Stool analysis / culture", "appropriate"),
         ("Blood culture (febrile)", "optional")],
    meds=[("omeprazole", "proton-pump inhibitor", "omeprazole", ["lansoprazole"]),
          ("oral rehydration salts", "rehydration", "ORS", ["IV ringer lactate"]),
          ("ciprofloxacin", "fluoroquinolone antibiotic", "ciprofloxacin", ["ceftriaxone"])],
    reds=["Vomiting blood or black tarry stool", "Rigid abdomen with guarding",
          "Persistent vomiting with no urine output", "Jaundice with confusion or coagulopathy"],
    hx=["pain onset, site, migration, character", "vomiting and stool pattern",
        "NSAID/alcohol use", "food and water exposure", "weight loss and appetite"]),
"sistem_ginjal_saluran_kemih": dict(
    exam=["flank: costovertebral-angle tenderness",
          "abdomen: suprapubic tenderness, bladder distension",
          "general: edema, hydration, blood pressure"],
    inv=[("Urinalysis", "essential"), ("Urine culture", "essential"),
         ("Serum creatinine + electrolytes", "appropriate"), ("Renal ultrasound", "appropriate"),
         ("Complete blood count", "optional")],
    meds=[("ciprofloxacin", "fluoroquinolone antibiotic", "ciprofloxacin", ["cefadroxil"]),
          ("paracetamol", "antipyretic-analgesic", "paracetamol", ["ibuprofen"]),
          ("tamsulosin", "alpha blocker (retention pattern)", "tamsulosin", [])],
    reds=["Fever with flank pain and vomiting", "No urine for > 8 hours",
          "Testicular pain of sudden onset", "Edema with breathlessness and oliguria"],
    hx=["dysuria, frequency, urgency", "flank or suprapubic pain", "urine colour and smell",
        "vaginal discharge (as relevant)", "stone history", "fluid intake and output"]),
"sistem_hemato_imunologi": dict(
    exam=["general: pallor, jaundice, petechiae",
          "lymph nodes: cervical, axillary, inguinal",
          "abdomen: spleen and liver size"],
    inv=[("Complete blood count + indices", "essential"), ("Peripheral blood smear", "appropriate"),
         ("Ferritin / serum iron", "appropriate"), ("Dengue NS1 / RDT panel (febrile)", "appropriate"),
         ("Reticulocyte count", "optional")],
    meds=[("ferrous sulfate", "oral iron", "ferrous sulfate", ["iron polymaltose"]),
          ("folic acid", "hematinic adjunct", "folic acid", []),
          ("paracetamol", "antipyretic-analgesic", "paracetamol", ["ibuprofen"])],
    reds=["Active bleeding withhemodynamic change", "Petechiae with fever and shock signs",
          "Severe pallor with breathlessness at rest", "Neutropenic fever pattern"],
    hx=["fatigue and exertional symptoms", "bleeding and bruising", "fever pattern and exposures",
        "nutrition and menstrual history", "drug causes review"]),
"sistem_indera_hidung": dict(
    exam=["nose: discharge character, mucosal edema, polyps",
          "sinuses: maxillary/frontal tenderness",
          "throat: postnasal drip, tonsils"],
    inv=[("Nasal endoscopy finding (as available)", "optional"), ("Sinus X-ray / CT (selected)", "optional"),
         ("Complete blood count", "optional"), ("Allergy review", "appropriate")],
    meds=[("fluticasone nasal spray", "intranasal corticosteroid", "fluticasone", ["mometasone"]),
          ("cetirizine", "antihistamine", "cetirizine", ["loratadine"]),
          ("sodium chloride irrigation", "saline irrigation", "NaCl 0.9% wash", [])],
    reds=["Unilateral foul bloody discharge in a child", "Periorbital swelling with fever",
          "Severe nosebleed not stopping with pressure", "CSF-like watery leak after trauma"],
    hx=["discharge character and duration", "nasal blockage laterality", "sneezing and itch triggers",
        "facial pain pattern", "smell disturbance"]),
"sistem_indera_mata": dict(
    exam=["eyes: conjunctival injection, discharge type, chemosis",
          "vision: bedside acuity each eye",
          "lids_cornea: swelling, corneal clarity, fluorescein pattern (as available)"],
    inv=[("Bedside visual acuity", "essential"), ("Fluorescein staining", "appropriate"),
         ("Slit-lamp finding (as available)", "appropriate"), ("Intraocular pressure (red-flag)", "appropriate")],
    meds=[("chloramphenicol eye drops", "topical antibiotic", "chloramphenicol 0.5%", ["gentamicin eye drops"]),
          ("artificial tears", "ocular lubricant", "artificial tears", []),
          ("olopatadine eye drops", "topical antihistamine", "olopatadine", [])],
    reds=["Sudden vision loss", "Severe eye pain with halos and nausea",
          "Chemical injury to the eye", "Corneal opacity with vision drop"],
    hx=["onset and laterality", "pain vs itch vs discharge", "vision change and halos",
        "trauma or lens wear", "allergy and contact history"]),
"sistem_indera_telinga": dict(
    exam=["ear: canal edema/discharge, tragal tenderness, tympanic membrane",
          "hearing: bedside whisper/Rinne-Weber (as available)",
          "nose_throat: concurrent URTI signs"],
    inv=[("Otoscopy finding", "essential"), ("Audiometry (persistent loss)", "appropriate"),
         ("Tympanometry (effusion)", "appropriate"), ("Complete blood count (febrile)", "optional")],
    meds=[("ofloxacin ear drops", "topical antibiotic", "ofloxacin", ["polymyxin ear drops"]),
          ("paracetamol", "analgesic", "paracetamol", ["ibuprofen"]),
          ("cetirizine", "antihistamine adjunct", "cetirizine", [])],
    reds=["Mastoid swelling with fever", "Facial weakness with ear pain",
          "Sudden sensorineural loss", "Vertigo with vomiting and gait change"],
    hx=["ear pain character and triggers", "discharge and hearing change", "preceding flu/cold",
        "water exposure and trauma", "dizziness pattern"]),
"sistem_kulit_integumen": dict(
    exam=["skin: morphology, distribution, border, scale, crust",
          "nails_hair: involvement pattern",
          "general: fever, lymph nodes (infected cases)"],
    inv=[("KOH scraping (scaly lesions)", "appropriate"), ("Bacterial swab/culture (infected)", "appropriate"),
         ("Dermoscopy finding (as available)", "optional"), ("Complete blood count (systemic)", "optional")],
    meds=[("hydrocortisone cream", "low-potency topical steroid", "hydrocortisone 1%", ["mometasone cream"]),
          ("permethrin cream", "scabicide", "permethrin 5%", ["benzyl benzoate"]),
          ("mupirocin ointment", "topical antibiotic", "mupirocin", ["fusidic acid"])],
    reds=["Rapid blistering with mucosal involvement", "Widespread pustules with fever",
          "Necrotic center with severe pain", "Erythroderma with systemic upset"],
    hx=["onset and spread", "itch severity and timing", "new drugs, soaps, exposures",
        "household similar cases", "atopy history"]),
"sistem_muskuloskeletal": dict(
    exam=["joint: swelling, warmth, range of motion, effusion",
          "spine: tenderness, straight-leg raise, neurology",
          "gait_function: weight bearing, deformity"],
    inv=[("Joint X-ray", "appropriate"), ("Serum uric acid (monoarthritis)", "appropriate"),
         ("CRP/ESR (inflammatory)", "appropriate"), ("Synovial fluid analysis (hot joint)", "appropriate")],
    meds=[("ibuprofen", "NSAID", "ibuprofen", ["diclofenac"]),
          ("colchicine", "gout flare agent", "colchicine", []),
          ("paracetamol", "analgesic", "paracetamol", [])],
    reds=["Single hot joint with fever", "Back pain with saddle numbness or retention",
          "Open fracture or neurovascular deficit", "Fever with bone pain and ulcer"],
    hx=["onset and trauma", "pain pattern and stiffness duration", "swelling and redness",
        "fever and systemic features", "gout/diet/alcohol history", "function limitation"]),
"sistem_reproduksi": dict(
    exam=["abdomen: fundal height, fetal lie/presentation (pregnancy), tenderness",
          "vitals_bp: blood pressure + urine protein (pregnancy)",
          "pelvic: discharge character, bleeding amount, cervical state (as indicated)"],
    inv=[("Urine pregnancy test / beta-hCG", "essential"), ("Hemoglobin", "appropriate"),
         ("Obstetric ultrasound", "appropriate"), ("Urinalysis + protein", "appropriate"),
         ("Blood group + rhesus", "appropriate")],
    meds=[("ferrous sulfate", "oral iron in pregnancy", "ferrous sulfate", []),
          ("methyldopa", "antihypertensive option in pregnancy", "methyldopa", ["nifedipine"]),
          ("nystatin", "topical antifungal", "nystatin", ["miconazole"])],
    reds=["Heavy vaginal bleeding with dizziness", "Severe headache/visual change in pregnancy",
          "Fluid gush with fever", "Absent fetal movement with concern", "Shoulder-tip pain with syncope"],
    hx=["last menstrual period and cycle pattern", "bleeding amount and clots",
        "pain character and location", "discharge character and odor",
        "pregnancy danger signs review", "contraceptive history"]),
"sistem_saraf": dict(
    exam=["neuro: GCS, pupils, facial symmetry, limb power, reflexes",
          "meningeal: neck stiffness, Kernig/Brudzinski",
          "gait_coordination: balance, nystagmus (vertigo)"],
    inv=[("Bedside glucose", "essential"), ("Non-contrast head CT (deficit/trauma)", "appropriate"),
         ("Lumbar puncture pathway (meningitis pattern)", "appropriate"),
         ("Complete blood count + electrolytes", "appropriate")],
    meds=[("paracetamol", "analgesic", "paracetamol", ["ibuprofen"]),
          ("ondansetron", "antiemetic adjunct", "ondansetron", []),
          ("diazepam rectal", "seizure rescue pathway", "diazepam", ["midazolam"])],
    reds=["Thunderclap worst-ever headache", "Focal deficit with last-known-well time",
          "Fever with neck stiffness and rash", "Seizure lasting > 5 minutes", "Progressive weakness with breathing change"],
    hx=["headache onset and severity scale", "weakness distribution and timing",
        "seizure witness account", "fever and neck pain", "trauma and toxin review"]),
"psikiatri": dict(
    exam=["mental_state: appearance, speech, mood, affect, thought, perception, cognition",
          "risk: suicide/self-harm intent, plan, means, protection",
          "general: vitals, thyroid signs, substance signs"],
    inv=[("PHQ-9/GAD-7 style symptom count", "appropriate"), ("TSH (new mood/anxiety)", "appropriate"),
         ("Substance review + urine screen (as indicated)", "optional"),
         ("Collateral history from family", "appropriate")],
    meds=[("sertraline", "SSRI antidepressant", "sertraline", ["fluoxetine"]),
          ("diazepam short course", "anxiolytic bridge (short, supervised)", "diazepam", []),
          ("olanzapine", "antipsychotic (referral pathway)", "olanzapine", ["risperidone"])],
    reds=["Active suicidal plan with means", "Command hallucinations to harm",
          "Severe agitation with danger to others", "Refusal to eat/drink with decline"],
    hx=["mood and interest over 2 weeks", "sleep, appetite, energy", "anxiety triggers and panic features",
        "psychotic experiences", "substance use", "stressors and support", "safety questions"]),
"kepala_dan_leher": dict(
    exam=["neck: swelling, lymph nodes, thyroid, torticollis posture",
          "airway: stridor, drooling, voice change",
          "throat_larynx: erythema, exudate, foreign body signs"],
    inv=[("Neck ultrasound (mass)", "appropriate"), ("Lateral neck X-ray (stridor)", "appropriate"),
         ("Complete blood count", "optional")],
    meds=[("dexamethasone", "airway-edema steroid pathway", "dexamethasone", ["prednisone"]),
          ("amoxicillin-clavulanate", "antibiotic (bacterial pattern)", "amoxicillin-clavulanate", []),
          ("paracetamol", "analgesic-antipyretic", "paracetamol", [])],
    reds=["Stridor at rest with drooling", "Neck swelling with breathing difficulty",
          "Button-battery suspicion", "Rapid airway swelling after sting"],
    hx=["onset and noise character", "fever and swallowing", "foreign body suspicion",
        "allergy and sting history", "neck pain and movement"]),
}

# Angle → presentation modifiers
ANGLES: dict[str, dict] = {
"typical": dict(sev="moderate", stab=False, urg="routine", dur="3 days",
                red_present=1, setting_default="primary care"),
"early": dict(sev="mild", stab=False, urg="routine", dur="1 day",
              red_present=0, setting_default="primary care"),
"chronic": dict(sev="mild", stab=False, urg="routine", dur="3 months",
                red_present=0, setting_default="primary care"),
"complicated": dict(sev="moderate-severe", stab=False, urg="urgent (<24h)", dur="5 days",
                    red_present=2, setting_default="primary care"),
"severe": dict(sev="severe", stab=True, urg="immediate/emergency", dur="1 day",
               red_present=3, setting_default="emergency department"),
"pregnancy": dict(sev="moderate", stab=False, urg="urgent (<24h)", dur="2 days",
                  red_present=1, setting_default="primary care"),
"child": dict(sev="moderate", stab=False, urg="routine", dur="2 days",
              red_present=1, setting_default="primary care"),
"elderly": dict(sev="moderate", stab=False, urg="routine", dur="1 week",
                red_present=1, setting_default="primary care"),
}
