// ============================================================
// Qora — clinical catalogues for the post-Assess pickers (§4.8)
// ------------------------------------------------------------
// Comprehensive, specialty-agnostic lists of investigations and
// management options for the "Data Penunjang" (investigations) and
// "Terapi" (therapy) pickers. English (product language). Expand freely.
// Exposed on window for the concatenated bundle scope.
// ============================================================

window.QORA_INVESTIGATIONS = {
  'Haematology': [
    'Full Blood Count (FBC) with differential',
    'Blood film / Peripheral smear',
    'Reticulocyte count',
    'Erythrocyte Sedimentation Rate (ESR)',
    'Haematinics (ferritin, B12, folate)',
    'Iron studies (serum iron, TIBC, transferrin sat)',
    'Coagulation screen (PT / APTT / INR)',
    'D-dimer',
    'Fibrinogen level',
    'Group & Save / Blood typing',
    'Crossmatch',
    'HbA1c',
    'Haemoglobin electrophoresis (Hb typing)',
    'G6PD screen',
    'Sickle cell screen',
    'Coombs test (direct / indirect)',
    'Bone marrow aspiration / biopsy',
    'Cytogenetics / Flow cytometry',
    'Peripheral blood CD4 count',
    'Thrombophilia screen (Protein C/S, Antithrombin III)',
  ],
  'Clinical Chemistry / Biochemistry': [
    'Urea & Electrolytes (U&E / BMP)',
    'Liver Function Tests (LFTs) — ALT, AST, ALP, GGT, bilirubin, albumin',
    'C-reactive protein (CRP)',
    'Procalcitonin (PCT)',
    'Bone profile — calcium, phosphate, alkaline phosphatase',
    'Magnesium',
    'Phosphate',
    'Amylase',
    'Lipase',
    'High-sensitivity troponin (hs-cTnI / hs-cTnT)',
    'BNP / NT-proBNP',
    'Thyroid Function Tests (TSH, FT4, FT3)',
    'Fasting blood glucose',
    'Random blood glucose',
    '2-hour postprandial glucose',
    'OGTT (Oral Glucose Tolerance Test)',
    'Lipid profile (total, LDL, HDL, TG)',
    'Serum urate / Uric acid',
    'Creatine Kinase (CK / CPK)',
    'Lactate dehydrogenase (LDH)',
    'Cortisol (serum / salivary)',
    'Ammonia',
    'Lactate',
    'Arterial Blood Gas (ABG)',
    'Venous Blood Gas (VBG)',
    'Blood ketones (beta-hydroxybutyrate)',
    'Toxicology screen (serum / urine)',
    'Paracetamol / salicylate level',
    'Lithium level',
    'Vancomycin trough',
    'Aminoglycoside peak/trough',
    'Carbamazepine / valproate / phenytoin level',
    'Vitamin D (25-OH)',
    'Vitamin B12',
    'Folate (RBC folate)',
    'Zinc / Copper / Selenium',
    'CA-125',
    'CA 19-9',
    'CEA',
    'AFP (Alpha-fetoprotein)',
    'PSA (total / free)',
    'Beta-hCG (quantitative / qualitative)',
  ],
  'Immunology & Serology': [
    'Antinuclear antibody (ANA)',
    'Anti-dsDNA',
    'ANCA (c-ANCA, p-ANCA)',
    'Rheumatoid factor (RF)',
    'Anti-CCP',
    'Complement C3 / C4',
    'Immunoglobulins (IgG, IgA, IgM, IgE)',
    'Serum protein electrophoresis (SPEP)',
    'Serum free light chains (kappa / lambda)',
    'Cryoglobulins',
    'Coeliac serology (anti-tTG, EMA)',
    'Anti-streptolysin O (ASO) titre',
    'Anti-DNase B',
    'VDRL / RPR (with TPHA confirmation)',
    'Cytokine panel (IL-6, TNF-alpha)',
    'Allergen-specific IgE (RAST)',
    'Tryptase (mast cell)',
    'Quantiferon-TB Gold',
    'Mantoux / Tuberculin skin test (TST)',
  ],
  'Microbiology & Infectious Disease': [
    'Blood cultures (aerobic / anaerobic)',
    'Urine dipstick & microscopy',
    'Urine culture & sensitivity (MC&S)',
    'Sputum MC&S',
    'Sputum AFB (acid-fast bacilli) smear',
    'Sputum GeneXpert MTB/RIF',
    'Stool MC&S',
    'Stool ova, cysts & parasites (OCP)',
    'Stool antigen (Giardia, Cryptosporidium, H. pylori)',
    'Rectal swab',
    'Wound swab MC&S',
    'Throat swab MC&S',
    'Nasopharyngeal swab (COVID / flu / RSV PCR)',
    'CSF microscopy, culture & sensitivity',
    'CSF Gram stain & India ink',
    'CSF GeneXpert',
    'CSF oligoclonal bands',
    'HIV serology (Ag/Ab combo)',
    'HIV viral load',
    'Hepatitis B (HBsAg, HBsAb, HBcAb, HBeAg)',
    'Hepatitis B viral DNA',
    'Hepatitis C (Anti-HCV)',
    'Hepatitis C viral RNA',
    'Hepatitis A IgM',
    'Hepatitis E IgM',
    'TORCH panel (Toxoplasma, Rubella, CMV, HSV)',
    'Dengue NS1 antigen',
    'Dengue IgM / IgG',
    'Leptospira IgM',
    'Malaria blood film (thick / thin)',
    'Malaria RDT',
    'Typhoid serology (Widal test / Typhidot)',
    'Brucella serology',
    'Rickettsia serology (Weil-Felix / scrub typhus IgM)',
    'Leishmania serology / rK39',
    'Fungal serology (Aspergillus, Cryptococcus Ag)',
    'Galactomannan (Aspergillus)',
    'Beta-D-glucan',
    'COVID-19 rapid antigen',
    'COVID-19 PCR',
    'Influenza A/B PCR',
    'Mycoplasma serology / PCR',
    'Chlamydia / Gonorrhoea NAAT',
    'HSV type-specific serology',
    'VZV serology',
    'EBV serology (VCA, EA, EBNA)',
    'CMV PCR / pp65 antigen',
    'Parvovirus B19 serology',
    'HPV genotyping',
  ],
  'Urine & Bedside': [
    'Urinalysis (dipstick — blood, protein, glucose, ketones, leucocytes, nitrites, pH, SG)',
    'Urine microscopy (RBC, WBC, casts, crystals)',
    'Urine protein-to-creatinine ratio (UPCR)',
    '24-hour urine collection (protein, creatinine, electrolytes)',
    'Urine beta-hCG (pregnancy test)',
    'Urine toxicology screen',
    'Urine myoglobin',
    'Capillary blood glucose (CBG)',
    'Capillary ketones',
    '12-lead ECG',
    'Ambulatory ECG (24h Holter)',
    'Blood pressure (clinic / ambulatory)',
    'Peak expiratory flow (PEF)',
    'Pulse oximetry',
    'Otoscopy',
    'Fundoscopy / Ophthalmoscopy',
    'Slit-lamp examination',
    'Tonometry',
    'Visual acuity (Snellen chart)',
    'Bedside ultrasound (POCUS)',
    'FAST scan (trauma)',
    'Capillary refill time',
    'Ankle Brachial Pressure Index (ABPI)',
  ],
  'Radiology & Imaging': [
    'Chest X-ray (PA / lateral)',
    'Abdominal X-ray (AXR) — 3 positions (supine, erect, decubitus)',
    'X-ray — limb / joint (AP + lateral)',
    'X-ray — cervical spine (AP + lateral + open-mouth odontoid)',
    'X-ray — thoracic spine',
    'X-ray — lumbar / sacral spine',
    'X-ray — pelvis',
    'X-ray — skull / facial bones',
    'X-ray — sinuses (Water\'s view)',
    'CT head (non-contrast)',
    'CT head (contrast)',
    'CT angiography head & neck (CTA)',
    'CT venogram',
    'CT chest (high-resolution / HRCT)',
    'CT pulmonary angiogram (CTPA)',
    'CT abdomen & pelvis (oral + IV contrast)',
    'CT abdomen (non-contrast — renal colic protocol)',
    'CT KUB (kidney, ureter, bladder)',
    'CT colonography (virtual colonoscopy)',
    'CT spine',
    'CT sinuses',
    'CT temporal bone',
    'CT orbit',
    'MRI brain (with / without contrast)',
    'MRI angiography (MRA)',
    'MRI venography (MRV)',
    'MRI spine (cervical / thoracic / lumbar)',
    'MRI abdomen (liver / pancreas protocol)',
    'MRI pelvis (prostate / gynaecological)',
    'MRI breast',
    'MRI cardiac',
    'MRI shoulder / knee / hip (joint-specific)',
    'MRI orbit',
    'Ultrasound abdomen (full)',
    'Ultrasound pelvis (transabdominal / transvaginal)',
    'Ultrasound renal tract',
    'Ultrasound breast',
    'Ultrasound thyroid',
    'Ultrasound scrotum',
    'Ultrasound soft tissue (lumps / abscess)',
    'Doppler ultrasound — carotid arteries',
    'Doppler ultrasound — lower limb arteries',
    'Doppler ultrasound — lower limb veins (DVT study)',
    'Echocardiogram (transthoracic — TTE)',
    'Echocardiogram (transoesophageal — TOE)',
    'Stress echo / Dobutamine stress echo',
    'Mammography',
    'DEXA scan (bone density)',
    'Ventilation / Perfusion (V/Q) scan',
    'Bone scan (Tc-99m MDP)',
    'Thyroid uptake & scan (Tc-99m / I-123)',
    'Myocardial perfusion scan (MIBI)',
    'PET-CT (FDG)',
    'PET-CT (PSMA — prostate cancer)',
    'HIDA scan (hepatobiliary)',
    'DMSA renal scan',
    'MAG3 renogram',
    'Sentinel lymph node lymphoscintigraphy',
    'Barium swallow / meal / follow-through',
    'Barium enema',
    'Small bowel series / enteroclysis',
    'Sialogram',
    'HSG (hysterosalpingography)',
    'IVU / IVP (intravenous urogram)',
  ],
  'Cardiopulmonary & Neurodiagnostic': [
    'Spirometry / Pulmonary Function Tests (PFTs)',
    'Lung volumes (plethysmography)',
    'Diffusion capacity (DLCO)',
    'Bronchial challenge (methacholine) test',
    'Exercise tolerance test (ETT / treadmill)',
    'Cardiopulmonary exercise testing (CPET)',
    '24-hour ECG (Holter monitor)',
    'Event / loop recorder',
    'Echocardiogram (see Radiology)',
    'Electroencephalogram (EEG) — routine',
    'EEG — sleep-deprived',
    'EEG — prolonged video monitoring',
    'Nerve conduction studies (NCS)',
    'Electromyography (EMG)',
    'Visual evoked potentials (VEP)',
    'Brainstem auditory evoked potentials (BAEP)',
    'Somatosensory evoked potentials (SSEP)',
    'Autonomic function tests',
    'Tilt-table test',
    'Lumbar puncture (opening pressure + CSF analysis)',
    'Polysomnography (sleep study)',
  ],
  'Endoscopy & Procedures': [
    'Upper GI endoscopy (OGD / EGD)',
    'Colonoscopy',
    'Flexible sigmoidoscopy',
    'Proctoscopy / Anoscopy',
    'Capsule endoscopy',
    'ERCP (endoscopic retrograde cholangiopancreatography)',
    'EUS (endoscopic ultrasound)',
    'Bronchoscopy (flexible / rigid)',
    'Bronchoalveolar lavage (BAL)',
    'Endobronchial ultrasound (EBUS)',
    'Cystoscopy',
    'Ureteroscopy',
    'Nasendoscopy / Nasopharyngoscopy',
    'Laryngoscopy',
    'Colposcopy',
    'Hysteroscopy',
    'Skin / punch / shave biopsy',
    'Skin scraping & microscopy (KOH / Wood\'s lamp)',
    'Punch biopsy (hair / nail)',
    'Incisional / excisional biopsy (lymph node, breast, soft tissue)',
    'Core needle biopsy (breast, thyroid, liver, kidney)',
    'FNA (fine-needle aspiration) — thyroid / breast / lymph node',
    'Bone marrow aspiration & trephine biopsy',
    'Liver biopsy',
    'Renal biopsy',
    'Endomyocardial biopsy',
    'Muscle biopsy',
    'Nerve biopsy (sural nerve)',
    'Pleural aspiration (thoracentesis)',
    'Pleural biopsy (Abrams / Tru-cut)',
    'Ascitic tap (paracentesis)',
    'Joint aspiration (arthrocentesis)',
    'Pericardial aspiration (pericardiocentesis)',
    'Arthroscopy (knee / shoulder)',
    'Lumbar puncture (see above)',
    'IV access — peripheral / central (CVC) / PICC',
    'Arterial line insertion',
  ],
  'Specialty-Specific': [
    'Ophthalmology: Slit-lamp, Tonometry, Visual fields (Goldmann / automated), Fundoscopy, Gonioscopy, Fluorescein angiography (FFA), OCT macula / RNFL, Corneal topography, Pachymetry, Schirmer test, Exophthalmometry',
    'ENT: Audiometry (pure tone / speech), Tympanometry, Otoacoustic emissions, Caloric testing / VNG, Olfactory testing',
    'Dermatology: Dermoscopy, Wood\'s lamp, Skin biopsy, Patch testing (TRUE test), KOH mount, Scabies prep (Burrow Ink Test), Tzanck smear, Bacterial swab',
    'Neurology: EMG / NCS (above), EEG (above), VEP / BAER / SSEP, Autonomic testing, Lumbar puncture (above), Muscle biopsy, Nerve biopsy',
    'Obstetrics & Gynaecology: Transvaginal ultrasound, Colposcopy, Hysteroscopy, Endometrial biopsy, Cervical smear (Pap / LBC), HPV genotyping, CTG (cardiotocography), Amniocentesis, Chorionic villus sampling (CVS)',
    'Orthopaedics: Joint aspiration, Arthroscopy, Bone scan, DEXA, CT / MRI joint-specific',
    'Cardiology: TTE / TOE, stress echo, Holter, ETT, CPET, coronary angiography (invasive / CTCA), myocardial perfusion scan, electrophysiology study (EPS)',
    'Respiratory: Spirometry, DLCO, bronchoscopy, EBUS, pleuroscopy, thoracentesis, pleural biopsy, sleep study',
    'Nephrology: Renal biopsy, DMSA scan, MAG3 renogram, ambulatory BP monitoring',
    'Gastroenterology: OGD, colonoscopy, ERCP, EUS, capsule endoscopy, hydrogen breath test, faecal calprotectin / elastase',
    'Rheumatology: Joint aspiration (crystal analysis), synovial biopsy, capillaroscopy, DEXA',
    'Paediatrics: Hip ultrasound (DDH), developmental assessment, growth chart review, newborn hearing screen, pulse oximetry screen',
    'Psychiatry: Standardised assessment tools (PHQ-9, GAD-7, MoCA, MMSE, ADOS), collateral history',
    'Urology: Cystoscopy, Urodynamics (filling / voiding), Ureteroscopy, TRUS biopsy, PSA density, urinary flow rate / post-void residual',
    'Infectious Disease: Specific serology (see above), lumbar puncture, tissue biopsy (granuloma), QuantiFERON, GeneXpert on any relevant sample',
  ],
};

window.QORA_THERAPIES = {
  'Pharmacological — Analgesia & Anaesthesia': [
    'Simple analgesia (paracetamol / acetaminophen)',
    'NSAIDs (ibuprofen, naproxen, diclofenac)',
    'COX-2 inhibitor (celecoxib)',
    'Weak opioid (codeine, tramadol)',
    'Strong opioid (morphine, fentanyl, oxycodone)',
    'IV paracetamol',
    'Ketamine (analgesic / dissociative)',
    'Local anaesthetic infiltration (lidocaine / bupivacaine)',
    'Regional anaesthesia (nerve block)',
    'Patient-controlled analgesia (PCA)',
    'Nerve block for post-op pain',
    'Neuropathic pain agent (gabapentin / pregabalin / amitriptyline)',
  ],
  'Pharmacological — Antimicrobials': [
    'Antibiotics — Penicillins (amoxicillin, co-amoxiclav, piperacillin-tazobactam)',
    'Antibiotics — Cephalosporins (cefalexin, ceftriaxone, ceftazidime, cefepime)',
    'Antibiotics — Carbapenems (meropenem, ertapenem)',
    'Antibiotics — Macrolides (azithromycin, clarithromycin)',
    'Antibiotics — Fluoroquinolones (ciprofloxacin, levofloxacin)',
    'Antibiotics — Aminoglycosides (gentamicin, amikacin)',
    'Antibiotics — Tetracyclines (doxycycline, minocycline)',
    'Antibiotics — Metronidazole / Tinidazole',
    'Antibiotics — Glycopeptides (vancomycin, teicoplanin)',
    'Antibiotics — Linezolid',
    'Antibiotics — Clindamycin',
    'Antibiotics — Co-trimoxazole (trimethoprim-sulfamethoxazole)',
    'Antibiotics — Nitrofurantoin',
    'Antifungals — Azoles (fluconazole, itraconazole, voriconazole)',
    'Antifungals — Terbinafine',
    'Antifungals — Amphotericin B',
    'Antifungals — Echinocandins (caspofungin)',
    'Antivirals — Aciclovir / Valaciclovir (HSV / VZV)',
    'Antivirals — Oseltamivir (influenza)',
    'Antivirals — Remdesivir (COVID)',
    'Antivirals — Tenofovir / Entecavir (HBV)',
    'Antivirals — Direct-acting antivirals (HCV — DAA)',
    'Antivirals — Antiretrovirals (HIV — ART per guideline)',
    'Antimalarials — Artemisinin combination therapy (ACT)',
    'Antimalarials — Chloroquine / Primaquine',
    'Antituberculars — RIFAMPICIN / INH / Pyrazinamide / Ethambutol (RHZE)',
    'Antituberculars — MDR-TB regimen (second-line)',
    'Anthelmintics (albendazole, ivermectin, praziquantel)',
    'Antiparasitics (metronidazole for amoebiasis / giardiasis)',
    'Antiseptics / topical antimicrobials (povidone-iodine, chlorhexidine, mupirocin)',
  ],
  'Pharmacological — Cardiovascular & Renal': [
    'Antihypertensives — ACE inhibitors (lisinopril, ramipril, enalapril)',
    'Antihypertensives — ARBs (losartan, candesartan, valsartan)',
    'Antihypertensives — CCB (amlodipine, nifedipine, diltiazem)',
    'Antihypertensives — Beta-blockers (bisoprolol, metoprolol, atenolol)',
    'Antihypertensives — Thiazide diuretics (HCTZ, chlorthalidone)',
    'Antihypertensives — Alpha-blockers (doxazosin, tamsulosin)',
    'Antihypertensives — Centrally-acting (clonidine, methyldopa)',
    'Antihypertensives — Vasodilators (hydralazine, minoxidil)',
    'Antianginals — Nitrates (GTN spray / patch, isosorbide mononitrate)',
    'Antianginals — Ranolazine, Nicorandil, Ivabradine',
    'Anticoagulation — Heparin (UFH / LMWH — enoxaparin)',
    'Anticoagulation — Warfarin',
    'Anticoagulation — DOACs (apixaban, rivaroxaban, dabigatran, edoxaban)',
    'Anticoagulation — Fondaparinux',
    'Antiplatelet — Aspirin',
    'Antiplatelet — Clopidogrel / Ticagrelor / Prasugrel',
    'Antiplatelet — Dual antiplatelet therapy (DAPT)',
    'Thrombolysis — Alteplase / Tenecteplase (STEMI / stroke)',
    'Heart failure — Diuretics (furosemide, spironolactone)',
    'Heart failure — Beta-blockers (bisoprolol, carvedilol)',
    'Heart failure — ACE-i / ARB',
    'Heart failure — SGLT2 inhibitor (dapagliflozin, empagliflozin)',
    'Heart failure — Sacubitril-valsartan',
    'Lipid-lowering — Statins (atorvastatin, rosuvastatin, simvastatin)',
    'Lipid-lowering — Ezetimibe',
    'Lipid-lowering — PCSK9 inhibitor (evolocumab)',
    'Inotropes / vasopressors (dobutamine, milrinone, noradrenaline)',
    'Antiarrhythmics — Amiodarone',
    'Antiarrhythmics — Beta-blockers, Verapamil, Digoxin, Flecainide, Adenosine',
    'Pulmonary hypertension — Sildenafil, Bosentan, Epoprostenol',
    'Renal — Erythropoiesis-stimulating agents (ESA)',
    'Renal — Phosphate binders (sevelamer, calcium carbonate)',
    'Renal — Vitamin D analogues (calcitriol)',
    'Renal — Potassium binders (Patiromer, sodium zirconium cyclosilicate)',
  ],
  'Pharmacological — Endocrine & Metabolic': [
    'Insulin — Rapid-acting (aspart, lispro, glulisine)',
    'Insulin — Short-acting (regular)',
    'Insulin — Intermediate (NPH)',
    'Insulin — Long-acting (glargine, detemir, degludec)',
    'Insulin — Pre-mixed',
    'Insulin — IV sliding scale / infusion',
    'Oral hypoglycaemics — Metformin',
    'Oral hypoglycaemics — Sulfonylureas (gliclazide, glibenclamide)',
    'Oral hypoglycaemics — DPP-4 inhibitors (sitagliptin, linagliptin)',
    'Oral hypoglycaemics — SGLT2 inhibitors (dapagliflozin, empagliflozin)',
    'Oral hypoglycaemics — GLP-1 agonists (semaglutide, liraglutide)',
    'Oral hypoglycaemics — Thiazolidinediones (pioglitazone)',
    'Oral hypoglycaemics — Acarbose',
    'Thyroid — Levothyroxine (T4)',
    'Thyroid — Liothyronine (T3)',
    'Thyroid — Carbimazole / Methimazole',
    'Thyroid — Propylthiouracil (PTU)',
    'Thyroid — Lugol\'s iodine / potassium iodide',
    'Corticosteroids — Hydrocortisone (oral / IV)',
    'Corticosteroids — Prednisolone / Prednisone',
    'Corticosteroids — Dexamethasone (high-dose / antiemetic)',
    'Corticosteroids — Betamethasone / Methylprednisolone (pulse)',
    'Corticosteroids — Topical (cream / ointment / eye drops)',
    'Corticosteroids — Inhaled (beclometasone, fluticasone, budesonide)',
    'Corticosteroids — Fludrocortisone (mineralocorticoid)',
    'Sex hormones — Oestrogen / Progesterone (HRT)',
    'Sex hormones — Testosterone replacement',
    'Sex hormones — Combined oral contraceptive pill (COCP)',
    'Sex hormones — Progestin-only / IUS / Implant',
    'Bisphosphonates — Alendronate, Zoledronate',
    'Denosumab',
    'Teriparatide',
    'Vitamin D / Calcium supplementation',
    'Anti-gout — Allopurinol / Febuxostat',
    'Anti-gout — Colchicine',
    'Anti-gout — NSAIDs (acute attack)',
    'Osteoporosis — Raloxifene, Strontium ranelate',
  ],
  'Pharmacological — Respiratory & Allergy': [
    'Short-acting beta-agonist (SABA) — salbutamol (MDI / nebuliser)',
    'Long-acting beta-agonist (LABA) — salmeterol, formoterol',
    'Inhaled corticosteroids (ICS) — beclometasone, fluticasone, budesonide',
    'LABA/ICS combination inhaler',
    'Long-acting muscarinic antagonist (LAMA) — tiotropium, umeclidinium',
    'LAMA/LABA combination',
    'LAMA/LABA/ICS triple therapy',
    'Montelukast (leukotriene receptor antagonist)',
    'Theophylline (oral / IV)',
    'Nebulised hypertonic saline',
    'Nebulised adrenaline (croup)',
    'Mucolytics — Acetylcysteine, Carbocisteine',
    'Antihistamines — H1 (cetirizine, loratadine, chlorphenamine, diphenhydramine)',
    'Antihistamines — H2 (ranitidine, famotidine — see GI)',
    'Adrenaline auto-injector (EpiPen — anaphylaxis)',
    'Doxapram (respiratory stimulant)',
    'Caffeine citrate (apnoea of prematurity)',
    'Pulmonary vasodilators (NO, sildenafil)',
    'Corticosteroids (systemic / inhaled — see Endocrine)',
  ],
  'Pharmacological — Gastrointestinal & Nutrition': [
    'Proton pump inhibitor (PPI) — omeprazole, pantoprazole, esomeprazole',
    'H2-receptor antagonist (H2RA) — famotidine, ranitidine',
    'Antacid / Alginate (Gaviscon)',
    'Antiemetics — Ondansetron (5HT3 antagonist)',
    'Antiemetics — Metoclopramide, Domperidone (dopamine antagonists)',
    'Antiemetics — Cyclizine (antihistamine)',
    'Antiemetics — Prochlorperazine',
    'Antiemetics — Aprepitant (NK1 antagonist)',
    'Antispasmodics — Hyoscine butylbromide (Buscopan), Mebeverine',
    'Laxatives — Bulk-forming (ispaghula husk / Fybogel)',
    'Laxatives — Osmotic (lactulose, macrogol / PEG)',
    'Laxatives — Stimulant (senna, bisacodyl)',
    'Laxatives — Rectal (glycerin suppository, phosphate enema)',
    'Antidiarrhoeals — Loperamide',
    'Antidiarrhoeals — Oral rehydration salts (ORS)',
    'Gut-specific steroids — Budesonide (ileal-release)',
    'Aminosalicylates — Mesalazine / 5-ASA / Sulfasalazine',
    'Immunomodulators — Azathioprine, 6-MP, Methotrexate (IBD)',
    'Biologics (IBD) — Adalimumab, Infliximab, Vedolizumab, Ustekinumab',
    'Anti-Helicobacter — Triple / quadruple therapy (PPI + 2 antibiotics)',
    'IV fluids — Crystalloids (normal saline, Hartmann\'s / Ringer\'s lactate)',
    'IV fluids — Colloids (Gelofusine, albumin)',
    'IV dextrose (5% / 10% / 50%)',
    'Enteral nutrition (NG / PEG feeding)',
    'Total Parenteral Nutrition (TPN)',
    'Pancreatic enzyme replacement (Creon)',
    'Ursodeoxycholic acid (UDCA)',
    'Vitamin K (for coagulopathy / warfarin reversal)',
    'Oral iron supplementation',
    'Oral B12 / Hydroxocobalamin (IM) / Folate',
    'Multivitamin / thiamine (alcohol withdrawal / Wernicke\'s)',
  ],
  'Pharmacological — Neurology & Psychiatric': [
    'Anticonvulsants — Sodium valproate / Valproic acid',
    'Anticonvulsants — Levetiracetam',
    'Anticonvulsants — Carbamazepine / Oxcarbazepine',
    'Anticonvulsants — Phenytoin',
    'Anticonvulsants — Phenobarbital',
    'Anticonvulsants — Lamotrigine',
    'Anticonvulsants — Topiramate',
    'Anticonvulsants — Clobazam / Diazepam (status / rescue)',
    'Anticonvulsants — Midazolam (buccal / intranasal) — rescue',
    'SSRI — Fluoxetine, Sertraline, Citalopram, Escitalopram, Paroxetine',
    'SNRI — Venlafaxine, Duloxetine',
    'Tricyclic antidepressants — Amitriptyline, Nortriptyline, Clomipramine',
    'MAOI — Phenelzine, Tranylcypromine, Moclobemide',
    'Other antidepressants — Mirtazapine, Bupropion, Agomelatine',
    'Antipsychotic — Olanzapine, Risperidone, Quetiapine, Aripiprazole',
    'Antipsychotic — Haloperidol, Chlorpromazine',
    'Antipsychotic — Clozapine (treatment-resistant schizophrenia)',
    'Antipsychotic — Long-acting injectable (depot — zuclopenthixol, paliperidone)',
    'Mood stabiliser — Lithium',
    'Mood stabiliser — Valproate / Lamotrigine (bipolar)',
    'Anxiolytics — Benzodiazepines (diazepam, lorazepam, clonazepam)',
    'Anxiolytics — Buspirone',
    'Hypnotics — Zopiclone / Zolpidem (short-term)',
    'Melatonin (circadian rhythm / paediatric insomnia)',
    'ADHD — Methylphenidate (short / long-acting)',
    'ADHD — Lisdexamfetamine, Atomoxetine, Guanfacine',
    'Anti-dementia — Donepezil, Rivastigmine, Galantamine (acetylcholinesterase inhibitors)',
    'Anti-dementia — Memantine (NMDA antagonist)',
    'Parkinson\'s — Levodopa / Carbidopa',
    'Parkinson\'s — Dopamine agonists (pramipexole, ropinirole)',
    'Parkinson\'s — MAO-B inhibitors (selegiline, rasagiline)',
    'Parkinson\'s — COMT inhibitors (entacapone)',
    'Parkinson\'s — Anticholinergics (procyclidine, trihexyphenidyl)',
    'Triptans — Sumatriptan, Rizatriptan (migraine)',
    'Anti-CGRP monoclonal antibodies (migraine prophylaxis)',
    'Migraine prophylaxis — Propranolol, Amitriptyline, Topiramate',
    'Alcohol withdrawal — Chlordiazepoxide (Benzodiazepine tapering)',
    'Opioid substitution — Methadone, Buprenorphine / Naloxone',
    'Smoking cessation — NRT (patch / gum / inhaler), Varenicline, Bupropion',
    'Naloxone (opioid overdose reversal)',
    'Flumazenil (benzodiazepine reversal)',
  ],
  'Pharmacological — Musculoskeletal & Rheumatology': [
    'Analgesia / NSAIDs (see above)',
    'Corticosteroids (systemic / intra-articular)',
    'DMARD — Methotrexate',
    'DMARD — Leflunomide',
    'DMARD — Sulfasalazine',
    'DMARD — Hydroxychloroquine',
    'Biologic — Anti-TNF (adalimumab, etanercept, infliximab)',
    'Biologic — Anti-IL6 (tocilizumab)',
    'Biologic — Anti-IL17 (secukinumab, ixekizumab)',
    'Biologic — Rituximab (anti-CD20)',
    'Biologic — Belimumab, Anakinra',
    'JAK inhibitor (baricitinib, tofacitinib, upadacitinib)',
    'Colchicine (acute gout / FMF / pericarditis)',
    'Allopurinol / Febuxostat',
    'Bisphosphonates / Denosumab / Teriparatide (see Endocrine)',
    'Local corticosteroid injection (joint / soft tissue)',
    'Hyaluronic acid injection (knee osteoarthritis)',
    'Muscle relaxants — Baclofen, Diazepam, Cyclobenzaprine',
  ],
  'Pharmacological — Ophthalmology & ENT': [
    'Topical antibiotic eye drops (chloramphenicol, ofloxacin, moxifloxacin)',
    'Topical corticosteroid eye drops (dexamethasone, prednisolone, loteprednol)',
    'Topical NSAID eye drops (ketorolac, diclofenac)',
    'Topical antiglaucoma — Prostaglandin analogues (latanoprost, travoprost)',
    'Topical antiglaucoma — Beta-blockers (timolol)',
    'Topical antiglaucoma — Alpha-agonists (brimonidine)',
    'Topical antiglaucoma — CAIs (dorzolamide, brinzolamide)',
    'Topical antiglaucoma — Combination drops',
    'Mydriatics / Cycloplegics (tropicamide, cyclopentolate, atropine)',
    'Lubricating eye drops / Artificial tears',
    'Antiviral eye drops (ganciclovir, aciclovir)',
    'Topical antifungal eye drops (natamycin, amphotericin B)',
    'Intravitreal injection (anti-VEGF — ranibizumab, aflibercept, bevacizumab)',
    'Ear drops — Antibiotic (ciprofloxacin, gentamicin)',
    'Ear drops — Antifungal (clotrimazole)',
    'Ear drops — Analgesic (phenazone / benzocaine)',
    'Nasal sprays — Saline irrigation',
    'Nasal sprays — Corticosteroid (mometasone, fluticasone, beclometasone)',
    'Nasal sprays — Antihistamine (azelastine)',
    'Nasal sprays — Decongestant (xylometazoline — short-term)',
    'Oral antihistamines / intranasal steroids (allergic rhinitis)',
  ],
  'Non-Pharmacological — Nursing & Supportive Care': [
    'Patient positioning (head-up / lateral / recovery position)',
    'Oxygen therapy — nasal cannula / simple face mask / non-rebreather',
    'High-flow nasal oxygen (HFNO / Optiflow)',
    'Non-invasive ventilation (CPAP / BiPAP)',
    'IV access (peripheral cannula / midline)',
    'Central venous catheter (CVC) insertion',
    'Arterial line placement',
    'Urinary catheterisation (urethral / suprapubic)',
    'Nasogastric tube (NGT) placement',
    'Wound care: cleaning, debridement, dressing (sterile technique)',
    'Pressure area care / repositioning schedule (pressure ulcer prevention)',
    'Chest physiotherapy / airway clearance techniques',
    'Suctioning (oral / tracheal / bronchial)',
    'Blood transfusion (packed RBC / platelets / FFP / cryoprecipitate)',
    'IV fluid therapy (maintenance / resuscitation / replacement)',
    'Parenteral nutrition (PN) — peripheral / central',
    'Enteral feeding — NG / PEG / NJ',
    'Bladder irrigation (3-way catheter for haematuria)',
    'Stoma care (colostomy / ileostomy / urostomy)',
    'Hot / cold compress (local symptom relief)',
    'Elastic compression stockings (DVT prophylaxis)',
    'Sequential compression device (pneumatic calf pumps)',
    'Intermittent pneumatic compression (IPC) for lymphoedema',
    'VAC / negative-pressure wound therapy (NPWT)',
    'Burn dressing (silver sulfadiazine / Biobrane / Mepitel)',
    'Splinting / immobilisation (slings, POP backslab, FUTURA splint)',
    'Traction (skin / skeletal)',
    'Cervical collar / spinal immobilisation (trauma)',
    'Limb elevation (oedema management)',
    'Ice / heat therapy (soft tissue injury)',
    'Vestibular rehabilitation / Epley manoeuvre (BPPV)',
    'Pulmonary rehabilitation (COPD / post-COVID)',
    'Cardiac rehabilitation (post-MI / post-CABG)',
    'Pelvic floor exercises / biofeedback',
    'Manual lymphatic drainage (lymphoedema)',
    'Speech and language therapy (dysphagia / communication)',
  ],
  'Non-Pharmacological — Diet & Lifestyle': [
    'Dietary modification — low salt diet (hypertension / CHF)',
    'Dietary modification — low fat / low cholesterol (hyperlipidaemia)',
    'Dietary modification — diabetic diet / carbohydrate counting',
    'Dietary modification — low FODMAP (IBS)',
    'Dietary modification — gluten-free (coeliac disease)',
    'Dietary modification — high fibre (constipation / diverticulosis)',
    'Dietary modification — renal diet (low K / low PO4 / fluid restriction)',
    'Dietary modification — hepatic diet (low protein / low Na)',
    'Dietary modification — soft / puree / liquid (dysphagia)',
    'Dietary modification — lacto-ovo vegetarian / vegan (nutritional guidance)',
    'Weight management programme (obesity counselling)',
    'Smoking cessation counselling + pharmacotherapy',
    'Alcohol reduction / abstinence advice',
    'Physical activity prescription (minimum 150 min/week moderate exercise)',
    'Structured exercise programme (IHT / hydrotherapy / gym referral)',
    'Healthy eating and portion control counselling',
    'Avoidance of trigger foods (migraine / GERD / urticaria)',
    'Hydration counselling',
    'Caffeine reduction advice',
  ],
  'Non-Pharmacological — Physiotherapy & Rehabilitation': [
    'Physiotherapy assessment and treatment plan',
    'Range of motion (ROM) exercises — passive / active-assisted / active',
    'Strengthening / resistance exercises',
    'Balance and proprioception training',
    'Gait re-education / walking aid prescription (stick, frame, crutches)',
    'Hydrotherapy / pool-based therapy',
    'Transcutaneous Electrical Nerve Stimulation (TENS)',
    'Therapeutic ultrasound (soft tissue healing)',
    'Manual therapy (joint mobilisation / manipulation)',
    'Massage therapy (sports / remedial / connective tissue)',
    'Postural correction training',
    'Ergonomic assessment and adjustment',
    'Scar massage / desensitisation (post-surgery / post-burn)',
    'Occupational therapy assessment + ADL training',
    'Home hazard assessment and modification (falls prevention)',
    'Splint / orthosis fabrication and fitting (hand therapy)',
    'Workstation ergonomics assessment',
    'Fatigue management / pacing techniques (chronic illness)',
    'Joint protection techniques (rheumatoid arthritis)',
  ],
  'Non-Pharmacological — Psychological & Behavioural': [
    'Cognitive Behavioural Therapy (CBT)',
    'CBT-I (CBT for insomnia)',
    'Acceptance and Commitment Therapy (ACT)',
    'Dialectical Behaviour Therapy (DBT)',
    'Psychodynamic psychotherapy',
    'Supportive counselling / active listening',
    'Behavioural activation (depression)',
    'Exposure and response prevention (ERP — OCD / phobias)',
    'Mindfulness-based stress reduction (MBSR)',
    'Motivational interviewing (addiction / behaviour change)',
    'Critical incident stress debriefing',
    'Trauma-focused CBT (PTSD)',
    'Eye Movement Desensitisation and Reprocessing (EMDR)',
    'Family therapy / systemic therapy',
    'Couples counselling',
    'Group therapy (substance misuse / mood disorders / grief)',
    'Parenting skills training / behavioural family intervention',
    'Social skills training (autism / schizophrenia)',
    'Cognitive rehabilitation / compensatory strategies (brain injury / dementia)',
    'Peer support group referral',
    'Carer support and respite planning',
    'Relaxation techniques (progressive muscle relaxation, guided imagery)',
    'Stress management training',
    'Sleep hygiene education',
    'Psychoeducation (diagnosis, treatment, relapse prevention)',
  ],
  'Procedures & Surgical Interventions': [
    'Incision & drainage (abscess / haematoma)',
    'Wound debridement (sharp / surgical / enzymatic)',
    'Suturing / wound closure (including adhesive / Steri-Strips / staples)',
    'Skin biopsy (punch / shave / excisional)',
    'Joint aspiration & injection',
    'Reduction of dislocation / fracture manipulation',
    'Splinting / casting / POP application',
    'Central line placement (IJ / SC / femoral)',
    'Chest drain insertion (intercostal catheter / underwater seal)',
    'Thoracentesis (pleural aspiration)',
    'Paracentesis (ascitic drain)',
    'Lumbar puncture',
    'Pericardiocentesis',
    'Bone marrow aspiration & trephine biopsy',
    'Nasogastric intubation',
    'Orogastric / NGT lavage (poisoning / GI bleed)',
    'Urinary catheterisation (urethral / suprapubic)',
    'Suprapubic catheter insertion',
    'Arterial blood gas (ABG) sampling',
    'Cardioversion (elective / emergency — synchronised)',
    'Defibrillation (VF / pulseless VT — unsynchronised)',
    'Transcutaneous pacing (bradycardia)',
    'Endotracheal intubation',
    'Tracheostomy (percutaneous / surgical)',
    'Cricothyroidotomy (emergency surgical airway)',
    'Surgical referral — General surgery',
    'Surgical referral — Orthopaedic surgery',
    'Surgical referral — Neurosurgery',
    'Surgical referral — Cardiothoracic surgery',
    'Surgical referral — Vascular surgery',
    'Surgical referral — ENT / Head & Neck',
    'Surgical referral — Ophthalmology',
    'Surgical referral — Urology',
    'Surgical referral — Gynaecological surgery',
    'Surgical referral — Paediatric surgery',
    'Surgical referral — Plastic / reconstructive surgery',
    'Surgical referral — Maxillofacial surgery',
    'Laparoscopic / open cholecystectomy',
    'Laparoscopic / open appendicectomy',
    'Hernia repair (open / laparoscopic)',
    'Bowel resection / anastomosis / stoma formation',
    'CABG (coronary artery bypass grafting)',
    'PCI / coronary stenting',
    'ERCP (endoscopic removal of CBD stone)',
    'Polypectomy (colonoscopic)',
    'Endoscopic mucosal resection (EMR)',
    'Organ transplantation referral',
  ],
  'Monitoring & Admission': [
    'Admit for observation (medical / surgical assessment unit)',
    'Admit to High Dependency Unit (HDU)',
    'Admit to Intensive Care Unit (ICU / ITU)',
    'Admit to Coronary Care Unit (CCU)',
    'Admit to stroke unit',
    'Same-day Emergency Care (SDEC / ambulatory care)',
    'Virtual ward / hospital-at-home',
    'Discharge with early follow-up (48-hour review)',
    'Monitoring — vital signs (NEWS2 / qSOFA) every 15 / 30 / 60 min',
    'Monitoring — hourly urine output',
    'Monitoring — neuro-observations (GCS)',
    'Monitoring — cardiac telemetry',
    'Continuous pulse oximetry',
    'Capillary blood glucose monitoring (CBG — sliding scale)',
    'Fluid balance chart (input/output chart)',
    'Weight monitoring (daily / weekly)',
    'Pain scoring (NPRS / FLACC / PAINAD)',
    'Sepsis screening (qSOFA / SIRS criteria)',
    'Thromboprophylaxis assessment (e.g. Wells / Caprini scores)',
    'Pressure ulcer risk assessment (Waterlow / Braden score)',
    'Falls risk assessment and prevention measures',
    'DNR / advance care planning discussion',
    'Refer to palliative care / end-of-life care team',
  ],
  'Education & Safety-Netting': [
    'Explain the diagnosis in plain language',
    'Deliver "bad news" using SPIKES protocol',
    'Provide written / printed information leaflet',
    'Red-flag return advice (symptoms that warrant immediate review)',
    'Safety-netting: specific timeframe (e.g. "return if worsening in 48h")',
    'Medication counselling (dose, frequency, adverse effects)',
    'Inhaler technique check and education',
    'Insulin injection technique counselling',
    'Activity / rest balance guidance',
    'Return to work / school advice',
    'Driving advice (including notifiable conditions — DVLA / local authority)',
    'Travel health advice (vaccinations, malaria prophylaxis)',
    'Contraception counselling',
    'Pre-conception counselling',
    'Antenatal / postnatal education',
    'Fluid / dietary intake specific counselling',
    'Caregiver training (wound care, medication administration)',
    'Plan for routine follow-up appointment (specialist / GP)',
    'Refer to community / primary care team',
    'Referral to allied health: dietitian, physio, OT, SALT, psychologist',
    'Refer to social services / social worker (discharge planning)',
    'Refer to palliative care / hospice services',
    'Refer to pain management clinic',
    'Refer to smoking cessation service',
    'Referral to exercise on prescription / health trainer',
    'Referral to vision rehabilitation / low vision clinic',
    'Referral to hearing aid services / audiology',
    'Referral to falls prevention service',
    'Referral to memory clinic',
    'Referral to sexual health / GUM clinic',
    'Referral to drug & alcohol service',
    'Address ideas, concerns & expectations (ICE framework)',
    'Arrange interpreter / translation services if needed',
    'Provide emergency contact numbers / crisis line',
  ],
};

// Convenience: total item counts for reference
(function () {
  var invCount = 0;
  for (var cat in window.QORA_INVESTIGATIONS) {
    invCount += window.QORA_INVESTIGATIONS[cat].length;
  }
  var txCount = 0;
  for (var cat in window.QORA_THERAPIES) {
    txCount += window.QORA_THERAPIES[cat].length;
  }
  window.QORA_CATALOG_STATS = { investigations: invCount, therapies: txCount };
  // eslint-disable-next-line no-console
  if (typeof console !== 'undefined') console.log('[qora-catalog] ' + invCount + ' investigations, ' + txCount + ' therapies loaded.');
})();
